### ISSUE TITLE
TeXlike parser passthrough commands match any environment style closing tags, not matched pairs

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1003]
Previous discussion on a related issue at end of #947.

Consider:

## `environment_mismatch.sil`
```tex
\begin[papersize=250mm x 125mm]{document}
\script{
SILE.registerCommand("texmode", function(_, content) SILE.doTexlike(content[1]) end, "texmode")
}
\begin{texmode}
\par\begin{center}\font[size=14pt]{\strong{Morality test---no cheating!}}\end{center}
\par ``Is this, dare I say, \em{evil}?''
\par ``Ito ba---`wag po kayo ma--offend ha---isa~~{n}g \em{kasalanan}?''
\end{texmode}
\end{document}
```

Ran as:

```bash
sile -e 'SILE.inputs.TeXlike.passthroughCommands.texmode = true' environment_mismatch.sil
```

Returns:

```
This is SILE v0.10.9.r36-gf16af44
<environment_mismatch.sil>

Error detected:
	["\begin[papersize=250..."]:6: parse error, Environment mismatch
\par\begin{center}\font[size=14pt]{\strong{Morality test---no cheating!}}\end{center}
                                                                              ^

shell returned 1
```

## `no_environment_mismatch.sil`

Yet, the supposedly equivalent...

```tex
\begin[papersize=250mm x 125mm]{document}
\script{
SILE.registerCommand("texmode", function(_, content) SILE.doTexlike(content[1]) end, "texmode")
}
\texmode{
\par\begin{center}\font[size=14pt]{\strong{Morality test---no cheating!}}\end{center}
\par ``Is this, dare I say, \em{evil}?''
\par ``Ito ba---`wag po kayo ma--offend ha---isa~~{n}g \em{kasalanan}?''
}
\end{document}
```

Runs without issue.

```
This is SILE v0.10.9.r36-gf16af44
<no_environment_mismatch.sil>
[1] 
```

![image](https://user-images.githubusercontent.com/838783/89092053-9c4e3d00-d37c-11ea-9cef-679c112d6ca4.png)

`SILE.inputs.TeXlike.passthroughCommands` should be fixed to support both types of invocation: as environment or as command.

**Comment by ctrlcctrlv** [comment]
OK, I think I know why this is happening. No clue how to fix it, @alerque is the LPEG grammar expert :-)

But, `V"environment"` considers any `\end` as ending the outer `texmode` environment as it's not considering the `\begin` because it's being passed through! :rofl: 

https://github.com/sile-typesetter/sile/blob/3d0c0a3a22a758029e252e2e2da8f26af7f7c064/core/inputs-texlike.lua#L75-L91

**Comment by ctrlcctrlv** [comment]
Oh, and here's a silly workaround, because why not&hellip;

```tex
\begin[papersize=250mm x 125mm]{document}
\script{
SILE.registerCommand("texmode", function(_, content) SILE.doTexlike(content[1]:gsub('\\begin {', '\\begin{'):gsub('\\end {', '\\end{')) end, "texmode") -- } } } }
}
\begin{texmode}
\par\begin {center}\font[size=14pt]{\strong{Morality test---no cheating!}}\end {center}
\par ``Is this, dare I say, \em{evil}?''
\par ``Ito ba---`wag po kayo ma--offend ha---isa~~{n}g \em{kasalanan}?''
\end{texmode}
\end{document}
```
Just add spaces to all internal environments, then remove the spaces before calling `SILE.doTexlike`.

**Comment by alerque** [comment]
I'm still scratching my head here, but here is a simplified MWE:

```sile
\begin{document}
\begin{script}
SILE.registerCommand("texmode", function() end)
\end{script}
\begin{texmode}
\begin{center}test\end{center}
\end{texmode}
\end{document}
```

Here's the weird bit: this only seems to be a problem for exact command definition `texmode`. If I change that to seemingly anything else (e.g. `foo` or `texmode2` or `tex` or `mode` or `modetex` or ... I tried quite a few things) it seems to work fine. But plug `texmode` in as the command being registered and it all goes sideways.

**Comment by alerque** [comment]
Okay here it is even simpler without messing with the built in passthrough list:


```sile
\begin{document}
\begin{script}
-- \end{foo}
\end{script}
\end{document}
```
