### ISSUE TITLE
[svg] "Holes" not appearing as holes

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1005]
![image](https://user-images.githubusercontent.com/838783/89100904-199f9f00-d3c9-11ea-8d96-1ebc5f02a38b.png)

Should appear as:
<img src="https://user-images.githubusercontent.com/838783/89101003-253f9580-d3ca-11ea-8e17-ee8ecbeeb852.png" width="300">

MWE:
```
\begin{document}
\script[src=packages/svg]
hi % avoids #1004

\center{\include-svg-file[src=mojikyo_tkana.svg,height="10%ph"]}
\end{document}
```

SVG: 
[MWESVG.zip](https://github.com/sile-typesetter/sile/files/5010304/MWESVG.zip)

**Comment by ctrlcctrlv** [comment]
And, as no bug report would be complete without a workaround, I've worked around this issue in my case by opening it in Inkscape, breaking apart the paths, putting the "holes" on top via <kbd>PgUp</kbd>, and giving them white fills.

![image](https://user-images.githubusercontent.com/838783/89101131-376e0380-d3cb-11ea-95fe-8477a65d9ec0.png)

**Comment by alerque** [comment]
I have (somewhat to my disappointment) confirmed that this is probably *not* an upstream bug in the [nanosvg](https://github.com/memononen/nanosvg) which we use to load the SVG data. At least using it's demo app to render the MWE here as a PNG, the holes are transparent:

![image](https://user-images.githubusercontent.com/173595/89425212-64ab1080-d741-11ea-9502-634b321f61d1.png)

It still could be a glitch  somewhere in talking to `nanosvg` but more likely it is our own code converting to PostScript.

**Comment by ctrlcctrlv** [comment]
@alerque Something seems really broken here. I took a page out of your playbook and simplified my MWE to the point the SVG no longer needs a zip...

## `hole.svg`
```svg
<svg
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    viewBox="0 0 150 150"
>
        <path 
            d="M 10 10 L 10 90 L 90 90 L 90 10 L 10 10 z M 20 20 L 40 20 L 40 40 L 20 40 L 20 20 z"
            fill="black"
        />
</svg>
```

### In Firefox
![image](https://user-images.githubusercontent.com/838783/89475484-32f07480-d756-11ea-9b66-6eef87ae878d.png)

## `hole.sil`
```
\begin{document}
\script[src=packages/svg]
% thanks for fixing #1004
\include-svg-file[width=20%pw, src=hole.svg]
\end{document}
```

### SILE v0.10.9.r108-gb6f880e
![image](https://user-images.githubusercontent.com/838783/89475594-76e37980-d756-11ea-851f-5bdeab9c8604.png)

**Comment by ctrlcctrlv** [comment]
Nobody seemed to care about this problem, so I decided to be the change I wanted to see in the world.

![image](https://user-images.githubusercontent.com/838783/90610885-e88ddf80-e1ba-11ea-8528-68d1a01994e6.png)

The problem is `src/svg.c` function `svg_to_ps` as @alerque predicted. Really it's simple, y'all are doing it wrong. PR incoming once I clean up my code and write a test or two. :-)

**Comment by alerque** [comment]
@ctrlcctrlv Please don't assume that unfixed issues are because "nobody cares". I do care about this issue, but I have a family to support and a primary role in life outside of software too. Besides at the moment 1 supporter on Github (thanks!) I don't get paid for developing SILE or even for *any* of the projects that I use it for, so I can't always take the time off to dive in to fixing all issues when they are reported.

Thanks for tackling this one yourself. Improved SVG support will benefit everyone.

**Comment by ctrlcctrlv** [comment]
Oh I'm surprised there's only one supporter. When I get back on my computer I'll look into becoming your second one :-)

Sorry for assuming this project was more popular than it was.

**Comment by ctrlcctrlv** [comment]
OK, now you have two sponsors :-)

Sorry, can't afford much more than that at the moment.

**Comment by alerque** [comment]
Wow @ctrlctcrlv thanks for that! I hope you and many others get lots of millage out of SILE.
