### ISSUE TITLE
Better stair ("bumpy road") logo possible

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1016]
I was going to PR this directly but was blocked by #1015, however I don't want to forget.

The stair logo in the manual (as of v0.10.9, &sect;6.1, p. 55), which I've copied into more than a few of my documents, could be improved.

Out with the old:
```tex
\define[command=SILEold]{S\lower[height=0.5ex]{I}L\glue[width=-.2em]\raise[height=0.6ex]{\font[size=0.8em]{E}}}
```

Right now, it uses a text size to make the smaller ⟨E⟩.

This looks, IMO, ugly, because it's essentially equivalent to the [fake small caps problem](https://practicaltypography.com/small-caps.html): the widest stroke of ⟨E⟩ is not equal to that of ⟨L⟩.

And in with the new:
```tex
\define[command=SILEnew]{S\lower[height=0.5ex]{I}L\glue[width=-.2em]\raise[height=0.6ex]{\font[features=+smcp]{e}}}
```

The problem is more acute with serif types, but keen eyes can notice it in sans-serif:

![image](https://user-images.githubusercontent.com/838783/89532574-d9646600-d7a6-11ea-899e-0406f487bb5c.png)

As luck would have it, my favorite font for use in SILE, EB Garamond, is worst affected of my sample.

I thought of this when rewriting the famous `\LaTeX` macro into SILE-speak:

```tex
\define[command=LaTeX]{\begin[family=Latin Modern Roman]{font}L\glue[width=-.3em]\raise[height=0.4ex]{\begin[family=Latin Modern Roman Caps]{font}A\end{font}}\glue[width=-.13em]T\glue[width=-.2em]\lower[height=0.5ex]{E}\glue[width=-.13em]X\end{font}}
```

Note the use of <kbd>Latin Modern Roman Caps</kbd>.

_Is this the most important issue facing SILE right now?_ **No**... It's still an issue, though!! 🤣

**Comment by alerque** [comment]
I agree, this is a visual improvement and I'd be happy to accept it as a PR. It does use an extra concept, but it was previously introduced in the manual and we might as well put the best foot forward when possible. At least explain very briefly that a font size adjustment could have been used but the small caps feature was chosen to keep the visual weight similar, and reference the section of the manual (§5.7) that has font feature usage.

While you are at it, I think the usage of `\glue` for tweaking the tracking should actually be `\kern` it all cases. Glue's typically allow breaks and can be dropped in some cases, Kern's are for keeps.
