### ISSUE TITLE
\tableofcontents should output PDF table of contents

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1026]
PDF's may contain a table of contents; the `\tableofcontents` should output it. Examples of the format may be found [here @ p. 4](https://www.lexjansen.com/seugi/psug2001.pdf) and [here @ Example 4](https://www.w3.org/WAI/WCAG21/Techniques/pdf/PDF2.html#examples).

This is something I'd really love to see. It seems like I might need to add it to the C library `justenoughlibtexpdf`? I think that it'd be much easier for y'all to do it than me as I've never even built that, but this is something I'd really like to see, so if you're not interested @simoncozens @alerque tell me and I'll dig in, probably annoying you w/questions :o)

**Comment by alerque** [comment]
SILE already does this. Note for example the PDF outline for the manual:

![image](https://user-images.githubusercontent.com/173595/90231909-86348800-de24-11ea-96ce-ed2d46291df5.png)

**Comment by ctrlcctrlv** [comment]
Sorry to bother you, my mistake.

**Comment by ctrlcctrlv** [comment]
Sorry to bother you again @alerque but can I know where the code for this is? I think it only happens in the `book` class, right (might be why I thought it didn't work as I didn't used to use the book class, or maybe I was just expecting it to work without `\tableofcontents`)? But `\pdf:bookmark` doesn't seem to be called anywhere?

**Comment by alerque** [comment]
I don't think `\tableofcontents` has anything to do with it, I believe `\chapter` and other section commands call the bookmark, but it might be in the section number tracking code too.

**Comment by ctrlcctrlv** [comment]
Yeah I'm lost, I've tried for an hour and got nowhere. `\pdf:bookmark` is certainly a dead end. It's implemented by calling `pdf_bookmark` in `justenoughlibtexpdf.c`, so perhaps it's being called by some other SILE internal? Is there an implicit call somewhere? I `grep`'d a bunch of stuff in `/opt` (which on my system only contains SILE), and am just as confused.

Sad, I wanted to PR some fixes for it since for me it doesn't result in good output in some cases...

**Comment by alerque** [comment]
The `\pdf:bookmark` command is just being called by a wrapper around the `\tocentry` command that adds the PDF bookmarking at the same time the TOC thing saves its entry for later use.

https://github.com/sile-typesetter/sile/blob/master/packages/pdf.lua#L41-L51
