### ISSUE TITLE
SILE should have a command to initialize a project

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1038]
Something like `cargo init`.

E.g.:

```bash
#!/bin/bash

mkdir "$1"
cd "$1"
cat << EOF > "${1}.sil"
\\begin[class=book]{document}

\\end{document}
EOF

mkdir doc_packages

if [[ ! -z $SEED_FROM ]]; then
    cp -r $SEED_FROM/doc_packages doc_packages
fi

cat << EOF > Makefile
# Makefile for SILE originally by Caleb Maclennan.
# This file is CC-BY-SA 4.0: 
# https://github.com/ctrlcctrlv/PamudpodUnicodePaper/commit/4d84d04f100e2265acbaaddc910bea080ef4df9d.patch
# Some modifications have been made by Fredrick Brennan (@ctrlcctrlv):
#  * added OPEN flag.

SHELL = bash
.ONESHELL:
.SECONDARY:
.SECONDEXPANSION:

OUTPUTS = $1.pdf

all: \$(OUTPUTS)

# This is a monkey patch to figure out how many passes we have to to to garantee the TOC is up to date,
# simplify when #230 is fixed.
hastoc = [[ -f \$(subst .pdf,.toc,\$@) ]] && echo true || echo false
pages = pdfinfo \$@ | awk '\$\$1 == "Pages:" {print \$\$2}' || echo 0
silepass = sile \$< -m -o \$@ && pg0=\$\${pg} pg=\$\$(\$(pages))

include \$(wildcard %.d)

# Why does this run SILE twice if exit status is > 0?
%.pdf: %.sil
	pg0=\$\$(\$(pages)) hadtoc=\$\$(\$(hastoc))
	\$(silepass)
	export -n SILE_COVERAGE
	if \$(hastoc); then
		\$\${hadtoc} || \$(silepass)
		[[ \$\${pg} -gt \$\${pg0} ]] && \$(silepass) ||:
	fi
	if [[ ! -z \$\${OPEN} ]]; then nohup xdg-open \$(outputs) 2>&1 > /dev/null; fi
EOF

>&2 echo Initiated "$1"
```

**Comment by alerque** [comment]
The vast majority of the code there is to work around #230. When that is fixed what would be left would be a trivial 3 liner. Given the plethora of build systems this _could_ fit into I don't think baking one in is a good plan. I have some experience trying to make build systems that work across platforms and it's a hard nut to crack. I think inviting it into the scope of SILE itself would start getting un into trouble and actually limit how people use SILE more than expand it.

As such what I think should happen is:

* Effort should be made to figure out how to loop internally so we can solve the TOC thing.
* The manual should be expanded with a note on build systems and how the GNU Make dependency generation can be used as simply as possible (i.e. why that `include $(wildcard %.d)` thing works).

Also of note, CaSILE *does* have an `init` function. Although the current iteration doesn't accomplish the same thing, it's in transition to a `setup` command that will do exactly this: initialize a project with a build system. I think that's the correct place to do this. I think with the new CLI based setup CaSILE will be suitable even for small builds like the ones you show, but if a lighter weight system is also needed maybe post it to a Gist and save it as a bash script in your `~/bin` and call it a day.
