### ISSUE TITLE
No  pdf output

### ISSUE THREAD

**Issue by yakoum** [sile-typesetter/sile#1050]
I installed sile on ubuntu 20.04  french (instructions page 14 sile Book).

`sudo add-apt-repository ppa:sile-typesetter/sile

sudo apt-get update

sudo apt-get install sile`

create file test.sil.
I get  :  Erreur de segmentation (core dumped)  what's that mean segmentation error (core dumped).

Any advice  ? I am beginner.

**Comment by alerque** [comment]
This probably means something is wrong with dependencies. I'll have access to an Ubuntu test rig briefly tonight and give it a quick test.

In the mean time can you show us the exact command you ran and the exact output. Often there is information about the location the error occurred besides just the error itself.

Also maybe send us the exact output of `sile --version` just to confirm what actually made it into your path, and try `sile -t test.sil` sometimes given more trace information about the error. The contents of your *test.sil* might have clues too.

Also can you confirm you didn't do anything manually such as check out the SILE source or anything that could be getting mixed up with the packaged version?

**Comment by yakoum** [comment]
I get the same error with sile --version   and sile -t test.sil  :

erreur de segmentation (core dumped)  segmentation error (core dumped).




    Le mardi 1 septembre 2020 à 15:07:07 UTC+2, Caleb Maclennan <notifications@github.com> a écrit :  
 
 


This probably means something is wrong with dependencies. I'll have access to an Ubuntu test rig briefly tonight and give it a quick test.

In the mean time can you show us the exact command you ran and the exact output. Often there is information about the location the error occurred besides just the error itself.

Also maybe send us the exact output of sile --version just to confirm what actually made it into your path, and try sile -t test.sil sometimes given more trace information about the error. The contents of your test.sil might have clues too.

Also can you confirm you didn't do anything manually such as check out the SILE source or anything that could be getting mixed up with the packaged version?

**Comment by alerque** [comment]
I just fired up a brand new fresh machine with Ubuntu 20.04. As soon as it booted up to a terminal I ran the commands as documented (adding the PPA, refreshing, and installing SILE). As soon as the commands ran `sile --version` worked fined and I tested it building PDFs.

Hence I'm pretty sure the packaging isn't itself broken. I was worried I'd accidentally uploaded something to the Focal (20.04) packaging that was built for Bionic (18.04) or some mistake like that, but it seems to be clean on that score.

At this point I'm not sure what to even tell you. I'd be happy to fix anything on SILE's end, but it sounds to me like you make have other issues with your system. Here are a few stabs in the dark:

* Can you run `which sile` to find the full path, and confirm that's from the system package and not some directory you downloaded.

* Try running `head -n2 $(which sile)`. For an original bonified Focal build it should read:
  ```
  #!/usr/bin/lua
  SYSTEM_SILE_PATH = "/usr/share/sile" -- global used in core/packagemanager
  ```

* Can you run your system's Lua executable okay? Try it like this:
  ```console
  $ /usr/bin/lua -v
  Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
  ```

**Comment by yakoum** [comment]
$ which sile

/usr/bin/sile

$ head -n2 $(which sile)

#!/usr/bin/lua

SYSTEM_SILE_PATH = "/usr/share/sile" -- global used in core/packagemanager

$ lua -v
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio

**Comment by alerque** [comment]
Okay I see the trouble there. Your `/usr/bin/lua` is **not** the default Ubuntu 20.04 Lua package that the SILE package was built with. I don't know where you came up with that (Lua 5.3.5), but the default packages –and hence what the SILE PPA is built against– is Lua 5.2.4 as shown in my output above.

How you fix this probably depends on how you ended up with that version of Lua in the first place. Some ideas:

* You could revert whatever you did to customize your system and go back to the `lua52-*` packages as the default Lua,
* or perhaps you still have Lua 5.2 under a different bin path, in which case you could actually edit that first line of `/usr/bin/sile` to point to it, for example maybe `#!/usr/bin/lua52`.
* You could also compile SILE yourself using your own system libraries. SILE itself doesn't have any problem with Lua 5.3, it only cares that it is run under the same version it was compiled with. You could either build an Ubuntu package with a slightly modified dependency from the one in the PPA or just do an install from source.

**Comment by yakoum** [comment]
I moved to ubuntu recently, if I change the first line  of  `/usr/bin/sile `  where to  put ` #!/usr/bin/lua5.2` to point to it ?

**Comment by alerque** [comment]
If your system has a fully functional Lua 5.2 install, that's what you need to point to. If it doesn't you need to get one, or switch to a SILE built for Lua 5.3. Does running `lua5.2 -v` show anything?

How did you end up with a non-default Lua anyway?

**Comment by yakoum** [comment]
Yes Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio

**Comment by alerque** [comment]
In that case I would guess the only thing you need to do is change the first line of `/usr/bin/sile` to read `#!/usr/bin/env lua5.2`. You'll need do edit it with root permissions of course. I don't think anything else will need changing. You'll need to re-edit the line every time the SILE package updates though.

The question still remains how you ended up with Lua 5.3 as the default Lua on Ubuntu 20.04. There may or may not be something I can do about the original packaging to save other users in the same situation, but not knowing what the situation is or how you got there I can't do anything. If you let me know what you may have done that landed you in that environment I can try to replicate it.

**Comment by yakoum** [comment]
Sorry, what I change  exactly in the first line to tell sile to point to lua 5.2 and I'll do it .

**Comment by alerque** [comment]
What I wrote above *was* the entire first line, replace what is there (starting `#!`) with this:

```
#!/usr/bin/env lua5.2
```

An alternative way to accomplish the same thing without editing the file is launch SILE differently.
Instead of doing this:

```console
$ sile test.sil
```

Do this:

```console
$ lua5.2 /usr/bin/sile test.lua
```

You still haven't answered the question about your system. Have you done anything special getting it setup like installing alternate Lua packages?

**Comment by yakoum** [comment]
I edit  the first line and it works like a charm ! Thank you.
Is it possible now to configure texstudio to work with sile ?   what I can put  in the command ?' sile  %.sil'

**Comment by ctrlcctrlv** [comment]
I don't think so @yakoum. SILE is not LaTeX-compatible and its syntax is not perfectly TeX-like. My package [sile-texmode](https://github.com/ctrlcctrlv/sile-texmode) can get you some of the way there but even I'm not interested in making SILE perfectly TeX-like&mdash;for example, I _like_ having numbers in commands.

**Comment by yakoum** [comment]
@harrysummer did it : 
[https://github.com/sile-typesetter/sile/issues/410](url)

**Comment by alerque** [comment]
Yes it's almost certainly possible to configure texstudio to build SILE files, but why? Personally I recommend using a generic programming editor (VSCode or Atom or Sublime or whatever you like). All of these can be configured with a build command too. You're welcome to do what you want and use texstudio if you like, but it's not officially supported.

Meanwhile you still haven't answered my questions about your system. I'd like to know how your situation with Lua happened so we can avoid it being a problem for others (and yourself the next time I update the PPA) but you still haven't answered any of my questions.

**Comment by yakoum** [comment]
I followed a tutorial on the official ubuntu page. I used to install  development versions of  software : R, povray,... under windows.  Now I use ubuntu 20.04 . manipulations of a real beginner, because I wanted to go fast, learn everything.
Sorry for my bad english !

**Comment by alerque** [comment]
Glad it works for you now.
