### ISSUE TITLE
wrong space before new frames?

### ISSUE THREAD

**Issue by ousia** [sile-typesetter/sile#1053]
@simoncozens,

congratulations for the SILE typesetter and many thanks for releasing it under a free license.

Paging through the manual, I have noticed that there are two points with wrong spacing before new frames:

1. https://sile-typesetter.org/manual/sile-0.10.10.pdf#nameddest=dest4.
1. https://sile-typesetter.org/manual/sile-0.10.10.pdf#nameddest=dest61.

I think there might be a problem there.

Just in case it helps.

**Comment by alerque** [comment]
Thanks for taking the time to report these @ousia.

1. This one is very much a know issue in relation to floating frames, currently tracked as #860 for the manual specifically but also more generically in #394.

2. Correct me if I'm missing what you are seeing, but as far as I can tell this one isn't actually a bug. It's true that there is a visual clash of information on the page, but for a justifiable reason. The red box and frame ID is debug information and choosing to output debug information *should not* affect the page layout. This can and will result in debug information being drawn on top of content, but if you re-render the PDF without debug information nothing should move and what you are left with will appear to have the correct spacing.

   Secondarily for this second one there is a small issue *after* the frame for the drop-cap ‘C’ in that the reflow happens a line after it should probably end, but this is tracked in issue #560.
