### ISSUE TITLE
Extra space added by `\code` as defined in `packages/url`

### ISSUE THREAD

**Issue by jmaibaum** [sile-typesetter/sile#1056]
Using SILE 0.10.10, and typesetting the following example:

```sile
\begin{document}
\script[src=packages/url]
The \code{\\code} command defined in \code{packages/url} typesets an extra space at the end, see:
\url{https://github.com/sile-typesetter/sile/blob/bd7e52e75663b861ee0bb57876204e740f518fbc/packages/url.lua#L47}.
Most likely I simply don’t know the use cases this extra space enables, but to the casual user,
this looks like a clear bug.
\end{document}
```

produces this output:

![Bildschirmfoto von 2020-09-12 17-45-04](https://user-images.githubusercontent.com/3957164/92999255-bfddd900-f51f-11ea-9205-e9555d35ec16.png)

https://github.com/sile-typesetter/sile/blob/bd7e52e75663b861ee0bb57876204e740f518fbc/packages/url.lua#L47

Commenting out the line locally fixes the example above:

![Bildschirmfoto von 2020-09-12 17-42-08](https://user-images.githubusercontent.com/3957164/92999193-670e4080-f51f-11ea-99d2-556f06dded51.png)

Does not typesetting this extra space break important stuff elsewhere?

I stumbled upon this while trying out @alerque's [WIP SILE writer for pandoc PR](https://github.com/jgm/pandoc/pull/6088) where using the standard markdown backticks syntax ends up using the `\code` command from `packages/url`.

**Comment by jmaibaum** [comment]
In case this *is* considered a bug, I have just filed a quick PR.

**Comment by alerque** [comment]
That looked pretty bizarre to me. I was even more chagrined to run `git blame` on the original `\code` function and find it tracked back to *my* commit 50fc3b3f3 with no explanation for the space.
