### ISSUE TITLE
The breadcrumbs utility doesn't work when SILE run under LuaJIT

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1069]
It doesn't crash, but the stack is never populated with commands and hence any attempt to use them (for example to find the parent of a command) fails to do anything useful.

This is probably a direct consequence of the stackTrace module also not working (see #1013).

**Comment by Omikhleia** [comment]
Unless mistaken, this "breadcrumbs" thing  is unused in the current code, a search on that keyword only provided unused things (?):
![image](https://user-images.githubusercontent.com/18075640/159165613-dd0b559d-9603-4eeb-b476-8bee1cc678a7.png)

It's also undocumented.

From my perspective: without documentation, actual use and justification, I'd suggest to remove it from the standard/default typesetter. It doesn't seem to belong here. And if it ever did at some point, I'd question the rationale for having it here (rather, say, depending on what it was supposed to address, a dedicated packages and/or a subclass of typesetter).

**Comment by alerque** [comment]
I use it in production for quite a few projects. It's not properly documented but it is quite useful and not something that can be retrofitted from a package outside of core.

**Comment by alerque** [comment]
As a jumpstart on documentation, among many other uses one of the things this does is allow functions to behave different based on their parent content. For example consider equivalent CSS examples:

```css
strong {
	font-weight: 600;
}
.epigraph strong {
	font-weight: 800;
}
```

```lua
SILE.registerCommand("strong", function (_, content)
    local weight = SILE.typesetter.breadcrumbs:contains("epigraph") and 800 or 600
	SILE.call("font", { weight = weight }, content)
end)
```

Or for direct children rather than descendants:

```css
strong {
	font-weight: 600;
}
.epigraph > strong {
	font-weight: 800;
}
```

```lua
SILE.registerCommand("strong", function (_, content)
    local weight = SILE.typesetter.breadcrumbs:parent(1) == "epigraph" and 800 or 600
	SILE.call("font", { weight = weight }, content)
end)
```

**Comment by Omikhleia** [comment]
Interesting! Would I have known about this "hidden" and pretty obscure mechanism, it could have made my XML processing much easier. I resorted on looping in structural nodes to propagate parent information (e.g. [here](https://github.com/Omikhleia/omikhleia-sile-packages/blob/ad7c0d08498f2ef64c576c5fffd717fac02623ce/packages/teidict.lua#L126)...) - It actually means however that a package can do it (at some pain) without core support...

Still, it's interesting, but why does it have to be reconstructed in the typesetter(*) and be based on some complex underlying trace stack system? Why isn't it simply in the AST construction? Is there a good rationale for it? (*) It also makes me wondering how it behaves when typesetter are switched.

**Comment by alerque** [comment]
> Still, it's interesting, but why does it have to be [...] based on some complex underlying trace stack system? Why isn't it simply in the AST construction?

> It also makes me wondering how it behaves when typesetter are switched.

These two bits are directly related. It is based on Lua function nesting (by logging the stack trace data in the typesetter) so that it is *not* tied to the AST — knowing the tree position in the AST can be useful but it does not accomplish the same thing. If some of your AST is typeset with one typesetter and other bits with another then the breadcrumbs will match the actual nested functions being used to process the content. This is more flexible than just the AST nesting. In many cases the same information could be derived from the document tree alone (as in fact CSS selectors rely on) but for more complex results the binding between content and style is too close for my liking, not to mention the code to achieve it being much more verbose.

**Comment by alerque** [comment]
Just to clarify from my earlier statement: the breadcrumbs thing itself could be bolted on in a package, it is just a tidy API bolted on to the inner workings of the trace stack. The latter needs to be in core, but the friendly end use access to it *could* be a package. I just don't see the point in doing so.

**Comment by alerque** [comment]
A related rabbit trail: if breadcrumbs were working on LuaJIT that might give us a way to handle context sensitive things inside `SILE.process()`. One such use case cropped ip in #1350, see especially [this discussion](https://github.com/sile-typesetter/sile/pull/1350#discussion_r841222976).

**Comment by alerque** [comment]
Somewhat to my relief after discovering #1013 has been fixed for a while, this bug remains unsolved. I've also narrowed it down to LuaJIT not being able to access globals from inside a table's metatable in the same way as Lua.

```lua

t = { 1, 2 }

local c = function (t)
  local a = {}

  setmetatable(a, {
    __len = function ()
      return #t
    end
  })

  function a:foo ()
    return #a
  end

  return a
end

a = c(t)

print(#a)
```

Lua prints 2 as expected, LuaJIT prints 0.

**Comment by alerque** [comment]
Not quite right, the issue isn't globals. It's that LuaJIT doesn't support `:__len()` metamethods unless compiled with `-DLUAJIT_ENABLE_LUA52`, which is not really something we can count on.
