### ISSUE TITLE
Add NetBSD installation instructions

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1077]
I see SILE has turned up [in the NetBSD package collection](https://pkgsrc.se/print/sile). I'd like to add a mention to the manual with brief installation instructions to go along with other platforms that have preconfigured packages. @jsonn or @iamleot can you perhaps suggest a couple sentences and whatever the appropriate one-liner command is for installation? For reference here is the bit of the manual that mentions other platforms with similar blurbs:

![image](https://user-images.githubusercontent.com/173595/95008601-f214bf00-0623-11eb-8550-5b70e6b437a6.png)

Also are there any buttons I should push to flag the package for update or anyone on the pkgsrc side of things that would appreciate a ping when we cut releases? I usually run though a checklist when cutting releases that include distributions to either submit updates to, flag as outdated, or otherwise notify (e.g. for [v0.10.11](https://github.com/sile-typesetter/sile/issues/1067)). If there is anything we can do on this end to facilitate smooth and timely updates we'd be glad to help.

**Comment by jsonn** [comment]
Building from source: `cd print/sile && bmake install`
Installing a binary package: `pkgin in sile`

**Comment by jsonn** [comment]
You can ping either myself or wiz@NetBSD.org for updates, at the very least it will end up on the TODO list that way.

**Comment by alerque** [comment]
Is the TODO list public somewhere I can check the status? It probably doesn't make sense to ping about an update if there is still a previous TODO item pending.
