### ISSUE TITLE
Allow inline SVG content

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1091]
Having to source SVG content from an external file is fine for many circumstances, but for some uses it would be a lot more convenient to inline the actual XML content in the `\svg{}` tag.

A previous PR #1011 already laid some of the groundwork for this, but didn't actually implement it. The SVG tag should be marked as a pass-through command and if the `src` option is not used it should try to parse its own content as the vector content.

**Comment by Omikhleia** [comment]
I think #1347 (along with and #1373) closed this issue.

**Comment by alerque** [comment]
True story, thanks for the issue triage comments.
