### ISSUE TITLE
`luarocks install` on rockspec file does not work

### ISSUE THREAD

**Issue by OlivierNicole** [sile-typesetter/sile#1098]
When I try to install the required Lua packages as indicated in https://github.com/sile-typesetter/sile#from-source, it fails:
```
$ sudo luarocks install sile-dev-1.rockspec

Error: File not found: ...
```

**Comment by alerque** [comment]
The file [does exist](https://github.com/sile-typesetter/sile/blob/master/sile-dev-1.rockspec) at the root of the repository. I suspect you tried running that command from somewhere else. You need to be `cd`'ed into the source directory (either your `git clone` or the extract of a source tarball) before running that command.

**Comment by OlivierNicole** [comment]
I am in the `.rockspec` file's directory. I suspect that the error message is rather related to this line of said file:
```
source = {
	url = "..."
}
```
but having no knowledge of luarocks, I can't know for sure.

**Comment by alerque** [comment]
Sorry about that, the docs are what is at fault here. You're missing a key argument ;-)

```
$ sudo luarocks install --deps-only sile-dev-1.rockspec
```

**Comment by OlivierNicole** [comment]
It works! Thank you.
