### ISSUE TITLE
Provide nested enumerations and bullets

### ISSUE THREAD

**Issue by the42** [sile-typesetter/sile#1106]
Apparently one can get far without enumerations and bullets.

Bullets are frequently used in text, maybe overused. They might lead to bad type setting style. Nonetheless the lack of proper support of bullets and enumerations leads to imperfections as can be seen in the Sile manual, section 4.1 the possible arguments to `\font`.

I hope this ticket gets accepted as tracking ticket to make Sile eventually feature-rich to fulfill casual type setting needs - for your definition of casual.

## Enumerations

Support enumerations. In first iteration arabic consecutive numerals only with the option to set the starter manually and to specify an enumeration stop symbol (usually a dot as in `1.` - 1 is the enumeration, the dot is a visual helper ) Provide a mechanism to input longer batches of text without breaking out of the enumeration environment.

In a later iteration support non-arabic enumerations like letters, roman numbers, chinese, and
to style the enumeration  eg. by defining the color, font weight, etc.

## Bullets / Itemization

Support bullets and itemization, Provide an option to specify, besides defaults, the unicode rune to use as the item symbol.

In a later iteration provide the means to style bullets by changing color, font weight, distance to text, ...

## Nesting of bullets and enumerations
Provide a means to nest Enumerations and bullets.

In the case of enumerations, a sub-enumeration is usually indented and uses a new enumeration domain, eg. letters

1. Text here
  a. Sub-item level

A nested bullet list often reduces the weight of the used bullet eg. switching from a solid circle an nesting level 0 to an unfilled circled on nesting level 1. 

Also provide the means to nest enumerations and bullets.

**Comment by Omikhleia** [comment]
Nearly a one-year old issue ^^

Hacked the quick'n dirty way during lunch pause

![image](https://user-images.githubusercontent.com/18075640/140319080-ce0f67d3-b134-4a2a-a73c-aa74c191323b.png)

Some of the above requirements could be questioned
- Bullet:
  -  "Provide an option to specify, besides defaults, the unicode rune to use as the item symbol." - Er. Why. Or rather why not defining your _styles_ for all levels, and use them consistently without micro-management?
- Enumerations:
  -  "the option to set the starter manually": Use case?
  - "input longer batches of text without breaking out of the enumeration environment": Quite vague.

**Comment by the42** [comment]
Any eta to try that out? Looks good for a quick shot and a welcomed feature

**Comment by Omikhleia** [comment]
> Any eta to try that out? Looks good for a quick shot and a welcomed feature

As for trying and giving it a quick shot, these lists are in [my repo](https://github.com/Omikhleia/omikhleia-sile-packages) - grab the "enumitem" and "styles" package, and read the PDF documentation (§1.1.9) in the "docs" folder.

As for a true ETA... The "styles" stuff is still in infancy, and the "enumiten" implementation, as said, is a quickly done thing, I'll likely heavily rewrite all the internals at some point... But it sort of works basically and is used in the above-mentioned documentation.  Any feedback is welcome, though. I just needed the bullet list initially, so I have done it quick ("coded with bare feet" as I use to say) and there's likely some room for improvements, if they are reasonable.

**Comment by the42** [comment]
Wow, this looks impressive and promising, actually a better showcase than the sile repo itself.

**Comment by Omikhleia** [comment]
Most of the points are addressed in a way or another
- SILE now has lightweight enumerations and bullet lists (via #1365)
- More complex things that that can be addressed via [3rd party packages](https://luarocks.org/m/sile) e.g. my own "resilient.sile" collection has such a thing, but of course package designers could do it differently.

Unless we want to add more feature(-creep?) to SILE's lists, maybe we can close this issue?
