### ISSUE TITLE
Link to mailing list broken

### ISSUE THREAD

**Issue by clintonblackmore** [sile-typesetter/sile#1107]
At the bottom of the main readme for the github repository, it says there is a mailing list and links to https://groups.google.com/d/forum/sile-users . When I follow that link, my browser says, "Content unavailable."

Conceivably the mailing list still exists at the URL but you have to get on the list before you see it, or, possibly, the list is no more. In either case, a note in the readme would be welcome.

**Comment by alerque** [comment]
The list does still exist, but this isn't the first time we've had trouble with Google's URL schemes for Groups.

Can you try [this link](https://groups.google.com/g/sile-users)? The current link in the README and in your issue report works for me, but it now forwards to that address. It's possible their forward only works for logged in users or some nonsense like that. If that link works for you I'll update the README to match.

**Comment by alerque** [comment]
See also #717 for the same issue (still unresolved because *I* don't have access) for the Japanese list.

**Comment by clintonblackmore** [comment]
I'm afraid the alternate link also doesn't work. I get the same result:

![image](https://user-images.githubusercontent.com/64144/100104535-8d0b6780-2e23-11eb-9787-a2a95191e70b.png)

**Comment by alerque** [comment]
I'm rather puzzled by this. I don't have any ownership on the group so @simoncozens is going to have to fiddle with the settings. That being said it *looks* like the settings are already what they should be:

![image](https://user-images.githubusercontent.com/173595/100106143-39c40400-2e79-11eb-8d0f-e38760124fa2.png)

I just tried in private browsing mode (i.e. no active Google login) and I can confirm none of the 3 link formats I have work, I get the same message Clinton is showing.

Confusingly browsing around on other group links works fine from the same unauthenticated browsing window, so there is a way to do this somehow.

**Comment by alerque** [comment]
Actually the permissions do seem wrong, the "Can see group" permisssion should be "anyone on the web". Simon this is you...

**Comment by clintonblackmore** [comment]
Here's a workaround until the permissions are fixed.

1. To subscribe to the group, send an e-mail (it doesn't even need a subject) to `sile-users+subscribe@googlegroups.com`
2. You'll receive an e-mail asking you to confirm. It will include a link (which won't work); reply to the message (you don't need to actually write anything) and you'll be confirmed.
3. Finally, you'll get a welcome e-mail, and the link to the group will work!

**Comment by alerque** [comment]
I get the distinct impression Google Groups has been on the back burner for some time and will likely be sunset by Google at some point (following a long tradition of useful but undeveloped projects being shut down). I'm wondering if we shouldn't start the process of migrating to the current hotness, [GitHub Discussions](https://github.com/github/docs/discussions).

**Comment by ctrlcctrlv** [comment]
It's on the back burner but I'd like to challenge the idea it'll be shut down. I thought that five years ago and Groups hasn't changed much since. 

I think they keep it around because it's essentially pure profit. They host tons of old discussions they can run ads next to. It's a deep historical archive. And some of Google's own development happens on Groups. 

Watch it close a week after I write this 😂

**Comment by OlivierNicole** [comment]
Contrary to you @clintonblackmore, the link in the welcome email contained the usual URL https://groups.google.com/group/sile-users, which does not work for me. Maybe you have to have certain cookies, e.g. being logged in with a Google account, or to subscribe with a Gmail address.

**Comment by Omikhleia** [comment]
The link to the Google Group is still in the README after more than one year and is still not working.

**Comment by alerque** [comment]
@simoncozens I still don't have owner privs on this, so you need to do it. This setting here is wrong and needs to be changed to "anyone on the web" otherwise Google does not allow browsing the group archives:

![image](https://user-images.githubusercontent.com/173595/160125207-90b0d270-c2a0-4c84-bb10-1692cb4901e4.png)

**Comment by simoncozens** [comment]
Fixed!

**Comment by simoncozens** [comment]
(I've also made you an Owner)
