### ISSUE TITLE
`sile --version` error: "Please install a bit library"

### ISSUE THREAD

**Issue by carlocab** [sile-typesetter/sile#1115]
I'm working on updating Homebrew's lua package to lua5.4.1: https://github.com/Homebrew/homebrew-core/pull/65993

Homebrew CI runs a battery of tests, which includes running a test for each package that depends on lua. (This, of course, includes sile.)

The test for sile calls `sile --version`. Despite the successful build against lua5.4, running this causes the following error:
```
❯ sile --version
/usr/local/opt/lua/bin/lua: ...llar/sile/0.10.13_1/share/sile/lua-libraries/bitshim.lua:50: Please install a bit library
stack traceback:
        [C]: in function 'error'
        ...llar/sile/0.10.13_1/share/sile/lua-libraries/bitshim.lua:50: in main chunk
        [C]: in function 'require'
        ...ocal/Cellar/sile/0.10.13_1/share/sile/core/utilities.lua:1: in main chunk
        [C]: in function 'require'
        /usr/local/Cellar/sile/0.10.13_1/share/sile/core/sile.lua:33: in main chunk
        [C]: in function 'require'
        /usr/local/Cellar/sile/0.10.13_1/libexec/bin/sile:36: in main chunk
        [C]: in ?
```

I'd appreciate some help fixing this, as this is the last test failure that needs to be addressed for Homebrew lua to be upgraded.

 Additionally, suggestions for more substantive tests of functionality would be appreciated.

Thank you!

**Comment by alerque** [comment]
Is Homebrew's Lua 5.4 compiled with or without the Lua 5.2 compatibility flag on or off? The 5.3 build had it enabled which gave it a bit32 module built into the VM. If you've compiled 5.4 without that flag, you need to add a resource bundle to the SILE forumla to get a bit32 module to shim it. SILE was already update to adapt (see #957), but you do need the latest library for it to count. Previous versions of the bit32 library were not aware of Lua 5.4 and would refuse to load on it. 5.3.5.1-1 was released specifically to address this issue. See also [this mess](https://github.com/keplerproject/lua-compat-5.3/issues/48)

**Comment by carlocab** [comment]
The compatibility flag is off. I'll add it, as who knows what else it breaks. Thanks for the tip; it would've taken ages for me to figure it out (if I ever would have).

Do you mind keeping this issue open till I get CI to succeed with sile? I'd hate to spam your issue tracker with other related issues, should any come up. (Hopefully not)

**Comment by alerque** [comment]
No worries. I hope this saves you some of the deep goose chases I spent who knows how many hours chasing this and other gremlins down when 5.4 hit Arch Linux and everything went haywire.

**Comment by carlocab** [comment]
Didn't work. 😞 

I tried grepping the lua5.4.1 source and there doesn't seem to be any reference to `LUA_COMPAT_5_2` in it. It does invoke a macro based on `LUA_COMPAT_5_3`, though, in `luaconf.h`.

Have I misunderstood what I'm supposed to do?

**Comment by alerque** [comment]
I would suggest leaving Lua compiled with default options, adding a resource block to the SILE formula that installs the `bit32` shim module, and making sure LuaRocks is the freshest release possible.

**Comment by carlocab** [comment]
I've left sile on 5.3 for now. Will try to fix it in a separate PR. The CI results should be good enough for the PR to be merged, I think.

Thanks so much for your help; I really needed it. You've been very generous with your time.

**Comment by alerque** [comment]
@carlocab Thanks for your work on HomeBrew. I just took a stab at updating the SILE Formula for 5.4, but since I'm not even on macOS it's a total stab in the dark. [Here is my PR](https://github.com/Homebrew/homebrew-core/pull/66142), you also have access to that remote if you see anything to poke.

**Comment by carlocab** [comment]
Oh,thanks very much. I'll have a look at it this afternoon.
