### ISSUE TITLE
Trace output can have invalid UTF-8

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1120]
The new (upcoming 0.3.0) CLI for CaSILE uses a wrapper to execute SILE and captures the output (both STDOUT and STDERR) on a line by line basis. The text processing library in Rust is complaining (very loudly in the form of a panic) that the input isn't valid UTF-8. Otherwise the SILE run seems to execute properly.

It's possible this is an issue with either the project (because source content snippets get echoed in the trace) or even a CaSILE issue with something leaking a sequence into the shell wrapper output, but for now I'm inclined to blame SILE.

**Comment by alerque** [comment]
It might be the `-d versions` output that is doing this, there is something weird going on with the font version string output. I don't notice anything in a regular terminal, but on piping the output through something that doesn't support all terminal escapes it's clear something weird is going on. For example launched as a shell job from inside vim:

![image](https://user-images.githubusercontent.com/173595/105626004-4b586680-5e3e-11eb-8a8f-3dd7037660d1.png)

**Comment by simoncozens** [comment]
That looks like we're pulling UTF32 out of the name table and not converting it. I'll take a look.

**Comment by alerque** [comment]
The font version data output is *a* problem, but the extra characters stuffed in there seem to be nulls. Those sections at least are valid UTF8 (even if they are rubbish for other reasons). The invalid UTF8 is specifically in the small strings of source document content returned by the `-t` function as positioning info. Something is wrong with the string slice operation.

**Comment by simoncozens** [comment]
There are nulls in the middle of the string because the OT spec specifies that Microsoft-platform name strings should have UTF16-BE encoding, and that’s what a UTF16 string looks like if you don’t decode it properly. The PR converts these strings to UTF8.

**Comment by alerque** [comment]
Thanks for the UTF16 fix @simoncozens.

The rest of this issue comes down to the fact that Lua strings aren't UTF8 safe to slice:

```console
lua -e 'print(("zihnindeki düşünceye"):sub(1,13))' | isutf8
(standard input): line 1, char 12, byte 12: After a first byte between C2 and DF, expecting a 2nd byte between 80 and BF
```

The problem line is here:

https://github.com/sile-typesetter/sile/blob/master/core/tracestack.lua#L80

**Comment by alerque** [comment]
I'm tired of reinventing UTF8 string manipulation one function at a time. Unless there are loud protests soon I'm going to start using the UTF8 safe functions built into Lua 5.3 and add [luautf8](https://github.com/starwing/luautf8) as a dependency to shim Lua <= 5.3.

**Comment by simoncozens** [comment]
Agree, this is getting silly. It also dawns on me that we're now requiring ICU, so could wrap some of its UTF conversion routines.
