### ISSUE TITLE
Make color font support more obvious

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1142]
It isn't obvious that SILE supports color fonts. If you load a font with COLR/CPAL table, that could be output as color, SILE should try to help you more than [making you ask Simon on Twitter](https://twitter.com/simoncozens/status/1360937214608293894) and being directed to `packages/color-fonts.lua` :-)

**Comment by alerque** [comment]
Agreed. This is something we should be able to detect and load the necessary support package automatically just by specifying the font. It just needs doing.

**Comment by simoncozens** [comment]
This and #936 are actually very similar: when a font is loaded, see what it can do, and respond appropriately.
