### ISSUE TITLE
Default language string functions not loaded

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1157]
The language setting defaults to English if no language is specified, but some specialty functions (mostly just wrappers that output localized strings) don't actually get defined unless *something* explicitly sets the language.

MWE:

```sile
\begin[class=book]{document}
% \language[main=en] % Uncomment to fix error
% \font[language=en] % Uncomment to fix error
\tableofcontents
\end{document}
```

This might be a good time to get back on #665.

**Comment by Omikhleia** [comment]
Why not get rid of those "localized strings" wholly?

I mean, currently (0.11), if I have a ``\chapter` in English, it will display "Chapter N". But in many other languages, one just get the "N" alone... Or if I use a `\tableofcontents`, in English I'll get "Table of Contents". But the above isn't true for many languages (e.g. table of contents, AFAIK, is only defined for "en", "tr", "cs"). And what if one just wants to "Contents"? or "Topics" or whatever? One has to redefine things... Which is cumbersome. Doh, keep it simple, do not try to mirror LaTeX's babel package (and the mess it is with localized strings that one _mostly_ always redefine to get what they want), just let the author use some `\chapter[numbering=false, toc=false]{Contents}` or whatever he wants as section heading... IMHO the rest (i.e internationalized string) is uttermost clutter, event if the software gets "potential" translations for any supported language... The `\tableofxxx` (items, figures, etc.) should only do one asks it for: display that table. Titles etc. should not (again IMHO) be part of it.

**Comment by alerque** [comment]
The localized strings will move to Fluent language files as soon as I can get around to finishing the work. This will make it easier and more intuitive to provide localizations rather that overriding a bunch of Lua functions. See #665 and the work I started in #675. I'm actually using this in some projects, I really should finish it up for contribution.

My initial idea was also that SILE‌ shouldn't have any strings hard coded, but my early attempts to do that convinced me that wasn't even what I wanted, much less what others expected. Every word processor and typesetting system I could find does this on some level (some more than others). Even basic things like the title for the table of contents are not strings most people expect to have to pass themselves (even if we setup a system where they could).

**Comment by alerque** [comment]
I think the discussion above about localization *systems* is irrelevant. Since this issue was opened the localization system has been completely replaced with Fluent and the "bug" if it is one is still present.

I think this boils down to this: **we are not being clear about what our defaults are**. We have some places in the code that assume `en` is the default if not otherwise explicitly set (e.g. `decoument.language`) and other places we assume `und` if not otherwise specified (e.g. base class, ICU functions, etc.)

We need to do one or the other, but not mix and match.

So which is it? Is `\document{foo}` expected to output a string in English or undefined?

**Comment by alerque** [comment]
@sile-typesetter/sile-maintainers I'm a bit torn on how to answer this question myself. I've come up with arguments for both direction already and am not even sure where I land. Half the users are likely to expect *some* language as a default and English is the obvious choice for that, but I'm of at least half a mind to default to undefined and throw warnings if people don't set a value. This will impact not only localized strings but things like hyphenation, font features, etc.

**Comment by alerque** [comment]
This *may* break some people's documents either way we do it since they may be making assumptions about either the document language being set to English already or some other features set to undefined. Either way we set the defaults a few things might break, so targeting v0.15.0.

At this point I'm leaning towards setting "en" as the default for the setting (as it is now) and normalizing all the other things to read that setting instead of "und" if unset.

**Comment by Omikhleia** [comment]
> At this point I'm leaning towards setting "en" as the default for the setting

It certainly better IMHO too to have a language rather than none ("und" cannot have any good localization; it cannot have hyphenation patterns, etc. -- and it's hard to explain).

Humorous note addressed to @ctrlcctrlv :
_Of course,_ SILE could set itself apart by being culturally agnostic, choosing a neutral language as a default... namely: Esperanto
