### ISSUE TITLE
Can't start a document with a \skip

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1164]
```
[fred@laptop tmp]$ export SILEFILE=one && sile $SILEFILE.sil && convert -density 400 $SILEFILE.pdf -background white -alpha remove $SILEFILE.png
SILE v0.10.15.r22-g72548c8-dirty (Lua 5.4)
<one.sil>
[1] 
convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `one.png' @ warning/png.c/MagickPNGWarningHandler/1748.
[fred@laptop tmp]$ export SILEFILE=two && sile $SILEFILE.sil && convert -density 400 $SILEFILE.pdf -background white -alpha remove $SILEFILE.png
SILE v0.10.15.r22-g72548c8-dirty (Lua 5.4)
<two.sil>
[1] 
convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `two.png' @ warning/png.c/MagickPNGWarningHandler/1748.
```

# one.sil
```tex
\begin[papersize=4cm x 4cm]{document}
\nofolios
\neverindent
\glue[width=1pt]
\skip[height=3em]
one
\end{document}
```

# two.sil
```tex
\begin[papersize=4cm x 4cm]{document}
\nofolios
\neverindent
\skip[height=3em]
two
\end{document}
```

# diff
```diff
diff --git a/one.sil b/two.sil
index 7da5d7d..dd4a774 100644
--- a/one.sil
+++ b/two.sil
@@ -1,7 +1,6 @@
 \begin[papersize=4cm x 4cm]{document}
 \nofolios
 \neverindent
-\glue[width=1pt]
 \skip[height=3em]
-one
+two
 \end{document}
```

![one](https://user-images.githubusercontent.com/838783/112878436-efa49680-9095-11eb-8e5c-f83bdf6739a5.png)
![two](https://user-images.githubusercontent.com/838783/112878432-efa49680-9095-11eb-873e-2738bda39a75.png)

**Comment by alerque** [comment]
True. I'm not sure this is a bug though. Perhaps it needs more documentation, but it's quite useful to have the typesetter "eat" a skip if it appears at the top of the page. This keeps weird artifacts from appearing when skips cause page breaks (which is quite common).

It might be useful to have an optional parameter for adding required skips, or perhaps another command altogether.

Note the standard way of dealing with this is to add an empty `\hbox` before the skip if you know you need to output it at the top of a frame.

**Comment by ctrlcctrlv** [comment]
Why would that be useful? If the user wrote `\skip`, why would they want it eaten?

**Comment by simoncozens** [comment]
Because they don’t know in advance where the page break is going to be. I think this is true of TeX as well. If you want to keep a top-of-page skip, add an empty hbox.

**Comment by alerque** [comment]
I tried disabling this a long time ago and the number of cases where you *don't* want the typesetter to be able to discard this far outweighed by the times you do. Think for example of a divider command:

```lua
SILE.registerCommand("SceneBreak", function(_, _)
    local skip_props = { height = "4em" }
	SILE.call("skip", skip_props )
	SILE.call("center", {}, { "* * * * *" })
	SILE.call("skip", skip_props)
end

SILE.registerCommand("Section", function(_, content
	SILE.call("skip", { height = "4em" })
	SILE.call("font:section", {}, content)
	SILE.call("par")
end
```

Now imagine some `\SceneBreak`s scattered through a long piece of prose. As the author you would have no way of knowing where on the page they are going to fall. Some might fall at the middle of pages, but many are going to end up at the end. So what should happen when the whole 8em + line in the middle don't fit at the end of a page? Should 4em and the stars be output at the end of a page, then 4em more space at the top of the next page? No, in book typesetting you **almost never** want vertical space at the top of a page. The main exceptions are very specifically crafted pages like chapter headings. Requiring something extra (an `\hbox`) to handle those cases is far more in line with expectations that the alternative.

Section headers are another possible example. If they appear after other content on a page you often want some leading space before them, but if they happen to be at the top of a page you never do.

Of course these examples are simplified to leave out the issue of penalties, but where you allow breaks and where you don't has very little affect on vertical whitespace handling.

**Comment by ctrlcctrlv** [comment]
Oh OK, I get it. Thanks for the explanation.
