### ISSUE TITLE
How do I horizontally squish content?

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1178]
Let's say I want to take a letter and make it 0.5 of its width—how?

I'd find this useful for Ruby. It's often done in Japan.

**Comment by ctrlcctrlv** [comment]
Here's an illustration.

# What I have
![image](https://user-images.githubusercontent.com/838783/122754869-2d165b80-d262-11eb-9822-2feff9bf372e.png)

# What I want
![image](https://user-images.githubusercontent.com/838783/122754919-3acbe100-d262-11eb-8029-6a86c4530f3c.png)

**Comment by simoncozens** [comment]
I don't think there's a way of doing this easily. You would have to manually set a PDF transformation matrix for the text. The pdf module might help with this.

**Comment by alerque** [comment]
I don't think we have something like this. Yet. We should.

We have `\rebox` which can be used to forcefully change the overall size of an output box, but it doesn't change the contents, just the edges of the bounding box.

We also have a tracking adjustment that can e used to squish text together (and thus offend typ designer sensibilities), but that doesn't change the proportions of glyphs.

The only workaround I can think of right now would be a two stage thing where you generated a PDF graphic and used an image editor to squash it, then embed the resultant PDF as an image back in another document. Obviously not a very satisfactory process even if the result comes out.

**Comment by ctrlcctrlv** [comment]
@alerque I'm getting somewhere.

![image](https://user-images.githubusercontent.com/838783/123058812-2ceb9c80-d3d7-11eb-9f99-855beb9723b2.png)
![i need fire](https://user-images.githubusercontent.com/838783/123058761-21987100-d3d7-11eb-8c9d-31ccad648d07.png)

**Comment by ctrlcctrlv** [comment]
It doesn't work how you're saying. It works how @simoncozens said.

Here's raw PDF syntax for one of the squished Ruby lines:

```postscript
q 1 0 0 1 406.8 94.4 cm .6667 0 0 1 0 0 cm 1 0 0 1 -406.8 -94.4 cm BT /F2 6 Tf 406.8 -94.4 Td[<05e205dd05ca>]TJ ET Q BT /F1 12 
```

I don't know what SILE's story is with output to other formats, but this'll only work for PDF and PostScript.

**Comment by Omikhleia** [comment]
@ctrlcctrlv If I understand correctly the initial question, you wanted to "re-scale" some content by some ratio. As @simoncozens suggested, using a PDF transformation matrix is a possible solution, though it would currently only work with the libtexpdf backend.

If this is indeed the question, then I actually did it [there](https://github.com/Omikhleia/textsubsuper.sile/blob/5878dff1c1dd8eb039d2664950cba3cc1f556a7a/packages/textsubsuper/init.lua#L261) for scaling sub/super scripts to some horizontal and vertical ratios - It would be possible to extract that bit of code e.g. in a separate more general package: probably, too, an external package rather than in the core distribution? Then I can help with it if need be, let me know. But ideally, in the end, we should be able to close this issue, it's all doable.

**Comment by ctrlcctrlv** [comment]
@Omikhleia Please do. I really have wanted to fix SILE's 縦書き for a long time, and fixing `ruby` package is a big part of that, and this is a requirement for proper Ruby (and 縦 in general).

**Comment by ctrlcctrlv** [comment]
To be honest we cannot support CJK even horizontal without this feature.

I figured that out while working on my paper called [【洋風 及び 和風】キャップ・トリップそして、それらの種類・歴史・算出方式・算法　一覧](https://github.com/ctrlcctrlv/torippu.pdf/) for which I required pLaTeX, because so many CJK norms just aren't possible in SILE.

Consider the word NPO法人 (hōjin).

![image](https://user-images.githubusercontent.com/838783/188275575-e9eb6202-d637-4e97-aff4-d72fa88196bb.png)

Even writing this horizontally, in a well-made (i.e. professionally typeset) grid-based book, you will squish the NPO.

**Comment by ctrlcctrlv** [comment]
I mean sure my Japanese language documents are a bit strange, they have to be as they're about esoteric internet topics lol

![image](https://user-images.githubusercontent.com/838783/188275654-837ad139-9a93-4be3-9920-fae087e9137d.png)

**Comment by Omikhleia** [comment]
Hmm, but **ruby** is a standard SILE-distributed package. Should the extracted code be proposed as a 3rd party package ("scalebox" or whatever) or be submitted as a PR? Or just baked into the **ruby** package? Did you have that meta-discussion on what is expected as PR and what is not? 'Cause I am not sure where I am heading, these days^^ (sincerely said).

**Comment by ctrlcctrlv** [comment]
I will open one with my initial thoughts now that I've had some time to think of it.

Basically I think `\scalebox` is a core feature because it is required to write a major world language, and all features needed for that are per se core features that should be packaged with SILE.

**Comment by Omikhleia** [comment]
Go ahead, feel free to pick code/ideas from the code I linked above, and don't hesitate to ping me. If you make it such as I could remove it from textsubsuper.sile and used a then standard scalebox, it will be cleaner.

**Comment by alerque** [comment]
I agree, at least the low level functionality here should be provided in core for any packages to use in normal or creative ways.
