### ISSUE TITLE
Variable font support

### ISSUE THREAD

**Issue by simoncozens** [sile-typesetter/sile#1182]
Lack of variable font support is a problem. We know *why* there's a lack: putting variable fonts into a PDF requires instantiation, which we don't currently have the tools to do. The Harfbuzz subsetter isn't quite there yet. But: I have recently discovered that Skia is able to produce PDF files with text from variable fonts. We need to do at least one and probably all of the following:

* Check upstream libtexpdf and see if they have variable font support there yet or not.
* Work out how Skia does its instantiation/PDF generation.
* If it's easy to implement, maybe implement it and contribute upstream.
* If not, consider writing a Skia outputter backend.

There *are* [Skia Lua bindings](https://chromium.googlesource.com/skia/+/chrome/m49/site/user/special/lua.md) but never prepackaged and they look tricky to build and doubly tricky to do so in a portable way. So while writing the Skia outputter itself would be fairly straightforward, getting the bindings buildable would not be.

**Comment by simoncozens** [comment]
OK, so I found out a few things:

* I found out how Skia does it. They just instantiate the glyf table using the gvar table and a location. In theory, not difficult, but...
* Adding this to libtexpdf is possible, but it would be a nightmare, because libtexpdf does all the table parsing by hand and the gvar table is a real pain to implement. (I know, I've done it once.)
* I'm kinda working on a variable font instantiate in Rust. That might actually be our best bet.

**Comment by alerque** [comment]
Great! Keep the Rust library as a separate project and version it properly, but we can definitely make use of that. Unrelated and not a requirement to make use of your idea since we can call into a Rust library from Lua and/or C, but I've also been thinking about swapping out a few bits of the SILE core with Rust—in such a way that the user could still use Lua replacements to override anything they want but just to crank some speed out of the slower iteration points.

**Comment by simoncozens** [comment]
I have also been thinking this way, especially with regard to the line breaking engine.

**Comment by ctrlcctrlv** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

The Modular Font Editor K Foundation, Inc. has selected this issue as requiring particular attention.

It offers a bounty of $3,000 for a PR merger which closes this bug.

If you see this before it appears on foundation.mfek.org, do not worry, it takes some time for that website to update.
-----BEGIN PGP SIGNATURE-----

iHUEAREIAB0WIQSY8o92dHASn747BUziFU3Rocd7iwUCYmHi8QAKCRDiFU3Rocd7
iz5vAQCioZIASHiOpcMmkkaELPWetGtOsCA2pzFIG2sD8FqH4gD7B1WSHBgbLhRw
xm/XoiiNpdB8+orFGqsCTFbk1PYvxhg=
=qE+Q
-----END PGP SIGNATURE-----
```

```
pub   dsa3072 2022-04-21 [SC]
      98F28F767470129FBE3B054CE2154DD1A1C77B8B
uid                      Modular Font Editor K Foundation, Inc. (Grants department) <grants@mfek.org>
sub   elg3072 2022-04-21 [E]
```

> This is felt to be necessary for proofing and therefore within scope.

(SILE could even be considered "part of MFEK" if it supported UFO font loading, lol)

**Comment by ctrlcctrlv** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

The Modular Font Editor K Foundation, Inc. has selected this issue (sile-typesetter/sile#1182) as requiring particular attention.

It offers a bounty of $3,000 for a PR merger which closes this bug.

If you see this before it appears on foundation.mfek.org, do not worry, it takes some time for that website to update.
-----BEGIN PGP SIGNATURE-----

iHUEAREIAB0WIQSY8o92dHASn747BUziFU3Rocd7iwUCYmHrlwAKCRDiFU3Rocd7
iwqSAQCpLqZBmxSCdQz/M9UQMr7C4/27VHnEHyGxzth8m1Dw8AD/WAcUiu2ex/EA
JoeHZyzbwmWInHreQ9EYU9MBU2GOs0o=
=qWAD
-----END PGP SIGNATURE-----
```

```
pub   dsa3072 2022-04-21 [SC]
      98F28F767470129FBE3B054CE2154DD1A1C77B8B
uid                      Modular Font Editor K Foundation, Inc. (Grants department)
sub   elg3072 2022-04-21 [E]
```

> This is felt to be necessary for proofing and therefore within scope.

(SILE could even be considered "part of MFEK" if it supported UFO font loading, lol)

**Comment by ctrlcctrlv** [comment]
(Sorry for double post, I deleted original as it had too broad a statement and didn't refer to the issue…)

**Comment by ctrlcctrlv** [comment]
```gpg
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

The Modular Font Editor K Foundation, Inc. has decided to raise its bounty on 
this issue (sile-typesetter/sile#1182) to $5,000.

This change is effective immediately; please note that all other terms remain 
the same. The bounty was raised due to the long period elapsed without progress.
-----BEGIN PGP SIGNATURE-----

iHUEAREIAB0WIQSY8o92dHASn747BUziFU3Rocd7iwUCYruEHgAKCRDiFU3Rocd7
i8KlAQCN23DsGLpj/ml7ikk/61ummSwXEYyb+MZv8L+Gy35CkQD/dWpOEnBITTIB
ErqIQt1iwseOCFgY1zbljevVrFRcpB4=
=41QE
-----END PGP SIGNATURE-----
```

**Comment by davelab6** [comment]
@ctrlcctrlv any updates on this?

**Comment by simoncozens** [comment]
I think with hb-subset in place we should be able to do this now.

**Comment by ctrlcctrlv** [comment]
> @ctrlcctrlv any updates on this?

MFEK's grant remains active and if no one takes it this year then it will roll over into next year. However, I am loathe to increase the price unless someone can give a good reason for me to do that, so far no one has even attempted to sketch what the code might look like so if I can't judge how much work will go into it I don't see a reason to increase the price.

**Comment by khaledhosny** [comment]
The PDF Type 3 fonts is what Skia is doing, BTW, and what I did for LibreOffice (the upcoming 7.5 release)

**Comment by ctrlcctrlv** [comment]
Hey Khaled, thanks a lot for the information. I looked it up in the Document Foundation's revision control and found it:

https://git.libreoffice.org/core/+/164d717530aff8d2581d0a2ff249f83aabb27502%5E%21

If you have a moment I have a question about the patch. It seems like HarfBuzz is capable of giving us back shapes that are already interpolated according to the axes. That is to say you're not using Masters and then using the Type 3 font format to interpolate those Masters. So I'm actually wondering why you need the Type 3 font format for this. Isn't it correct to say that you could just roll over a new Type 1 PS font every 255 variable font characters?

Or am I missing something?

**Comment by alerque** [comment]
@ctrlcctrlv I think you've done *more than enough* to bait the hook! The offer is more than generous. We need some combination of other tech to catch up and somebody to sit down and chew on this. I started a couple times and keep getting sidetracked by other little stuff that needs refactoring, but might take another swing soon.

**Comment by ctrlcctrlv** [comment]
Good to hear, and obviously I don't care if the eventual patch uses Type 3 fonts or not, and won't be an issue vis a vis payment to whomever, I just don't understand why they're needed. Obviously every PDF reader that is well written must support Type 3 fonts because they are part of the official specification no matter how few documents may use them.

**Comment by khaledhosny** [comment]
> Hey Khaled, thanks a lot for the information. I looked it up in the Document Foundation's revision control and found it:
> 
> https://git.libreoffice.org/core/+/164d717530aff8d2581d0a2ff249f83aabb27502%5E%21
> 
> If you have a moment I have a question about the patch. It seems like HarfBuzz is capable of giving us back shapes that are already interpolated according to the axes. That is to say you're not using Masters and then using the Type 3 font format to interpolate those Masters.

Yes, the hb-draw will apply variations to the outlines.

> So I'm actually wondering why you need the Type 3 font format for this. Isn't it correct to say that you could just roll over a new Type 1 PS font every 255 variable font characters?

PDF Type 3 fonts (not to be confused with PS Type 3 fonts), are not standalone fons, they live entirely inside the PDF file and use PDF code for drawing glyphs. I’m already using them for color fonts (both outlines and bitmaps), so it was less work and I didn't want to learn how to create Type 1 fonts from scratch. The only downside to Type 3 fonts is the lack of hinting, but hb-draw is not giving me hinting anyway.

It might be good idea to use PDF Type 3 fonts for color fonts support in SILE as well, it should give smaller file size and better text extraction than the current approach of drawing directly to the PDF stream.

**Comment by khaledhosny** [comment]
I looked into libtexpdf, and I don’t think my Type3 idea is going to work here. Turns out, libtextpdf does not subset the fonts and uses Type0 composite fonts (with CIDFontType0 or CIDFontType2 depending on the kind of outlines) and since these can use more than 256 glyphs (unlike the other PDF font subtypes, including Type3), it would be hard to fit Type3 idea into this workflow.

**Comment by ctrlcctrlv** [comment]
> hb-subset does not yet support CFF2 fonts, is this a show breaker?

I somehow missed this question.

No, not for me.

CFF2 is really not the most useful varfonts format, and isn't the original one, which was TrueType GX back when varfonts were called MM fonts.

Also I think that @behdad said he was going to somehow get a revision to the `glyf` table to allow for cubic splines? This would make CFF2 even more useless.

But MFEK's Foundation can sponsor adding CFF2 to the HB subsetter if people are interested in that. I see it as somewhat useful as most of us do design our fonts in cubics but given nearly 1:1 quadratic conversion is possible it rarely ever matters in practice.

Also aren't the TT GX-style varfonts physically smaller on disk?

Either way I'm writing this to remind @alerque or whoever merges to make a new issue whenever this is closed called "Add CFF2 variable fonts support". :-)

**Comment by khaledhosny** [comment]
I couldn’t care less about CFF2 myself, the only CFF2 font one is likely to ever come across in the wild is Cantarell, otherwise CFF2 support is is bug in certain popular operating system and everyone seems to be shipping glyf/gvar fonts.

**Comment by ctrlcctrlv** [comment]
Indeed, and even in the case of Cantarell you can convert it pretty easily. I do a CFF2→glyf conversion in FRBAC. I wonder if it might not make sense to point people to `fontmake` in the error message Khaled?

I just tried to do a conversion and it went fine. I wonder what @davelab6 thinks of just not distributing the CFF2 version?

I've never built this font before and it was easy. Just:

```bash
git clone https://gitlab.gnome.org/GNOME/cantarell-fonts
cd src
fontmake -m Cantarell.designspace -o variable --verbose DEBUG
```

![image](https://user-images.githubusercontent.com/838783/209588248-e4865610-06cb-4bcd-b6fe-554be9df456d.png)
![image](https://user-images.githubusercontent.com/838783/209588227-53f44185-ef51-42f7-8565-9b52059bac6c.png)

[Cantarell.zip](https://github.com/sile-typesetter/sile/files/10304997/Cantarell.zip)

It might be because they've optimized their PS hints that they are using a CFF2 font but they really should transition to TT hints anyway, and for SILE obviously hints are barely a concern. :)

**Comment by khaledhosny** [comment]
> not distributing the CFF2 version?

Cantarell is maintained by @madig, and if I were to guess it is probably because he likes FreeType’s CFF rendering more.

**Comment by ctrlcctrlv** [comment]
<sub>(Oh, right, sorry, I keep forgetting Dave gave up maintainership of Cantarell.)</sub>

I get that. Luckily it doesn't have to be an eitiher/or. I'll have to ask over on the GNOME tracker about the feasibility of distributing a GX-flavored varfont as well as the CFF2-flavored one. Cantarell's a small font filesize wise so it wouldn't increase the size of the distribution much at all.

Perhaps it could be `ttfautohint`'d…or if I ever get off my ass and finish hacking up VTT, manually VTT-hinted.

It'd be good to at least have an official option for it as it's such a popular font.

Thanks a lot again for stepping up to the plate and working on patching this @khaledhosny. To be honest, I didn't think anyone ever would! I owe you $5,350:money_with_wings:! :-)

**Comment by madig** [comment]
> because he likes FreeType’s CFF rendering more.

Yep. The only reason I care about CFF2, and I recently upgraded to a 4K screen. So, who knows :)

**Comment by ctrlcctrlv** [comment]
@madig Since you're here would you mind distributing a `glyf`-flavored VF of Cantarell?

**Comment by madig** [comment]
Eh, I could... maybe the next time I do something on it.
