### ISSUE TITLE
Footnote rule and custom mark

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1217]
- Footnote rule between the main content and the footnotes.

  Just to be clear, I mean the highlighted rule in this example from a book made with LibreOffice:

  ![image](https://user-images.githubusercontent.com/18075640/132958774-896b6468-a94e-4872-a8de-c030887e4b6a.png)
 
  Is this something SILE's footnote package could/should have? If so, I have no idea (yet) on how to implement it, though - has there been any attempt already?
  
- Custom footnote mark, not incrementing the counter, for use cases such as the one presented below:
 
  ![image](https://user-images.githubusercontent.com/18075640/132958865-63b860fb-3821-4c49-a769-2271af81b8c8.png)
 
  Here, it's SILE in action, with just a few redefinitions ;)

  Is this something that SILE's footnote package should have in its standard version? (If so, I could clean up my quick attempt and propose it, but the code is very basic).

**Comment by alerque** [comment]
Nice looking work!

The separator is already something SILE can do. For example here is the default provided by CaSILE:

```lua
SILE.call("footnote:separator", {}, function ()
  SILE.call("rebox", { width = "6em", height = "2ex" }, function ()
    SILE.call("hrule", { width = "5em", height = "0.2pt" })
  end)
  SILE.call("medskip")
end)
```

And in action:

![image](https://user-images.githubusercontent.com/173595/132959608-6e7609e4-c7f0-44eb-b77a-8087871cbb3c.png)


The custom marker might be something that would make a nice addition to the examples gallery on the website (which will be a lot easier to contribute to shortly).

**Comment by Omikhleia** [comment]
Great kudos @alerque, as of the footnote rule, it worked as a charm:

![image](https://user-images.githubusercontent.com/18075640/132983872-33a17063-d044-4eb0-bcff-26239203520d.png)

I'll clean up my code and make PR's for consideration whether it should become part of the standard package or not. It comes along the lines of:
- A helper command such as `\footnote:rule[width, beforeskipamount, afterskipamount` (all params being optional with defaults), just a convenience wrapper for the above mentioned `\footnote:separator`. IMHO it would be a handy addition (and a nice use of the rebox functionality !).
-  Supporting `\footnote[mark=...]` for custom marks. I'll consider this one separately, it's a bit more controversial maybe, and I'll review the use cases I know.

**Comment by Omikhleia** [comment]
Thanks, I am considering this as answered.

> I'll clean up my code and make PR's for consideration whether it should become part of the standard package or not.

Actually, I am not using the footnotes package any longer, so the point is moot.
