### ISSUE TITLE
dropcaps (or floats) and footnotes do not behave very well

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1218]
Greetings,

SILE 0.10.15 on Ubuntu 20.04

I tried to add a dropcaps to the initial (text) paragraph of a document. _Caveat emptor:_ My attempt at getting dropcaps might be wrong. SILE does a pretty good job without it.

Dropcaps and footnotes do not seem to behave very well. It might depend on how the dropcaps is made (so my definition follows, at the end of this ticket)

I tried to add a dropcaps to the initial (text) paragraph of a document.

- Pretty nice formatting without dropcaps :+1: - SILE does a good job that far: 
 
  ![image](https://user-images.githubusercontent.com/18075640/132963097-2c5aa166-af96-4cfb-a2bf-aa83493613b1.png)

  Well, nearly perfect - but to tell the truth, on p. 4 the notes get really close to the text (but that's not the main point here):

   ![image](https://user-images.githubusercontent.com/18075640/132963425-e7636722-229d-412a-b62d-84da3f771860.png)

- Any how, when the dropcaps is used on the first text paragraph :-1: 

   ![image](https://user-images.githubusercontent.com/18075640/132963139-6e45c151-fd3d-4c00-83c9-5dfad77fb7ec.png)

   - On page 1, lots of overlaps between the text and the footnotes. For a closer view:

     ![image](https://user-images.githubusercontent.com/18075640/132963233-1f183600-5aca-407b-82c1-0885dd26af9f.png)
 
   - The layoyut of subsequent pages  seems affected too (huge vertical spaces, etc.)

Of course, maybe I did somethings wrong. The definition I tried for obtaining the dropcaps is `lettrine{E}some more text` where:

```
\define[command=lettrine]{\noindent\float[bottomboundary=1bs]{\font[size=3bs, family=Linux Biolinum Keyboard O]{\process}}\noindent{}}
```

(lFWIW, "lettrine" = dropcaps, in French ;)

**Comment by alerque** [comment]
I've already spent half my week trying to fix this. I have an alternate float implementation better suited to dropcaps in the works, but it still has some cases that don't work.

Everything I see here is iterations of the bugs noted in #394, #420, #474, #491 and #1185. Somewhat amazingly I think you've managed to trigger every one of those separate but related issues in one example.

I'm closing this as a duplicate, but I do feel your pain.

I have successfully published a couple books combining footnote insertion frames with dropcaps, but it has been touch and go to find metrics that worked.

**Comment by alerque** [comment]
> SILE 0.10.15 on Ubuntu 20.04

By the way I'm kind of curious why you are on an old version still. The Ubuntu PPA should have you up to v0.11.1 already.

**Comment by Omikhleia** [comment]
Switched to 0.11 only after I was done sorting out my local changes ^^

Oh, by the way, regarding dropcaps working well with footnotes, I think I am slowly getting somewhere...

![image](https://user-images.githubusercontent.com/18075640/133010654-e9a012d6-1310-484a-8371-e3a00daaf84a.png)

That, **without using float / frames at all**, hehe (*)... The code is messy as hell, works only for LTR writing, might be hard to generalize - it's sort of a trick, but heh, it looks so nice. ^^ ;)..

It even shows something that I long wanted to have but that did not prove possible (AFAIK) in MS-Word or LibreOffice: the possibility for the dropcaps not to just be a "square" box, when the letter belongs to the first word on the first line. I mean, this effect:

![image](https://user-images.githubusercontent.com/18075640/133011876-4c30b722-ee65-47c8-a5de-e4c43ae05505.png)

As found e.g. in some books (image taken from Wikipedia):

![image](https://user-images.githubusercontent.com/18075640/133012585-176b6ecc-5b83-443b-9048-5f5b9d292893.png)

It's sort of hack too, not sure I can make it general without depending too much on _ad hoc_ tuning depending on the font, but it's real cool :smile_cat: 

(*) _Without using floats_: so what's the trick? Basically implementing (at least partially) hangindent/hangafter from Knuth's linebreak algorithm, and then a bunch of hacky-whacky re-boxings to insert the caps in the space left for it.

**Comment by alerque** [comment]
Wow, my float based dropcap implementation I was working on last week does the same hanging indentation. I'll definitely review that PR and compare notes.
