### ISSUE TITLE
URL and line breaks

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1229]
Nowadays, it's a common practice to have URLs in print article (whether it is a _good_ practice or not is another topic).

The **url** package says it will 
> automatically insert breakpoints into unwieldy URLs, 

.... but it actually breaks only after `/` by default.

I think it could be made more powerful and I would suggest:
- Removing the `breakpat` option on `\href` and `\url`: 
  - As currently implemented, it could be any regular expression, which makes the urlFilter some some sort of badly named 
    generic filter
  - It's hard to use in SIL language (not even tried to check we could escape `[` and `]` in command options!)
  - Some breaks should be before, some after (see below)
- Implementing breakpoints at approriate places:
  - After:
    -  `:`, `/`, `.`, `;` (URL path elements)
    -  `?`, `&`, `=` (URL query parts)
    -  `_`, `-` (goodies that feel safe breaking at, e.g. https://en.wikipedia.org/wiki/Alan_Turing, https://github.com/sile-typesetter/sile#what-is-sile)
    - maybe `!` (IIRC the `#!` is/was used by Twitter, Facebook etc. I am not on these social networks, but heh why not)
  - Before:
    -  `%` (URL escape sequence)
    -  `#` (URL fragment)
    - I am not an expert at penalties, but maybe some of the above "After" elements could be breaks before, with a lower (higher?) penalty. I guess i'll need to read more about penalties.
      I mean, _in the worst case_, a line break before them could be acceptable.
- Temporarilly switching language to 'und'
  - To avoid hyphens being inserted.
    (While bits of an URL can be actual words, in most international URLs several languages can be mixed, and
    for latin-script languages, accents are not used, so it can become quite messy anyway)
  - To avoid language-specific formatting: currently that might affect French only, but one doesn't want the typography rules
    (space before `:`, `?` etc.)
  - If this change is felt too drastic,
    - Either do it for French only...
    - Or allow an option `language` to be set (and one author could take the decision to override 'und' 
      with  `SILE.setCommandDefaults` if he really wants hyphenation rules to apply...)

I will be doing this (at least some parts) for my own needs, so I you feel this could become part of the default **url** package,
assign the issue to me and I'll propose a PR at some point :D

**Comment by simoncozens** [comment]
I like this a lot! I don't think it's just a French language issue, so please do it for everything. :-)

**Comment by alerque** [comment]
Sounds good to me too.

**Comment by alerque** [comment]
Resolved by #1233.
