### ISSUE TITLE
Graphite fonts (including default Gentium Plus) cause memory leak

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1236]
SILE 0.11.x

I made an attempt at processing a "decently large" XML document (around 1.7Mb) with SILE, most tags being (via the `xmltricks` package ignored _for now,_ or passthru until a few text nodes are reached.

One issue is the performances (EDIT: memory consumption) - I know my computer was already somewhat loaded, and will try again after a fresh reboot, but this is still interesting: 

![image](https://user-images.githubusercontent.com/18075640/133890330-e960b1c9-0c84-416f-921d-f9e745cac52d.png)

(I killed it after 22 pages - On my previous experiment l let it kick into the swap and had high times trying to stop it at 31 pages. I expect the document to have around 60 pages (in default papersize) with most tags ignored, and around 100 pages if complete with all tags)

~~Another issue is one of the first tag not to be ignored was not processed as expected:~~ (removed, my mistake)

=> No real question so far, I am still experimenting, but is they any output (debug options?) that could be interesting to observe and report along the way?

**Comment by ctrlcctrlv** [comment]
I'd like to see a comparison to the results running SILE under LuaJIT.

**Comment by ctrlcctrlv** [comment]
(Also it's funny how similar this is to an issue I was thinking of opening about a Japanese internet slang dictionary I wanted to write and use the XML feature to build with SILE, and if I needed to know anything.)

**Comment by alerque** [comment]
I routinely work with some 900+ page monstrosities and haven't seen a memory consumption issue like this. I'm wondering if this is a leak in the XML parsing library more than it is a SILE thing. I do find LuaJIT a lot friendlier to bring down the render time, but either way I haven't gotten into a deadlock situation like your resource history is showing.

It would be useful to have a synthetic MWE to compare, say a short script where we can generate a long document pro grammatically in both XML and SIL dialects to compare.

**Comment by ctrlcctrlv** [comment]
900 pages in SILE is brave :laughing:

**Comment by Omikhleia** [comment]
- My bad, the "other issue" was my mistake, fixed it.
- Starting on a fresh boot, I could process all the document (ended up to be ~80 pages), with a much simplified preamble. Memory consumption got fairly high too (and even kicked slightly into the swap, but that was less dramatic).
- I'll try to convert the XML to SIL and see how it behaves.

**Comment by Omikhleia** [comment]
Might have got upon something...

When I add in my preamble:
````
\font[family=Libertinus Serif, size=10pt]
```
The memory consumption is fairly decent and rises only at a small pace. All goes well to the end of the document.

When I remove it (as I was initially - so I am back to the default font) -, the memory consumption shows that dreadful pattern as illustrated above.

**Comment by Omikhleia** [comment]
First run (the small bump), second run (the huge bump):

![image](https://user-images.githubusercontent.com/18075640/134087474-dcdbd719-af97-4b94-abf5-078359923110.png)

```
$ /usr/bin/time -v sile -I preamble-libertinus.sil dict-sd-subset.xml 
SILE v0.11.1 (Lua 5.2)
Loading preamble-libertinus.sil
<preamble-libertinus.sil>
<dict-sd-subset.xml>
[1] [2] [3] [4] [5] [6] [7] [8] [9] 
	Command being timed: "sile -I preamble-libertinus.sil dict-sd-subset.xml"
	User time (seconds): 11.68
	System time (seconds): 0.20
	Percent of CPU this job got: 97%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:12.21
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 388472
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 96126
	Voluntary context switches: 1
	Involuntary context switches: 1790
	Swaps: 0
	File system inputs: 0
	File system outputs: 112
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
$ /usr/bin/time -v sile -I preamble-gentium.sil dict-sd-subset.xml 
SILE v0.11.1 (Lua 5.2)
Loading preamble-gentium.sil
<preamble-gentium.sil>
<dict-sd-subset.xml>
[1] [2] [3] [4] [5] [6] [7] [8] [9] 
	Command being timed: "sile -I preamble-gentium.sil dict-sd-subset.xml"
	User time (seconds): 14.39
	System time (seconds): 0.96
	Percent of CPU this job got: 97%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:15.78
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 2628656
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 656434
	Voluntary context switches: 1
	Involuntary context switches: 2270
	Swaps: 0
	File system inputs: 0
	File system outputs: 120
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
$ diff preamble-gentium.sil preamble-libertinus.sil 
6c6
< \font[family=Gentium Plus]
---
> \font[family=Libertinus Serif]
```
**Test files attached:** [xml.zip](https://github.com/sile-typesetter/sile/files/7199105/xml.zip)

The XML file is a dictionary, so very repetitive in structure.

_N.B. Since I removed most of the legalese tags for testing purpose; I suppose I have to say something such as "The included sample XML lexicon subset is licensed under CC-BY-NC-SA 2.0 with additional limitations of scope. It is provided to the SILE development team for testing purpose, and does not cover other derived used."_

Surprising indeed:
> Maximum resident set size (kbytes): 2628656

Compare to the first run:
>  Maximum resident set size (kbytes): 388472

In case the matter:

- The font comes from
  ```  
  $ dpkg-query --search /usr/share/fonts/truetype/gentiumplus/
   fonts-sil-gentiumplus: /usr/share/fonts/truetype/gentiumplus
  ```
- That fonts-sil-gentiumplus package was installed by SILE
  ```
  $ apt-cache depends sile
  sile
    Depends: libc6
    ...
    Depends: fonts-sil-gentiumplus
  ```
- The font is the v5 
  ```
  $ otfinfo -v /usr/share/fonts/truetype/gentiumplus/GentiumPlus-R.ttf
  Version 5.000
  ```

**Comment by simoncozens** [comment]
OK, definitely confirmed here! The Libertinus run allocates 158M max on the heap, the Gentium one allocates 306Mb.

But if I make a "no Graphite" version of Gentium Plus, stripping out the Silf/Sill/Silt/Glat/Gloc tables, SILE barely allocates anything at all until writing out the PDF at the end!

So I am going to blame this on Harfbuzz's Graphite implementation.

**Comment by simoncozens** [comment]
It's a leak in our `justenoughharfbuzz` code. I think I've found it. *Bad* programmer.
