### ISSUE TITLE
pdf:link does not allow line breaks

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1239]
SILE 0.11.1

Links made with pdf:link cannot span over multiple lines.

**Comment by alerque** [comment]
This might need some tricky work to fix. We will need some sort of pseudo hbox mechanism that groups the nodes inside it but doesn't do anything else to the layout, then *after* line breaking we need to process it and find the contiguous chunks of it and find their bounding box.

**Comment by Omikhleia** [comment]
See discussion https://github.com/sile-typesetter/sile/discussions/1292 for a possible way...
