### ISSUE TITLE
Detecting font features for fallback?

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1258]
This is kind of an enhancement suggestion, but also a request for advice on how to best address this idea: could SILE provide a way to detect available font features, so one could either use them or implement a fallback?

I have this case where I'd like to use the superscript characters in a font, when available, instead of raising and scaling a character, because most of the time they'll obviously look better. That could for a number (e.g. in footnote calls), but also for letters (e.g. in century references in French, "IVe" with superscript e, or like with in sequences in English, 12th with superscript th).

Of course, one can check prior-hand if a font has the necessary features and adapt one's own code. E.g. for now, I have a very simple command:

```
SILE.registerCommand("style:superscript", function (options, content)
  if SU.boolean(options.native, true) then
    SILE.call("font", { features="+sups" }, content)
  else
    SILE.call("raise", { height = "0.77ex" }, function ()
      SILE.call("font", { size = "1.414ex" }, content)
    end)
  end
end, "Typeset in superscript.")
```

And I just use `SILE.setCommandDefaults` to set it to native or not, depending on the font I decided to use for a given text. On the other hand, I would find it nicer to be automatically detected.

I guess such a thing could rely on the shaper (harfbuzz's `hb_ot_layout_collect_features` probably) or more likely on the recent opentype parser. Obviously, the initial question may actually have two sides: (1) is a font feature supported? (2) but also: are the characters supported for that feature? (that might be harder).
 
Understandably, there are not many font features, probably, where this could be worth having. Besides `sups`, probably `subs` or `sinf` (for subscripts), and `smcp` (for a scaled fallback for smallcaps). So I understand this "convenient" feature might not be that needed. 

Moreover, some fonts. such as the default (Gentium Plus) do not have the sups/subs feature but do include however some of the [Unicode](https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts) super/subscript characters... So the whole idea of doing it via font feature detection might not be as general as I thought... And perhaps the whole point is moot?

**Comment by simoncozens** [comment]
One way I’ve found useful to detect whether a feature exists and does something is simply to shape the same text twice, with the feature on and with it off. If the results are different, your feature did something…

**Comment by alerque** [comment]
Small caveat, doesn't that assume you are also shaping a think that would be affected by the specific feature? I.e. you can't test shape "test" for a feature that only possible affects the letter "i", right? In other words this might work for a case by case basis for a specific context, but it won't give a general purpose answer.

**Comment by alerque** [comment]
(@Omikhleia Off topic but you should check your notifications on GitHub / Email for an invite to join the SILE org on GitHub. No expectation on our part of contributing anything more than you have time and interest in anyway, but it will give you access to a few more GitHub features.)

**Comment by Omikhleia** [comment]
Just tested @simoncozens 's clever trick. Nice idea! My quick implementation so far, just for sharing -
```
local textFeatCache = {}

local _key = function (options, text)
  return table.concat({
      text,
      options.family,
      ("%d"):format(options.weight),
      options.style,
      options.variant,
      options.features,
      options.filename,
    }, ";")
end

local textFeatCaching = function (options, text, status)
  local key = _key(options, text)
  if textFeatCache[key] == nil then
    textFeatCache[key] = status
  end
  return status
end

local checkFontFeatures = function (features, content)
  local text = SU.contentToString(content)
  if tonumber(text) ~= nil then
    -- Avoid caching any sequence of digits. Plus, we want
    -- consistency here.
    text="0123456789"
  end
  local fontOptions = SILE.font.loadDefaults({ features = features })
  local supported = textFeatCache[_key(fontOptions, text)] 
  if supported ~= nil then
    return supported
  end

  local items1 = SILE.shaper:shapeToken(text, fontOptions)
  local items2 = SILE.shaper:shapeToken(text, SILE.font.loadDefaults({}))

  -- Don't mix up characters supporting the features with those
  -- not supporting them, as it would be ugly in most cases.
  if #items1 ~= #items2 then
    return textFeatCaching(fontOptions, text, false)
  end
  for i = 1, #items1 do
    if items1[i].width ~= items2[i].width or items1[i].height ~= items2[i].height then
      return textFeatCaching(fontOptions, text, true)
    end
  end
  return textFeatCaching(fontOptions, text, false)
end

local scriptSubOffset = "0.33ex"
local scriptSupOffset = "0.77ex"
local scriptSize = "1.414ex"

SILE.registerCommand("style:superscript", function (options, content)
  if type(content) ~= "table" then SU.error("Expected a table content in style:superscript") end
  if checkFontFeatures("+sups", content) then
    SILE.call("font", { features="+sups" }, content)
  else
    SILE.call("raise", { height = scriptSupOffset }, function ()
      SILE.call("font", { size = scriptSize }, content)
    end)
  end
end, "Typeset in superscript.")
```

@alerque Bothered by the 2FA requirement - I couldn't install a 2FA application on my phone yet (which is getting too old apparently), and I was not fond of providing my phone number to GitHub for SMS... Will make another attempt after the WE, I lacked time to better check the options.

**Comment by alerque** [comment]
> I couldn't install a 2FA application on my phone yet (which is getting too old apparently), and I was not fond of providing my phone number to GitHub for SMS

@Omikhleia I understand both the old phone limitation and not wanting to give GitHub your number. There are lots more options though for 2FA. Besides using a hardware key, you can also use a authenticator app on your computer. [KeepassXC](https://github.com/keepassxreboot/keepassxc) for example has TOTP support built in or there are CLI apps like [cotp](https://github.com/replydev/cotp).

**Comment by Omikhleia** [comment]
Thanks for the answer.
