### ISSUE TITLE
OpenType FeatureVariations have no effect

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1265]
This is a bit different than #1182, because this doesn't require instancing or anything—we should still be applying the OT FeatureVariations even without that.

I tried this patch to get SILE to start setting the opsz OT FeatureVariation for use in FRB American Cursive v2, but it doesn't work:
```diff
diff --git a/src/justenoughharfbuzz.c b/src/justenoughharfbuzz.c
index 5ac8d61b..fd559247 100644
--- a/src/justenoughharfbuzz.c
+++ b/src/justenoughharfbuzz.c
@@ -178,6 +178,11 @@ int shape (lua_State *L) {
     hb_face_t* hbFace = hb_face_create (blob, font_index);
     hbFont = hb_font_create (hbFace);
     unsigned int upem = hb_face_get_upem(hbFace);
+    hb_variation_t hbVar;
+    hbVar.value = point_size;
+    hbVar.tag = HB_TAG('o', 'p', 's', 'z');
+    printf("hbVar.value : %g\n", hbVar.value);
+    hb_font_set_variations(hbFont, &hbVar, 1);
     hb_font_set_scale(hbFont, upem, upem);
 
     if (can_use_ot_funcs(hbFace)) {

```

Even though my code there matches what's used in the Harfbuzz tests, I don't get my numbers like I expect:

**Chrome (OK)**
![image](https://user-images.githubusercontent.com/838783/139399773-3b3ba4ec-2e10-45af-b8e5-8a5dd78e7894.png)

**SILE (broken)**
![image](https://user-images.githubusercontent.com/838783/139399920-9ee55988-c784-4f6e-b305-4fe7b4e95159.png)

**Comment by ctrlcctrlv** [comment]
I give up on this one, but the solution has to be simple. It's just eluding me, and I have no more time to look. But I really need this fixed for proofing purposes.

So…you know what's coming…drum roll please…(lol) :drum: :drum: 


**The Modular Font Editor K Foundation, Inc. has selected this issue (sile-typesetter/sile#1265) as requiring particular attention.**

It offers a bounty of **$350** for _either_ a PR merger which closes this bug _or_ a patch which fixes the issue described in the original post. @ctrlcctrlv will shepherd the PR if you don't want to commit to that.

If you see this before it appears on foundation.mfek.org, do not worry, it takes some time for that website to update.
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

VGhlIE1vZHVsYXIgRm9udCBFZGl0b3IgSyBGb3VuZGF0aW9uLCBJbmMuIGhhcyBzZWxlY3RlZCB0
aGlzIGlzc3VlIChzaWxlLXR5cGVzZXR0ZXIvc2lsZSMxMjY1KSBhcyByZXF1aXJpbmcgcGFydGlj
dWxhciBhdHRlbnRpb24uCgpJdCBvZmZlcnMgYSBib3VudHkgb2YgJDM1MCBmb3IgX2VpdGhlcl8g
YSBQUiBtZXJnZXIgd2hpY2ggY2xvc2VzIHRoaXMgYnVnIF9vcl8gYSBwYXRjaCB3aGljaCBmaXhl
cyB0aGUgaXNzdWUgZGVzY3JpYmVkIGluIHRoZSBvcmlnaW5hbCBwb3N0LiBAY3RybGNjdHJsdiB3
aWxsIHNoZXBoZXJkIHRoZSBQUiBpZiB5b3UgZG9uJ3Qgd2FudCB0byBjb21taXQgdG8gdGhhdC4K
CklmIHlvdSBzZWUgdGhpcyBiZWZvcmUgaXQgYXBwZWFycyBvbiBmb3VuZGF0aW9uLm1mZWsub3Jn
LCBkbyBub3Qgd29ycnksIGl0IHRha2VzIHNvbWUgdGltZSBmb3IgdGhhdCB3ZWJzaXRlIHRvIHVw
ZGF0ZS4K
-----BEGIN PGP SIGNATURE-----

iHUEAREIAB0WIQSY8o92dHASn747BUziFU3Rocd7iwUCYmaHEwAKCRDiFU3Rocd7
i0aCAP4z1dwuyeWyOIYl0WQcDk7E5Jk/GO9yWUd48K7vvj3eeAD/VKUfpghh4MDN
23x7FRn88VpVYbSJmqgsm9EhsXBfT98=
=/FLR
-----END PGP SIGNATURE-----
```

Rationale: Required for VF proofing.

**Comment by alerque** [comment]
I *might* be able to tackle this soon. I'm 100% blocked on landing the class model overhaul right now. As soon as that works I'll look at this as a warm-up to possibly digging into variable font support.

**Comment by khaledhosny** [comment]
#662 fixes the underlying issue, I didn’t include the `opsz` axis bit as it probably deserves an issue of its own (or may be part of general font variations support). But with #1662 and this patch:
```diff
diff --git a/src/justenoughharfbuzz.c b/src/justenoughharfbuzz.c
index b8debb3d..4f49d0f7 100644
--- a/src/justenoughharfbuzz.c
+++ b/src/justenoughharfbuzz.c
@@ -178,6 +178,9 @@ int shape (lua_State *L) {
     unsigned int upem = hb_face_get_upem(hbFace);
     hb_font_set_scale(hbFont, upem, upem);

+    hb_variation_t opsz = { HB_TAG('o', 'p', 's', 'z'), point_size };
+    hb_font_set_variations(hbFont, &opsz, 1);
+
     if (can_use_ot_funcs(hbFace)) {
       hb_ot_font_set_funcs(hbFont);
     } else {
@@ -297,6 +300,9 @@ int get_glyph_dimensions(lua_State *L) {
   unsigned int upem = hb_face_get_upem(hbFace);
   hb_font_set_scale(hbFont, upem, upem);

+  hb_variation_t opsz = { HB_TAG('o', 'p', 's', 'z'), point_size };
+  hb_font_set_variations(hbFont, &opsz, 1);
+
   if (can_use_ot_funcs(hbFace)) {
     hb_ot_font_set_funcs(hbFont);
   } else {
```

SILE output now is:
<img width="777" alt="image" src="https://user-images.githubusercontent.com/93914/208312622-e5abeacf-dada-4be7-ba32-fe3794f05ac1.png">
