### ISSUE TITLE
nofoliothispage vs. nofoliosthispage

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1266]
SILE 0.12, package "folios":

Package documentation has `\nofoliothispage`. Actual code implements `\nofoliosthispage`.

We should either fix the package documentation or (the singular being likely what was wanted) deprecate the current command and implement the correct naming.

**Comment by alerque** [comment]
I agree, the documentation makes more sense than the code. This will need a deprecation shim for sure though, and I won't be in a hurry to pull the trigger and remove the shim. We can warn for a long time, but this is in a *lot* of code out there and supporting the shim shouldn't be too messy.
