### ISSUE TITLE
Justified headings within ragged* environments

### ISSUE THREAD

**Issue by biggnome** [sile-typesetter/sile#1268]
On pages terminating within a raggedright or -left environment, the headers incorrectly render with full justification. (This behavior seems somewhat intermittent, but mostly consistent--I couldn't figure out what besides ragged* may affect this.) I've noticed it occasionally in my own documents, but it is also present in the manual--

![badheader](https://user-images.githubusercontent.com/12508219/140200884-88ab159a-6a4b-4656-ab4e-a84ec19207ef.png)

(Incidentally on the subject of the manual, `\section{color-fonts}` in `c05-packages.sil` probably ought to be a subsection instead.)

**Comment by Omikhleia** [comment]
Likely the headers do not reset the settings (as the folios and footnotes do).

**Comment by Omikhleia** [comment]
Yep, adding `SILE.settings.toplevelState()` in `book.endPage`  (twice, i.e. just before the `SILE.settings.set("current.parindent", SILE.nodefactory.glue())` calls for the left and right header) does seem to fix the issue. (And I realize my own book class had it in its custom headers, so I might have experienced it at some point, though I don't remember when I added then)

**Comment by alerque** [comment]
Thanks for reporting this @biggnome.
