### ISSUE TITLE
Incorrect atomType name in unicode-symbols.lua

### ISSUE THREAD

**Issue by arichard4** [sile-typesetter/sile#1274]
```
local atomType = {
  ordinary = 0,
  bigOperator = 1,
  binaryOperator = 2,
  relationalOperator = 3,
  openingSymbol = 4,
  closeSymbol = 5,
  punctuationSymbol = 6,
  inner = 7,
  overSymbol = 8,
  underSymbol = 9,
  accentSymbol = 10,
  radicalSymbol = 11,
  vcenter = 12
}

local mkAtomType = {
  mathopen = atomType.openingSymbol,
  mathclose = atomType.closeSymbol,
  mathord = atomType.ordinary,
  mathfence = atomType.ordinary,
  mathalpha = atomType.ordinary,
  mathbin = atomType.binaryOperator,
  mathaccent = atomType.accentedSymbol,
  mathaccentwide = atomType.accentSymbol,
  mathrel = atomType.relationalOperator,
  mathunder = atomType.underSymbol,
  mathover = atomType.overSymbol,
  mathop = atomType.ordinary,
}
```

"mathaccent = atomType.accentedSymbol," -> accentedSymbol doesn't exist; this should presumably be accentSymbol. But I'm not familiar enough with SILE to know if this would break something.

**Comment by ctrlcctrlv** [comment]
> But I'm not familiar enough with SILE to know if this would break something.

That's what the test suite is for. :-)

**Comment by arichard4** [comment]
Ah, I see, thanks. I'd been having some trouble running it, turns out I needed to install libertinus-font for the test suite to pass. I'll send a CR over shortly.

**Comment by alerque** [comment]
> I'd been having some trouble running it, turns out I needed to install libertinus-font for the test suite to pass.

This should not be the case, I'm curious what went wrong here. The test suite needs *lots* of specific fonts to work, Libertinus being just one of them. However it also has rules for downloading copies of all the fonts it needs and the test runner should be isolated to **only** use those downloaded fonts.

Were you using `make test` to run the test suite?
