### ISSUE TITLE
Indic hyphenation rules

### ISSUE THREAD

**Issue by simoncozens** [sile-typesetter/sile#1275]
Add these: https://github.com/smc/hyphenation

**Comment by Omikhleia** [comment]
All these patterns (as, bn, gu, hi, kn, ml, mr, or, pa, ta, te) are the same as those in the [TeX hyph. repo](https://github.com/hyphenation/tex-hyphen), except three (hi, mr, ta) which have received a small fix each (mostly related to the handling of ZWNJ, in March 2016 for two of them and in 2018 for the other), looking at the commits. But the Changelog wasn't updated and this was not pushed back to the TeX hyph. repo... That should be a question for the author's repository or perhaps the TeX folks...

Anyhow, out of the **11** patterns, we **already** had **10** in SILE, from #31 and #32 in... **2014-2015**. Only Tegulu (**te**) was not imported (for no obvious reason in the above-mentioned PRs). I actually proposed it for addition in #2102

--> We can close/reject this issue.

**Comment by Omikhleia** [comment]
As for the (hi, mr, ta) discrepancy between the smc repo and the TeX repo, I just reported the fact to the former.

**Comment by Omikhleia** [comment]
To be fully complete on the matter (if looking at this ticket in the future), as far as "indic" is concerned, #2102 also adds Pāli (**pi**).
