### ISSUE TITLE
Duplicated content after some reboxing

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1278]
I had a weird "\rebox" issue the other day - sometimes the content got duplicated. In my case, the reboxing was temporary only and in bad code (lol), so I didn't bother much... but I just noticed the issue was in the 0.12 manual too, as can be seen here (from the online version of the 0.12 manual):

![image](https://user-images.githubusercontent.com/18075640/141036874-dd8201dd-69cd-4031-ac97-6e5b7c4671d7.png)

**Comment by alerque** [comment]
I'm absolutely baffled how `\rebox` ever worked correctly. Even using Git history I don't see how it has ever done anything but output duplicate content.
