### ISSUE TITLE
cropmarks package is broken

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1285]
Document:
```
\begin[class=book, papersize=6in x 9in]{document}
\script[src=packages/cropmarks]
%\define[command=crop:header]{crops}
\crop:setup[papersize=a4]

Test page 1

\eject

Test page 2

\end{document}
```

Result = error

```
SILE v0.12.0 (Lua 5.2)
<examples/croptest.sil>
[1] 
Error detected:
	/usr/share/sile/packages/date.lua:7: attempt to index local 'options' (a string value)
```

Removing the comment to override the default crop header = page 1 is wrong.

![image](https://user-images.githubusercontent.com/18075640/141714248-ad8bf52d-870b-41dc-b5ae-4bca84dcbfe2.png)

(Page 2 is ok)

**Comment by alerque** [comment]
Yes. It should probably be replaced with [CaSILE's crop implementation](https://github.com/sile-typesetter/casile/blob/master/packages/crop.lua) which is quite a bit more robust and I use in production.
