### ISSUE TITLE
Hyphenation issue after apostrophe?

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1297]
SILE 0.12

**Observed**
```
grou-pe d’-hommes (French, 0x2019)
grou-pe dʼ-hommes (French, 0x02BC)
grup d’-ho-mes (Catalan, 0x2019)
grup dʼ-ho-mes (Catalan, 0x02BC)
```
I am getting line breaks with an hyphen after the apostrophe (whether using the 0x02BC apostrophe or the 0x2019 quote mark: I thought this could have been my issue initially, with received texts from different software having one or the other, but they behave the same apparently).

![image](https://user-images.githubusercontent.com/18075640/144711369-db3d0004-3d24-4d20-9578-d9b9dee4355d.png)

**Expected** 

It does not seem to me that the hyphenation point is legit. Seems to occur in more than one language (e.g. French and Catalan above).

**Comment by Omikhleia** [comment]
The second commit in the above PR fixes the issue for U+2019... A mere typo in the code ;)

U+2019 "is preferred where the character is to represent a punctuation mark" - so this seems sufficient.

U+02BC "is preferred where the apostrophe is to represent a modifier letter (for example, in transliterations to indicate a glottal stop)" - so is not appropriate anyway.

**Comment by Omikhleia** [comment]
FWIW
- The "quote" category is ambiguous according to the standard, 
- ICU is having issues for languages using it as French, perhaps Italian (and Catalan, they don't mention it), as per e.g. https://unicode-org.atlassian.net/browse/CLDR-6665 and https://unicode-org.atlassian.net/browse/ICU-21854

**Comment by alerque** [comment]
c.f. #355
