### ISSUE TITLE
Normalize indentiation inhibititors

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1300]
As discussed in #1288...

Direct uses of the low level `SILE.typesetter:inhibitLeading()` should be avoided in favor of the higher level `SILE.call("noindent")` unless there is a specific reason to do so. To many direct calls to lower level tooling fragments the code base and makes it harder for projects or libraries to override behavior.

**Comment by Omikhleia** [comment]
I am not quite sure (hence the initial questioning), but `SILE..typesetter:inhibitLeading()` seems to act on _vertical_ spacing and might have been thought to be something else than the _horizontal_ paragraph indentation (`indent`/`noindent`).

**Comment by simoncozens** [comment]
Yeah, leading and indentation are different... (Do we need a high level inhibit-leading command?)

**Comment by Omikhleia** [comment]
Wrong issue then: `SILE.typesetter:inhibitLeading()` != `noindent`

And #1288 received additions in the meantime -- Whether to inhibit leading after sectioning commands is a matter of conventions and user choices, but unrelated to indenting or not the first paragraph/alinea after a section.

--> Rejecting.
