### ISSUE TITLE
The Manual seems to equate leaveHmode() with \par

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1304]
The SILE manual (0.12), §9.1.1
> Line breaking and page breaking happens when the typesetter
moves between horizontal and vertical mode; you can force this to happen by calling the function
SILE.typesetter:leaveHmode(). The SILE-level command for forcing a paragraph end is \par

This wording more or less seems to equate Lua `SILE.typesetter:leaveHmode()` with SILE-language `\par`.

This is not wholly true however, as `\par` also invokes the classe's `endPar()` which does additional things such as inserting a vertical parskip and resetting some settings. This is slightly confusing e.g. when a package developer needs to understand the implication of invoking `SILE.typesetter.leaveHmode()` (as shown in the examples in this chapter) or rather `SILE.call("par")`).

**Comment by alerque** [comment]
I hope those changes clarify it a bit. We can always fine tune.
