### ISSUE TITLE
\bidi-on causes infinite loop

### ISSUE THREAD

**Issue by simoncozens** [sile-typesetter/sile#1330]
If you call `\bidi-on` when bidi is already on, `nobidi_boxUpNodes` now becomes equal to `bidiBoxupNodes`, and when `bidiBoxupNodes` calls `nobidi_boxUpNodes` it ends up calling itself recursively and endlessly.

MWE:

```
\begin[papersize=a5]{document}
\bidi-on

aaaaa
\end{document}
```

**Comment by alerque** [comment]
There are a couple issues with builds (e.g. Docker Hub tagging is borked and the nix flake has dependency issues). I was considering another bump anyway, this look seals the need.

Plan: check to see if bidi is on and throw a warning if it is, then do nothing.
