### ISSUE TITLE
(minor) weird code linting warnings (tate and bibliography packages)

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1333]
SILE 0.12.3

Just noticed these strange lines with my brand new VSCode setup...

![image](https://user-images.githubusercontent.com/18075640/156670141-7f1ba055-9a66-49f2-bfb5-c995e9c31ca1.png)

![image](https://user-images.githubusercontent.com/18075640/156670305-af896879-fd08-4a87-a166-d41ef39714e5.png)

As of yet, I've never used these packages and have no idea what was intended here (i.e. whether it's just mere minor typos or if it could point to a potential hidden bug), but I'm just reporting anyway for code check & quality. (Also, I wonder why this was not caught by the linting CI pipelines.)

(Good side of the story: AFAIK that's the only two lines caught by Tencent's LuaHelper in VSCode)

**Comment by alerque** [comment]
Those both look like legitimate coding errors and should be fixed. That being said I'm also surprised / impressed those are the only two things it turned up!

The first one is likely innocuous. The `k` value will just be initialized to `nil` effectively setting the scope to `local` (a valid thing to do), and it is later set before use anyway. Setting it explicitly will just be to appease the linter.

The second one might be a real bug lurking in there somewhere.
