### ISSUE TITLE
\dotfill doesn't stretch to the end of a single paragraph line

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1343]
SILE 0.12.4

I would have thought `\dotfill` to behave the same way as an `\hfill`, as far as streachability is concerned, but it doesn't:
- When it is on the last line of a paragraph (or below, on its own unique paragraph line), it doesn't stretch to the full width.
- It only does so if `typesetter.parfillskip` is cancelled.

Could be a documentation issue, but I am also concerned it might not be the expected behavior, and it's kind of delicate to always notice and fix.

Test script:
```
\begin[class=book, papersize=a5]{document}
\script[src=packages/leaders]
\script[src=packages/lorem]
\nofolios
\neverindent

|\hfill{}|

|\dotfill{}|

\lorem[words=13]

Kill parfillskip:

\set[parameter=typesetter.parfillskip,value=0pt]

|\hfill{}|

|\dotfill{}|

\lorem[words=15]

\end{document}
```

Results:
![image](https://user-images.githubusercontent.com/18075640/158682726-098b21d4-40c7-40cd-be8e-f29233c30490.png)

**Comment by alerque** [comment]
I agree these should both behave the same way, and negating the `typesetter.parfillskip` makes the most sense from an end user perspective.

Keep in mind that some of us consider `\dotfill` to be completely broken anyway, see #875 for why.

**Comment by Omikhleia** [comment]
> Keep in mind that some of us consider `\dotfill` to be completely broken anyway, see #875 for why.

Yes, looking at the implementation, `\dotfill` and `\leaders` are somewhat broken. The present stretch issue is a low-hanging fruit and can be addressed separately.
