### ISSUE TITLE
Font-relative parindent and line justification issue

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1361]
And after #1358 and #1359, a train can hide yet another again ;) Here is another source of my justification issues.

![image](https://user-images.githubusercontent.com/18075640/163291209-3ee4b6df-d033-44bb-b212-3a564abbbb11.png)

I have this small "block quote" environment that leaves Hmode, sets a smaller font and reduced lskip and rskip margins. As can be noticed, the lines beginning a paragraph within that environment have a small offset.

FWIW, my input code looks as follows.

```
\begin[class=omibook, papersize=6in x 9in]{document}
\language[main=fr]
\set[parameter=linebreak.emergencyStretch, value=15%lw]%

L’auteur de poursuivre :

\begin{blockquote}
C’est une tradition de toute la région, m’avait-on dit, que de tenir,
au mois de février, une fête de l’ours, ou \em{festa de l’ós}. Bien que
ce ne soit pas propre à la Cerdagne, mais aussi au Vallespir &c.

Je ne m’étonnai pas sur le moment de cette étrange comparaison. Notre
discussion dériva bientôt vers d’autres sujets. Lorsque le souvenir m’en
revint ensuite sur la route, je ne pus me retenir de penser que mon
interlocuteur avait en réalité voulu évoquer (...)
\end{blockquote}

Lorem ipsum (...)

\end{document}
```

But nothwithstanding how I implemented it, I think the important things here is that the `document.parindent`  was expected to be font-relative, i.e. it is set to `1.2em` in my class - because smaller text in such quotes ought to have a smaller indent, ideally...

Back to default plain class and a simpler test case, the observed behavior can be simplified as follows:

```
\begin[papersize=6in x 9in]{document}
\script[src=packages/rules]
\script[src=packages/lorem]
\nofolios
\font[size=30pt]
\set[parameter=document.parindent, value=1em]

\noindent{}\hrule[width=1em]% This rule just to show a 1em width at 30pt

\font[size=10pt]{\par
\lorem[words=35]

\lorem[words=35]
\par}

\end{document}
```

![image](https://user-images.githubusercontent.com/18075640/163292310-483b96a2-1226-48bc-afb0-0de5713a85dd.png)

It does seem to mean that one cannot have a font-relative paragraph indent in such environments... Or maybe `newPar` in `core/baseclass.lua` should "absolute()" the pushed glue? It does seem to do the trick for the small test above, but it might also mean SILE is not doing things properly elsewhere (i.e. in the context where this glue is later interpreted).

EDIT:
> but it might also mean SILE is not doing things properly elsewhere (i.e. in the context where this glue is later interpreted).

To clarify my feeling: it might be considering the glue at several places (line-breaking, then output) without applying the same font options.

**Comment by alerque** [comment]
I think you've just dug up a hornets nest. The settings state stack we have isn't being utilized here as much as it should be. The implementation I typically use for situations such as your blockquote command here is to use a temporary settings closure before setting the font size and then anything that is relevant to it. It shouldn't require that extra step to get relevant values to track with current settings though.

**Comment by Omikhleia** [comment]
I am afraid I don't agree with your analysis, if this would imply here explicitly setting the parindent to its own absolute value within a temporary settings closure. It would seem to fix the simplest case, but won't work with nesting (e.g. blockquote in a blockquote).

I actually think the proposed solution above (absolutizing when the parindent is pushed in `newPar()` is very probably the only correct way: _Any glue should be made absolute at the place it is pushed_.

That probably true too for the parskip in `endPar`, which could also be defined as relative (e.g. in `em`)...

A more drastic approach _could_ be to do it in `pushHglue` and `pushVglue` respectively as well as there `pushExplicit...` variantes. It could even cover more corner cases, e.g. `math.displayskip` defaults to "2ex plus 1pt", so what does one expect if in a smaller font environment? Has someone ever tested, say, maths in footnotes?

**Comment by alerque** [comment]
What would you expect in the given (pseudo code) scenario, given I'm using braces to indicate setting closures?

```
{
	\set font size 16pt
	\set left margin 2em
	content ... I expect the left margin here to be 32pt
	{
		\set font size 8pt
		content ... I expect the left margin here to be 16pt
	}
}
```

My expectation is that the relative value setting `2em` would get absolutized at the point where it is used in context, not when I set it. Am I understanding correctly you would expect the left margin in this scenario to evaluate to 32pt in both locations?

**Comment by Omikhleia** [comment]
Looking at the implementation: 
- The lskip and rskip margins enter in another category: they are not even "pushed" as the other above-mentioned glues, but they are inserted directly in the node list at boxing time, via `addrlskip`... So they don't fall in the cases I referred above and they wouldn't be impacted.
- But look there, they are actually converted to number (an even stronger assumption than my mere absolutizing); i.e. evaluated within a given font context: the one active at the moment vertical mode is left, _whatever_ closures you might have used when preparing the content. In other terms, tell me where the vertical mode is exited in your example, and I might guess how they evaluate.

**Comment by Omikhleia** [comment]
Updated my comment.

**Comment by Omikhleia** [comment]
But we actually said the same thing. ME: "Any glue should be made absolute at the place it is pushed." YOU: "the relative value setting would get absolutized at the point where it is used in context".

**Comment by Omikhleia** [comment]
I experimented absolutizing in `pushHglue` and `pushVglue` (and their explicit variants) and in my case it worked well and gave the expected results....

... However, I don't think it is the best solution. For cases where the next frame has a different width, it would imply that the boxed content doesn't contain a relative unit any longer. This might not be what users expect if they used a line/page-relative unit (rather than a fixed or, now, font-relative unit), say some "%lw"...  This would be resolved to the absolute value in the current frame, but if a page breaks later occurs and the content is moved (via pushback) to a frame with a different width, that won't be recomputed.

This being said, lots of commands actually already absolutize their values at the point where they are processed (e.g. "kern" does it width immediately, so within the context of the current frame at this point). So the suggested change would just make it more general. That is, already now, if one has a `\kern[width=50%fw]` in a line, and that line is pushed back to another frame of different width, that would not lead to a 50% width there...

Actually I wonder if the correct solution wouldn't be to use a logic similar to unshaped nodes. When these are pushed, the font options are passed to them (in `typesetter:setpar`), and that is used to compute them with that font selection. Maybe all pushed elements should behave the same way (i.e. be pushed with the current font, and evaluated based on it) rather that be absolutized earlier...

Needless to say, this is indeed a hornets nest. The settings state stack is not the issue, it is rather the fact that some objects will be (re-)evaluated outside a temporary settings closure, and possibly in a different frame after the page building occurs.

**Comment by Omikhleia** [comment]
Partly relates to #262
