### ISSUE TITLE
Questioning SILE's default interword spacing

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1371]
So the default behavior in SILE is to use, for interword spacing:
- `shaper.spaceenlargementfactor` = 1.2
- `shaper.spacestretchfactor` = 1/2
- `shaper.spaceshrinkfactor` = 1/3

The stretch and shrink are somewhat consistent with what TeX and Co do.

Where does the default 1.2 enlargement factor comes from, however? Is there any rationale (read: typography literature) for that value?

**Comment by simoncozens** [comment]
I'll be totally honest - 1 just looked too tight. But 1 is probably the correct default.

**Comment by alerque** [comment]
If we trust font designers to do their thing...

I'm not planing any more patch releases in the v0.12.x series, the next release will be a "breaking" v0.13.0 for other very minor reasons. As of the Fluent stuff I just merged nothing should beak for probably 99% of users, but I'll be marking it as breaking anyway for the couple of unavoidable edge cases. In other words this might be a good time to drop in this clearly massively breaking "fix" if we do decide to fix it.

**Comment by Omikhleia** [comment]
It really depends on the font (e.g. it may look tight with Gentium for instance, but take some old Caslon, say, with large space characters)... We could make it more clever and font dependent (I don't think it is addressed in OpenType, but decision could be based on some guesses between the em size and the relative space size in that font to stay within acceptable ranges for the stretch and shrink, but that probably an overkill - something that the font designers should rather have considered.).

**Comment by alerque** [comment]
Changing this might merit a deprecation warning when *no explicit setting is detected*. In other words anybody who is just using the defaults should probably be warned, documents that ever touch the setting knobs at all can be let go. Thoughts? The same issue is going to apply to other default settings we plan on changing like the default leading algorithm (#1118) and saner parindent (#1722).

**Comment by Omikhleia** [comment]
Likewise 1718 might be breaking for anyone who used boxes at the beginning of a paragraph (e.g. I know my poetry and footnotes will break -- I've already moved forward to implement the fix -- but I suspect my teidict module will break too and I don't plan an immediate fix yet...).

Deprecations and changes in behavior are messy to handle properly. I would assume the release implementing them would document properly the changes in its release notes, but I wouldn't put pressure on implementing warnings and shims etc. in the code. After all, every update takes the risk of breaking things, even unforeseen (e.g. 1707, 1708).
