### ISSUE TITLE
hrule with depth option wrongly affects the current base line

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1382]
SILE 0.12.5

Test script
```
\begin[papersize=a6]{document}
\neverindent
\nofolios
\script[src=packages/rules]

Lorem \hrule[depth=2mm, width=1cm] Ipsum
\end{document}
```
Observed:

![image](https://user-images.githubusercontent.com/18075640/165649681-f7b85f9e-7dc8-413d-86f4-036bb28cc1e8.png)

Expected:

The depth should not have moved the baseline, i.e.

![image](https://user-images.githubusercontent.com/18075640/165650448-d3cbf96c-9ed0-4f0a-a590-6c4535cd40be.png)

Moreover:

- Package documentation states: "The first command is `\hrule` which draws a line of a given length and thickness, although it calls these `width` and `height`. (A box is just a square line.)" 
- The in-code command documentation states `Creates a line of width <width> and height <height>`
- EDIT: package documentation also says "Like images, rules are placed along the baseline of a line of text." This caused me a big LOL ;) (that a mere blob of ink is being compared to an image?)

This is misleading and probably ill-formulated: the command also has a `depth` option... BTW, as far as I can tell, only one existing test uses this depth option, but on a standalone line without surrounding context, so the issue could not be seen there. The box vs. line wording is also weird (the command rather makes a rectangular blob of ink -  It can be used to produce horizontal or vertical lines depending on the dimensions, and the `h` in the name just refers to the fact that is is an horizontal box, no ?)

Personally I don't think the depth option should necessarily be removed. Not only it is in line with what a box actually is, but It can be pretty handy sometimes, e.g.

![image](https://user-images.githubusercontent.com/18075640/165660141-c6c04669-a4db-4c21-93ed-6e991f382d45.png)

(Ok, I could have done this another way without using a rule depth for the longer barcode lines, but heh...)

On the other hand, it all depends whether we want to be be similar to TeX's `\hrule` (which has optional width, height, depth parameters) or to LaTeX's `\rule` (which has width, thickness and raise options, the latter effectively being a depth below baseline if negative). It seems to me the first case is more general...

Anyway, the fix is simple - pick up your choice:
- Remove the depth option...
- Or rather restore the Y cursor after drawing the rule (and update documentation to mention that depth option and rephrase the weird wording).

(EDIT: Fixed the TeX and LaTeX similar command descriptions)

**Comment by Omikhleia** [comment]
> BTW, as far as I can tell, only one existing test uses this depth option, but on a standalone line without surrounding context, so the issue could not be seen there.

This is a very last test in `tests/percent-units.sil` and the issue is actually visible there too:
![image](https://user-images.githubusercontent.com/18075640/165921460-babee85c-e767-4cc8-84e1-6a4ce37c11cc.png)

(= `\hrule[width=50%lw,height=10pt,depth=2pt]#`)

**Comment by alerque** [comment]
I'm all for keeping the option.

By the way your barcode example is an eye opener. Personally I've been using `zint` to generate SVG's and embedding those in SILE docs, but I have it on my todo-list to stop doing that and start using a barcode font instead so they could be copy-pasted from a PDF easier.

**Comment by Omikhleia** [comment]
> By the way your barcode example is an eye opener. Personally I've been using zint to generate SVG's and embedding those in SILE docs, but I have it on my todo-list to stop doing that and start using a barcode font instead so they could be copy-pasted from a PDF easier.

FWIW, my [EAN-13 implementation](https://github.com/Omikhleia/omikhleia-sile-packages/blob/main/packages/barcodes/ean13.lua) (loosely inspired by a TeX package presented in [TUGboat, vol. 15-4, 1994](https://tug.org/TUGboat/Articles/tb15-4/tb45olsa.pdf)) uses rules for the bars, and an OCR B font for the human readable text below them. I didn't want to include an image generated via a 3rd party tool (though `zint` in indeed great) nor a barcode font (to be able to easily select between the standard scales without mistakes, and for no other reason that EAN-13 is easy to code compared to some other barcode schemes... Well I see Speedata has a [QR code](https://github.com/speedata/luaqrcode) implementation in Lua, I might it give it a try if I ever need such a thing ^^)
