### ISSUE TITLE
[opened in error]

### ISSUE THREAD

**Issue by zavislak** [sile-typesetter/sile#1403]
[wrong assumptions; deleted]

**Comment by zavislak** [comment]
Note that one can obtain the desired page breaking behavior by adding an additional zero-height glue:

> \begin{document}
> 
> one
> \skip[height=2in]
> two
> \skip[height=0in]
> \skip[height=8in]
> three
> 
> \end{document}

This will typeset lines 'one' and 'two' on the first page, and 'three' at the top of the next page.

**Comment by zavislak** [comment]
Whoops, ignore.  There's another issue I'll open separately.

**Comment by Omikhleia** [comment]
By the way, `\skip` has a discardable option (false by default. Just in case you didn't know).
