### ISSUE TITLE
Where is the first baseline on a new page (alignment, grid or not)?

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1430]
The first line on a page has a baseline depending on its actual height.

In regular typesetting:
if a page starts with a line with, say, no ascenders or capitals, it will not line up with another page where those would be present.

In grid typestting:
I am not too sure how the grid typesetting is supposed to work, but it seems to be the case here too.

I wonder if this was intended/expected.

(Admittedly, it seldom occurs in normal languages with full sentences...)

**Scenario A**
```
\begin[papersize=a5]{document}
\neverindent
\nofolios
\font[size=50pt]
Some ascenders or capitals here...

\vfill
\break

none ov em
\end{document}
```

**Scenario B** (same but with grid typesetting)

```
\begin[papersize=a5]{document}
\script[src=packages/grid]
\neverindent
\nofolios
\font[size=50pt]
\grid[spacing=60pt]
Some ascenders or capitals here...

\vfill
\break

none ov em
\end{document}
```

**Observed result**

Scenario A:

![image](https://user-images.githubusercontent.com/18075640/173469432-a23a22b0-da4e-456f-95c0-4b177183774c.png)

Scenario B = Likewise in grid typesetting:

![image](https://user-images.githubusercontent.com/18075640/173470109-50369579-a94d-4bf1-bb19-6c51ab1a4483.png)

**Comment by Omikhleia** [comment]
Possibly relates to #1398 (needed for proper grid bible typesetting)

**Comment by alerque** [comment]
I think scenario A is expected, the leading mechanism just uses the height and depth of the current line and jams it at the top of the page, then works down from there. I suppose we could have a mechanism for all/some of the leading types (especially `fixed`) where the first baseline could be specified relative to the frame somehow.

For scenario B that's definitely a bug. The grid needs to start calculations relative to some frame (whether that be `content` or `page` should probably be configurable) and then all pages should use the first available grid line. Initializing the grid spacing after the first line is a terrible order op operations.

**Comment by Omikhleia** [comment]
I do have the feeling the scenario A might be wrong too (but differently - as with "struts", i.e. the _minimum_ baseline should ensure it fits an ascender height of the default font). Still, I could not find any book with a page starting with a line containing not ascenders at all, and did not find an explicit mention in the typography resources I consulted... It's an obscure edge case, likely ;)

**Comment by alerque** [comment]
Minor update with discovery in case I get distracted before finishing: This is not so much an issue with the grid getting initialized incorrectly as it is with some lines not respecting the grid we have.

```sile
\begin[papersize=a5]{document}
\script[src=packages/grid]
\neverindent
\nofolios
\font[size=50pt]
\grid[spacing=60pt]
\grid:debug
Some ascenders or capitals here...

Some ascenders or capitals here...

Some ascenders or capitals here...

Some ascenders or capitals here with a longer \font[size=1.5em]{run of foo bar baz}

\vfill
\break

none ov em
\end{document}
```

![image](https://user-images.githubusercontent.com/173595/206709424-9d55e539-c5f9-4421-a24c-96b427e26b81.png)

**Comment by alerque** [comment]
I thought I had a patch for this, and the PDF was looking great. At least the first 3 pages ... out of 951,561. Garahumph.

**Comment by alerque** [comment]
Okay this bug is probably a one line fix, but reasoning about it is a nightmare because the typesetter stuff is still all cross wired. I started refactoring so the various typesetters are proper subclasses instead of the current monkey patching system (grid, bidi, balancing, etc. all replacing functions piecemeal). I'm at the point where everything works again and all tests except bidi pass, but it still needs a bit of love. Once that's done it should be a lot easier to debug and reason about at least.

**Comment by alerque** [comment]
The "previous vbox" being used to calculate the leading adjustment in this MWE is not a vbox, it is a penalty node. That's the bug.
