### ISSUE TITLE
Release 0.13.0 seems to want lua-zlib 1.2-2

### ISSUE THREAD

**Issue by dontlaugh** [sile-typesetter/sile#1431]
I was building from a zip file downloaded from the releases page. Kept getting this:

```
Installing https://luarocks.org/lua-zlib-1.2-1.rockspec
Cloning into 'lua-zlib'...
fatal: unable to connect to github.com:
github.com[0: 140.82.112.3]: errno=Connection timed out


Error: Failed installing dependency: https://luarocks.org/lua-zlib-1.2-1.rockspec - Failed cloning git repository.
make: *** [Makefile:1195: lua_modules] Error 1
```

I'm not a Lua expert, but perhaps 1.2-1 was yanked? Here is the LuaRocks page https://luarocks.org/modules/brimworks/lua-zlib

Switching to lua-zlib 1.2-2 fixed my build.

**Comment by alerque** [comment]
The difference between -1 and -2 is entirely on the luarocks side, just the rockspec got bumped on luarocks.org. Both rockspec files point to the `v1.2` tag on the project's GitHub repository.

The error you show above is much more basic: `unable to connect to github.com`. Note this shows up during a clone operation before it even tries to switch to a tag – any tag.

I believe you just had a temporary network problem reaching GitHub. I don't see anything else amiss.

In any case -1 or -2 should both be fine. I believe the author of that project put out the -2 to work around the LuaRocks protocol issues, then found he could republish -1 to fix it there too so both rock rels should be working and equivalent. I will bump it in our dependencies anyway, but I don't think anyone will be affected.
