### ISSUE TITLE
Document papersize parameter case sensitivity

### ISSUE THREAD

**Issue by baubleb** [sile-typesetter/sile#1433]
Sometimes it is natural to write the papersize for ISO 216, ISO 217 and ISO 269 in caps (A, B and C series), however the _papersize_ parameter for a document is lowercase (defined in _core/papersize.lua_). See https://github.com/sile-typesetter/sile/blob/5e95ff4fb93ae675c0812cb6286957e89c4b9e51/core/papersize.lua#L13 and 
https://github.com/sile-typesetter/sile/blob/5e95ff4fb93ae675c0812cb6286957e89c4b9e51/core/papersize.lua#L59

Given this document input
```
\begin[papersize=A0]{document}
\end{document}
```
Gives the output
```
$ sile test.sil 
SILE v0.12.5 (Lua 5.2)
<test.sil>

! Unknown paper size A0 at test.sil: in <file> (\)

```

**Comment by Omikhleia** [comment]
All the non-ISO papersize names could also be questioned... (ideally with reference to their standard, when they have one, e.g. ANSI, JIS, etc.)

**Comment by alerque** [comment]
Octavo. What size *is* it anyway?

On a more serious note, would it be fair to just make this field case insensitive? Many of our other values that do not run the risk of clashes are already, e.g. `style=italic` and `style=Italic` both work.

**Comment by alerque** [comment]
So is case insensitivity fine with folks for papersize?

**Comment by Omikhleia** [comment]
Does "LeTteR" makes sense then? ;)

**Comment by alerque** [comment]
Does it make sense? No. But technologically if we are going to accept both "letter" and "Letter" then unless we provide a large map of allowed casings the only sane way to handle it is just cast the user input to lowercase, which would make "lEtTEr" valid input even if it's insane.

**Comment by Omikhleia** [comment]
From their names and values,  our "archE", "archD", "archC", "archB", "archA" are probably the "North American ARCH Series"   for large drawings and architecture plans. Whether we should accept spaces and all caps here is an interesting question ("ARCH A", "Arch A" are both seen, AFAIK). Or a dash? (Arch-A, etc.)

Interestingly, we do not have the Arch E1, E2 and E3:

(mm, in, pt)
Arch E: 914 x 1219, 36 x 48, 2592 x 3456
Arch E1: 7620 x 1067, 30 x 42, 2160 x 3024
Arch E3: 686 x 991, 27 x 39, 1944 x 2808
Arch E2: 660 x 965, 26 x 38, 1872 x 2736
Arch D: 610 x 914, 24 x 36, 1728 x 2592
Arch C: 457 x 610, 18 x 24, 1296 x 1728
Arch B: 305 x 457, 12 x 18, 864 x 1296
Arch A: 229 x 305, 9 x 12, 648 x 864

Why not support the ANSI paper sizes:
(mm, in, pt)
ANSI A: 216 x 27, 8.5 x 11, 612 x 792
ANSI B: 279 x 432, 11 x 17, 792 x 1224
ANSI C: 432 x 559, 17 x 22, 1224 x 1584
ANSI D: 559 x 864, 22 x 34, 1584 x 2448
ANSI E: 864 x 1118, 34 x 44, 2448 x 3168

What about supporting the JIS B paper size series (from JIS B0 to B10) and (at least some of) the traditional Japanese formats, e.g. the Kiku-ban (菊判) 150 × 220 mm and Shiroku-ban (四六判) 127 × 188 mm ?

It took me a moment to understand that our (identical) FLSA and FSLE are propably an American and resp. European "Foolscap" format. But both ours correspond to 8.5 x 13in (612 x 936pt) while there's a huge variety of such Foolscap sizes (e.g. 8 x 13in)...

Some of the other traditional names we have make sense (assuming "letter" = US Letter, etc.) though we could question their exact name and their choice (e.g. our "Monarch" seems to be an envelope size, not the "imperial" book size of the same name...). And we have a Tabloid, but not the US trade book (6x9in) which is one of the usual option in POD, so I don't know where we'd want to go here.

Erm. I realize this goes beyond the initial issue, but let's admin I don't really care if we support A4 besides a4. That's purely cosmetic, vs. supporting good format names and useful selections...

**Comment by alerque** [comment]
I tucked in support for a few more of those standard sizes, but there are many more that could be added. Feel free—my only criteria is I don't want to add any that can be ambiguous. We already have a few and I haven't removed them, but at least the ones we add should be pretty unambiguous unless we have a good method for selecting the right one.
