### ISSUE TITLE
A thought on full bleed printing, trim areas and cropmarks

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1439]
I was about to add this comment to #1285, but it's a more general topic, which (beyond mere cropmarks) requires that we think about a more general solution to the underlying question, though these things are somehow related anyway (IMHO)...
  1. Sometimes, as show in the example in #1285, one wants to produce, say, a 6x9in book but only has a regular printer, with A4 paper: the expectation is to have, usually, the "intended" page to be (more or less) centered. That's the "poor man" solution (I want to see print my 6x9 in book as it would appear in print, but centered on the only paper available to me... Or: I am going to distribute an A4 version to proofreaders, so they have the book as intended, but lots of margins for annotations, etc.)
  2. But more seriously, professional printers nowadays rather expect an extra "trimming" margin around the target page -- for what is usually called "full bleed" printing. E.g. the extra space around the target page could be 3mm (0.125in), and the assumption then is that "full page" images or background color would extend past the target page size so as to cover the bleed area -- when the pages are "cut", one wouldn't want blank white space to occur if for some technical reason the cut is not perfect...
  3. Cropmarks are a bit orthogonal to the above points, but somehow related: Some printers want them (honestly, AFAIK, it's seldom used nowadays in the PDF printing era...), as visible "cut" indications; but others would reject them and just ask for proper bleed areas, e.g. in my example, directly ask for a 6.125x9.125in PDF as their input, without any visible cropmarks...

All of the above, as the "papersize", is something one usually decides globally for a whole document, not when loading (on-demand, at any point in a document, a package...)

Summarizing:
- Document level options (i.e. as the papersize) rather than when some package is loaded at some point... (We wouldn't want to change that, usually, in the course of a document...).
- Actual paper size vs. target page size
- Bleed areas
- Optional cropmarks, for those who want such things
- Ensuring full page content actually extends over the bleed area (= e.g. `background` package, I'm looking at you...)

![image](https://user-images.githubusercontent.com/18075640/173961614-ace5532c-897c-4cb8-864b-16245f8ed803.png)

Kind of a proposal for discussion...

- `begin[pagesize=6in x 9in, bleed=0.125in}{document}` = leads to a 6.125x9.125in PDF, with bleed distributed evenly.
- `begin[pagesize=6in x 9in, bleed=0.125in, papersize=a4}{document}` = leads to an A4 PDF, with a 6x9 centered page, and bleed distributed evenly, applying to background color/images. Obviously, error if pagesize + bleed > papersize, and bleed defaults to 0 if unspecified.
- `begin[..., cropmarks=true]{document}` = show crop marks around the pagesize, for any of the above cases.

The current way (with `begin[papersize=...]{document}` would merely mean the page size is the same as the paper size, with no bleed area.

And the `%pw` units, or page-related frame dimensions, of course apply to the pagesize.

Whether one uses print-on-demand services (such as Lulu, Blurb, KDP, etc.) or professional printers, it seems to me that "full bleed" printing with bleed areas is the "standard" today, without the (old-fashioned?) cropmarks. Whether the above proposal is sound or not, we should likely address it and make it easier for users.

**Comment by alerque** [comment]
Just a heads up I have a *much* improved crop package in CaSILE that I use for full bleed stuff in production all the time. It makes some assumptions that it would be nice to more to document class options like you suggest, just dropping this here so you know about it...
