### ISSUE TITLE
Footnotes stop working part way through manual

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1453]
The last footnote in the manual is in §5.7 on p33, but there should be more. I noticed while mucking about with the new Esperanto support (#1444) and why in the world the Ruby package docs are killing the manual build (#1451) that the footnote I added was showing a marker but no footnote. Another example in the current manual sources in *master* might be in §11.1 on p98 where I see another marker but no footnote.

**Comment by Omikhleia** [comment]
Using `SILE.require` however causes other issues later, e.g.
```
Error detected:
	./packages/twoside/init.lua:43: attempt to index a nil value (local 'args')
```
(Package tries to initialize without args... We have a serious API issue here now...)

> EDIT: Now why loading the insertions with a "require" breaks them, I'have no idea !

Found. Because of the local vars
```
local insertionsThisPage = {}
```
(If replaced by a global scratch variable, and autodoc reverted to require, then the footnote is there).

**Comment by alerque** [comment]
> However the code, a few lines below that one, now manually registerCommands. It seems wrong to me anyway (commands could expect settings and initialization so as to work properly...).

Commands may require their respective packages to be initialized when they *are called*, but they should not require anything to *register*. By the time they are used the package will be initialized.
