### ISSUE TITLE
Manual (a PDF) table of contents hyperlinks are wrong

### ISSUE THREAD

**Issue by dontlaugh** [sile-typesetter/sile#1459]
Here is the URL I'm looking at in Firefox

https://sile-typesetter.org/manual/sile-0.13.1.pdf

Clicking on headings, like "The Nitty Gritty", does not link me to that section of the PDF. This behavior was the same when I downloaded the PDF and opened it in Gnome's default pdf viewer.

**Comment by Omikhleia** [comment]
It starts getting wrong after §5.28.16 "tableofcontents" (with the next section, "xmltricks", pointing to the very first chapter), so unless we missed a re-run, it looks quite similar too #1453 (which solved it for insertions, but not sure the solution is general enough) = autodoc performing a "require" resetting some locals.
