### ISSUE TITLE
Obsolete SILE manual chapter 11.3 Other Features

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1471]
In the SILE manual (as of v0.13.2), noticed in passing that we have that fairly old **11.3 Other features** chapter:
> SILE’s DocBook implementation is a work in progress, and there is more that can be done. For instance, there is a basic implementation of lists, which equally need to be able to handle nesting; we implement another stack to take care of the type of list and list counter at each level of nesting. How would you handle a tag like `<xref>` which renders a cross-reference to another part of the document? For instance, `<xref linkend="ch02"/>` should generate something like _Chapter 2, “Second Chapter”_. This is another problem which can be handled using the infonode package to collect and store cross-reference information about chapter numbers and titles.

- Lists have been addressed in #1365 in SILE v0.13.2
- Cross-references might be addressed at some point (#1366)

True, a dedicated issue could be opened on the mentioned DockBook implementation to use these. But I am not sure anyone is currently developing it (see #1338).
Anyhow, time is passing with new features being added to SILE, etc. I think this chapter is hard to keep up-to-date anyway regarding the things that could be done...

Possibilities:
- Rewrite it with contents pertaining to the current efforts and areas where help would be neat...
- Or remove it fully - it's not where such things should be tracked. (= In my opinion at least).

**Comment by alerque** [comment]
At first glance I'd say nuke it, but I'll give it a second gander...
