### ISSUE TITLE
Mongolian shaping is foo-bared

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1472]
I noticed while reviewing the Jekyll→Zola transition on the website that our Mongolian example output has shaping that is is pretty much borked to pieces:

![image](https://user-images.githubusercontent.com/173595/177880722-461e7e28-15bf-409e-93a4-23d5d7a01d57.png)

A couple quick tests with docker suggest it was last working properly in v0.11.1 and anything v0.12.0–HEAD turns up the same scrambled output. Not a proper bisect yet, but at least a range to look into.

The website file `content/examples/mongolian.sil` is suitable as a regression test, although it could probably use cleanup.

**Comment by ctrlcctrlv** [comment]
Likely related to my CJK tate thoughts.

**Comment by alerque** [comment]
c.f. #501 and #1245.

Yes the CJK / tate / everything related is a mess, but *this particular issue* may actually be a bogus example on our part. It works fine if I set the font direction correctly, the example here sets it to a bogus value missing the TTB bit (kind of important). The only other thing is I would have expected the frame direction to propagate to the font direction without having to set it manually, so I'll look into that briefly.
