### ISSUE TITLE
The `date` package causes an error

### ISSUE THREAD

**Issue by khaledhosny** [sile-typesetter/sile#1476]
I’m re-compiling some not-so-old SILE documents today and the `date` package seems to be broken. The following test document:
```
\begin{document}
\script[src=packages/date]
\date[format=%d %b %Y]
\end{document}
```
produces:
```
$ sile test.sil
SILE v0.13.2 (Lua 5.4)
<test.sil>

Error detected:
	...cal/Cellar/sile/0.13.2/share/sile/packages/date/init.lua:21: attempt to call a nil value (method 'date')
```

**Comment by Omikhleia** [comment]
Quick analysis: the "script" command doesn't load the exports into the class.

**Comment by Omikhleia** [comment]
Somehow relates to #1385 -- Though regression as the above should likely occur in 0.13.x rather that 0.14, IMHO...

**Comment by alerque** [comment]
Yes, the load action being run by `script` is out of sync with the one being done by `SILE.require()`.

A quick fix for the document would be to load it differently, change:

```sile
\script[src=packages/date]
```

to:

```sil
\script{SILE.require("packages/date")}
```

This is something that we could land in a patch release for sure. I just got back home after a few days out and am going to take quick stock of how close I am to having 0.14.0 ready to go.
