### ISSUE TITLE
Space after subsection number in 0.14.0 & 0.14.1

### ISSUE THREAD

**Issue by matteodelabre** [sile-typesetter/sile#1523]
As of version 0.14.0, there is no longer a space between the subsection number and the subsection title, where there was one in version 0.13.1. This can be seen in the subsections of section 5.28 [in the manual for 0.14.1](https://sile-typesetter.org/manual/sile-0.14.1.pdf#dest65) vs. [in the manual for 0.13.1](https://sile-typesetter.org/manual/sile-0.13.1.pdf#dest65).

**Comment by alerque** [comment]
My fault. I refactored some of the section numbering stuff to facilitate better localization and I accidentally moved the space to after the subsection title instead of before the title and after the subsection number.
