### ISSUE TITLE
The rotate command weirdly offsets the rotated text (0.9.5 regression?)

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1530]
(_While trying to dispose some 90°-rotated text in the spine area of a book cover..._)

The `\rotate` command doesn't place the text as expected.

In v0.9.5, this was (more or less, see below) correct, i.e. decent-looking in the manual:
![image](https://user-images.githubusercontent.com/18075640/185137672-fa7dd60d-bd03-4f63-ae38-e73f59a91ecc.png)

Since v0.10.0, this is weirdly offset to the right:
![image](https://user-images.githubusercontent.com/18075640/185138650-4ed84ef4-1c61-48a5-af84-dd45b99684f4.png)

Obviously still offset in v0.14.2 nowadays (I added bars to better show the effect, and a 90° angle): 
![image](https://user-images.githubusercontent.com/18075640/185140308-104275f5-23b8-4e48-9074-21bea464e8f3.png)

~~This issue perhaps somewhat relates to #427 from 2016 ("The axis is not in the center."), but not considering here frames which have their own issues.~~ EDIT: Nope, frames don't use the "offending" bit of code quoted below.

The change between 0.9.5 and 0.10.0 can be traced:
```
-  local horigin = typesetter.frame.state.cursorX + origbox.width.length / 2
-  local vorigin = -(typesetter.frame.state.cursorY - (origbox.height) /2)
+  local horigin = (typesetter.frame.state.cursorX + origbox.width.length / 2):tonumber()
+  local vorigin = -(typesetter.frame.state.cursorY + origbox.height / 2):tonumber()
```
If not mistaken, this was introduced by f4a64e7dfdb6a17e91e7d09122ad533f8bf13e38, which relates to sanitizing lengths vs. measurements vs. units, so the **sign change** in the `vorigin` formula is probably a typo, rather than a voluntary change?

Fixing it back as it was in 0.9.5, i.e.
```
  local vorigin = -(typesetter.frame.state.cursorY - origbox.height / 2):tonumber()
```
We'd get:
![image](https://user-images.githubusercontent.com/18075640/185142627-71250de7-9dff-4c11-a4f4-be68b540e204.png)

While this does look as it did in 0.9.5, I however wonder whether the following wasn't actually intended:
```
  local vorigin = -(typesetter.frame.state.cursorY - (origbox.height-origbox.depth) / 2):tonumber()
```
![image](https://user-images.githubusercontent.com/18075640/185143219-525f2f6d-3a52-462d-9638-b02a499851d4.png)

It's hard to tell from the package documentation what was the intended behavior, but my attempt above seems better centered (?)

By the way, as we could look at this possible regression, perhaps could we take that opportunity to add more control on the rotation "anchor" point, i.e. minimally allowing to specify it as "c(enter)" (as here) or as "n, nw, ne, e, se, s, sw, w" to select corners and sides? I mean, e.g. something to the effect of the highlighted pictogram from Gimp: 
![image](https://user-images.githubusercontent.com/18075640/185147121-cc275587-97ec-4ecc-b849-bc3f0eb82f82.png)

But I'll admit I was always bad at rotation matrices - maybe someone more at ease with the math and formulas could be interested in giving it a shot?

**Comment by alerque** [comment]
We *have* a test that would have shown this regression, but we don't have expectations for it because it only works with the actual PDF backend and not the debug dummy one. :disappointed:

I agree having a robust way to specify the axis origin would be a nice addition. We should probably open a new bug to track that though as I intend to push the fix through before I would have time to work on such an additional option.

**Comment by Omikhleia** [comment]
> I agree having a robust way to specify the axis origin would be a nice addition. We should probably open a new bug to track that though as I intend to push the fix through before I would have time to work on such an additional option.

Yes, indeed. Opened a dedicated issue on this possible enhancement.
