### ISSUE TITLE
Relative SVG filename not working (svg package)

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1532]
SILE 0.14.2 (... actually an older bug from my 0.12.5 backlog)

Folder content:
- `experiments/pic.png`
- `experiments/pic.svg`
- `experiments/svgissue.sil`

Where `svgissue.sil` is:
```
\begin{document}
\use[module=packages/image]
\use[module=packages/svg]

\img[src=./pic.png]

\svg[src=./pic.svg]

\end{document}
```
Running from the parent directory, i.e. `sile experiments/svgissue.sil`

Observed result:

```
SILE v0.14.2-dirty (Lua 5.4)
<experiments/svgissue.sil> as sil

! Unexpected Lua error

error summary:
	Processing at: experiments/svgissue.sil:7:1: in \svg[src="./pic.svg"]
	Using code at: ./packages/svg/init.lua:60: attempt to index a nil value (local 'svgfile')
```

The PNG image works.

The `\svg` command should likely call `SILE.resolveFile()` (as done by the `\img` command, with an adequate error message)

**Comment by alerque** [comment]
Agreed, relative `src=` references should use `resolveFile()` to check both relative to CWD and the document.

A related question though, should `resolveFile()` file be expanded to consider paths relative to the Lua file being executed (for `SILE.call("svg", { src = ... })` inside modules)? If so #1529 or some variant of that code should enable that, but the question is, **would this  be expected or unexpected behavior**?

**Comment by Omikhleia** [comment]
Sorry for the late comment on #1529, I too was pretty busy refactoring my old 0.12.5 classes and packages (both to 0.14 and luarocks[^1]) and missed noticing it... I actually faced the same issue locating package image resources and fixed it in [a very similar way](https://github.com/Omikhleia/couyards.sile/blob/34cdae0dc984d517d3fc57a8432850e855c5b505/packages/couyards/init.lua#L16), without fully being convinced that faking resources (here .svg file) as "lua" in the rockspec is really legit, though it kind of works...

For the more general question, it's harder to say. From a user perspective, I'd expect paths relative to the current _input_ document (i.e. my .sil, .md, .xml or whatever) be resolved to it (perhaps _even_ regardless of the CWD ?). E.g. it may seem weird if my document `folder/subfolder/somefile.sil` refers to `\img[src=toto.png]` and the later is loaded from anything else than `folder/subfolder/toto.png`). I certainly don't expect it to be loaded from some package's folder. But the big picture might to be that obvious.

[^1]: This is a pretty cool feature, kudos for it! I once ditched luarocks a bit too quickly and would have to apologize for that. Once one gets the idea (which was not that _obvious_ in the first place, we may need comprehensive docs to help with that), it's just rocks indeed, and we even get an easy way to list [published modules](https://luarocks.org/m/sile) - Congrats from a quite stubborn or long-to-understand guy. ;)

**Comment by alerque** [comment]
> without fully being convinced that faking resources (here .svg file) as "lua" in the rockspec is really legit, though it kind of works...

I got that trick directly from the author of `luarocks` when we were discussing the possibility of using it as a plugin manager in this way. He plans to add better first class support for other resources, but given that it takes a long time for updates to get into all distros (looking at Ubuntu here) we kind of needed a solution that works on old versions too, and that was what he recommended.

> From a user perspective, I'd expect paths relative to the current input document (i.e. my .sil, .md, .xml or whatever) be resolved to it (perhaps even regardless of the CWD ?).

Okay, but what if your document `a.sil` includes another document, say `../b/c.sil` and there is a resource `../b/d.png`. The document c wants to include image d. How does it reference it? Perhaps the b directory is shared between several projects. I would expect paths to be first relative to the master document, and probably secondarily relative to the document fragment being processed.

> E.g. it may seem weird if my document folder/subfolder/somefile.sil refers to \img[src=toto.png] and the later is loaded from anything else than folder/subfolder/toto.png). I certainly don't expect it to be loaded from some package's folder. But the big picture might not be that obvious.

I have workflows that expect the opposite. Common "fragments" repositories have relative paths to assets and the resources are co-located with the fragments. When I want to override some asset in one project but not another all I have to do is provide a new asset along with the document, overriding the common one from the include space.

How would you expect to handle overrides like this?

**Comment by alerque** [comment]
This *could* be a breaking change for some documents in the event people planned on running `sile` from a directory other than the document root, but given the inconsistency with images of other types with similar syntax I'm just going to call this a fix.

It doesn't need a separate test because two existing tests confirm it works.
