### ISSUE TITLE
CLI options -O and -c issues

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1533]
SILE 0.14.2

1. Trying to override a document paper size with `-O papersize=a7` (to override the document a4), it had no effect at all.

    https://github.com/sile-typesetter/sile/blob/01be7155ab07057a51a80e82c07665cbfe268e95/core/cli.lua#L86

   Possible fix:
   ```
   SILE.input.options = pl.tablex.merge(SILE.input.options, options, true)
   ```

1. Trying to enforce another class with `-c resilient.book` (to override the document "book"), it raised an error:

     `! Cannot change class name after instantiation, derive a new class instead.` (...)

    Possible fix:

    https://github.com/sile-typesetter/sile/blob/01be7155ab07057a51a80e82c07665cbfe268e95/inputters/base.lua#L25

    Adding `options.class = class` below that line, since the options are later passed to the class constructor.

    Might not be a general/appropriate fix, as with the previous fix above, `-O class=resilient.book` seems to work, so maybe it could be done in a more generic way.

**Comment by alerque** [comment]
The priority for overriding options per №1 is clearly backwards. I can fix that.

I'm not so sure about how to fix №2 but I'll look into it. It seems like I must have only tested setting the class from the CLI on documents that did not call out their own class internally, i.e. in non-native XML variants, etc.

Which order would you expect `-c` and `-O class=` to take affect? Having the CLI override the document makes sense to me, but when I added `-c` I'm not sure I was even thinking about `-O class=` being an existing possibility. Also `-u classes.foo` will have a similar effect, but I would expect it to be slightly different than `-c` in that it resets the default class if none is specified but doesn't override the actual class if one was specified. Do my expectations make sense to you?

**Comment by alerque** [comment]
P.S. Yes I know I'm a week behind on notifications and working in reverse order. I see several other from you, I'm not ignoring you I just only have so many hours in the day to give.

**Comment by alerque** [comment]
I think I'm going to pretend `-O class=` is not a thing. The "class" to classes is king of a pseudo option already. The class is passed options and also the option naming itself. We don't allow it to change itself, so any case where that option is not already consumed is considered an error. It is kind of a half way measure between commands that are commands and the one magic top level command (whether `\document` or `<sile>` or something else) that actually initializes a class.

Lets pretend the document itself and the `-c/--class` arg are the only two right places to set that value. As such figuring out the order of where `-O class=` would be is irrelevant as we officially don't recommend it.
