### ISSUE TITLE
pdf package lacks an initialization

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1534]
SILE 0.14.2

(Simplified) reproduction scenario

```
\begin[class=book]{document}
\use[module=packages.pdf]

\pdf:destination[name=here]

Lorem ipsum 

\pdf:link[dest=here]{Link}

\end{document}
```

Observed result:

```
/usr/sbin/lua: /usr/local/share/sile/packages/pdf/init.lua:46: PDF object not initialized!
stack traceback:
	[C]: in function 'justenoughlibtexpdf.destination'
	/usr/local/share/sile/packages/pdf/init.lua:46: in method 'outputYourself'
	/usr/local/share/sile/core/nodefactory.lua:498: in method 'outputYourself'
	/usr/local/share/sile/typesetters/base.lua:577: in method 'outputLinesToPage'
	/usr/local/share/sile/typesetters/base.lua:419: in method 'buildPage'
	/usr/local/share/sile/classes/base.lua:554: in function 'classes.base.finish'
	/usr/local/share/sile/classes/book.lua:79: in function 'classes/book.finish'
	/usr/local/share/sile/core/sile.lua:406: in function 'core.sile.finish'
	/usr/local/bin/sile:128: in main chunk
	[C]: in ?
```

Note that it only occurs if this is on the first document page (upon a new page, `ensureInit()` is invoked by the outputter), so it's easy to miss in most documents which have, e.g. a title page.

**Comment by alerque** [comment]
I agree this looks like a bug, but also I'm concerned about beginning to introduce module order problems. Having a package initialize the outputter on load will break some other packages, e.g. crop marks or full bleed type packages that need to fiddle with the outputter before it gets going.

Perhaps adding an init isn't the right move but adding `ensureInit()` to all user facing functions might do the trick.

**Comment by Omikhleia** [comment]
Could be fixed by calling the `_ensureInit()| in the relevant commands only (i.e. upon actual use, as done in the pdfstructure package).
A longer term solution would be to avoid those direct pdf access and delegate them to the outputter, but that's probably what #902 is about.

**Comment by alerque** [comment]
Unfortunately a "real" fix for this is complicated because the `justenoughlibtexpdf` C module uses shared state. The outputter never gets called here. We could move all the package logic to the outputter and some sort of stubs to call them, but I think there are more important scope issues to work on first. This one is easy to find and refactor when we get a chance.
