### ISSUE TITLE
Should twoside package now really impose mirrored pages? (0.14)

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1558]
My use case here is a book where left and right page masters are not _exactly_ mirrored, i.e. aren't the result of a `self:mirrorMaster("right", "left")` in my class (rationale further below).

In SILE 0.12, I used to do the following thing:
- Define my "left" master
- Define my "right" master
- Load the twoside package, initialized with those.

It took me a bit of time to understand why this was no longer working after trying to upgrade that code to 0.14: Here [twoside](https://github.com/sile-typesetter/sile/blob/2afb5fa9500daef01f2e4d6229eb04d47f91a2ca/packages/twoside/init.lua#L66) now automatically mirrors the frame in a post-init hook, ignoring whether both were already defined.

I worked around this, having an additional post-init hook to re-apply my intended (manually made) left and right masters. Still, this does seem very contrived now!

The rationale is twofold:
- Sometimes, `mirrorMaster` doesn't do what one expects (depending on how the frame is defined, possibly referring to the page with in complex way, which happens to be my case for, notably, margin area for sidenotes, it just fails...)
- _Even when it does work_, in the book I'm considering, the frames that aren't just mirrored, but some are placed differently (vertically) on odd and even pages...

(Porting this to 0.14, I was trying to chase another issue (relating to something wholly different, pertaining to insertions), and got stuck here for a few hours, trying to understand what had changed. As stated, I eventually found the cause and re-applied my expected frames in a post-init hook, so as to cancel what the now "automated" mirroring had done. I'm back on chasing that other unrelated insertion issue again, but still, I am not sure this was an intended side effect of making "twoside" too clever -- One should have IMHO a way to use it with different masters, as it was the case before)

**Comment by alerque** [comment]
No it shouldn't do that.
