### ISSUE TITLE
Typo in 0.14 textcase package name prevents using its methods from class

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1568]
SILE 0.14.0-0.14.3 has a small typo here:
https://github.com/sile-typesetter/sile/blob/a60c6f4eeaf5063aea41cb5b32bafa601d463f4c/packages/textcase/init.lua#L4

te**tx**case > te**xt**case, or one will fails using the methods in code such as `self.class.packages.textcase:lowercase()` in one's own package (= the issue as I experienced it, it might have other side effects probably).

**Comment by alerque** [comment]
Good grief. Not only did I typo this here I managed to get my own downstream production projects to work because I typed it the same way there. More than probably the propagation happened because my editor completes tokens based on everything I've had open recently.
