### ISSUE TITLE
Processing XML with the deprecation of the -I cli option

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1570]
Before 0.14, one could process an XML file using a `-I` preamble:
```
sile -I examples/dict-sd-fr-preamble.sil  examples/dict-aq-fr.xml
```
Where the preamble was a self-contained SILE-document (specifying a class with options, possibly tweaking some settings and hooks, etc.)

In 0.14, this still works currently but of course emits a deprecation warning:
```
! -I/--include() was deprecated in SILE v0.14.0. Please use -u/--use or -p/--preamble() instead.
```

However:
- The `-I` cannot just be replaced with just a `-u` obviously (it's not a module, and thus errors) 
- It cannot just be replaced with `-p` as the preamble then file is loaded without honoring the declared class (so settings won't be available, etc.)

I came up with:
- Either `sile examples/dict-sd-fr-preamble.sil -P examples/dict-aq-fr.xml`: works, but inappropriate as the output PDF has, quite logically, the name of the preamble, not of the processed XML file (and adding a `--output` is not very user-friendly).
- Or `sile -u classes.teibook -p examples/dict-sd-fr-preamble.sil  examples/dict-aq-fr.xml`: kind of works (after locally fixing #1569), but the command line is not very user-friendly either (esp. if there were also class options to specify)

Migrating some of these classes, I wonder what would be the best approach to provide something "as simple" as it used to be for such a use case.

**Comment by alerque** [comment]
What kind of content is in your `dict-sd-fr-premble.sil` that would not belong in a dedicated class module? The solution I've used elsewhere was to write a class that inherited (to use your example` *classes.teibook* and adds the use case specific commands for the type of XML I was loading.

I was envisiouning preambles as actual content that would end up inside the primary document. Kind of like a fax cover sheet (yes my beard is greying). I always thought the method of stuffing macros is a preamble to handle a document type was weird.

Another approach I used on a non XML file and later for an XML variant of the same content was to write an inputter module that also specified the default class, and made the default class for that file input type be something that made sense for the content type. Again no preamble required.

I'm quite willing to evaluate other use cases, but if the preamble is just a bunch of tag handling commands it makes more sense to me to write it as a module: whether a class, package, or inputter.

**Comment by Omikhleia** [comment]
> What kind of content is in your dict-sd-fr-premble.sil that would not belong in a dedicated class module

Things that are dependent from the input XML file, a multilingual dictionary, and cannot be fully known by the class:
- Hyphenation exceptions for a peculiar dictionary content
- Settings pertaining to the variability in ordering some tags depending on main language (e.g. order for translations, skipping some language-specific parts, etc.)
- Obviously, presentation decisions (such as fonts etc.)
- Fine tuning (e.g. emergency stretch tweaking, secondary packages when required...)

**Comment by Omikhleia** [comment]
Closing my own issue/question. I've found ways to handle this, and there's no need for SILE's core team to address anything here.
