### ISSUE TITLE
Support for arm64 as an architecture? arm64 support on the Ubuntu PPA? 

### ISSUE THREAD

**Issue by n7s** [sile-typesetter/sile#1576]
Is sile available for the arm64 architecture? Are there plans to make it happen? With the rise of this architecture, mainly M1/M2 chips and Raspberry pis for our needs, it would be lovely to be able to use sile there as well. 

It would be very useful to have an arm64 version of sile for Ubuntu published in the PPA. 
Details for the Launchpad side of things on: https://dev.launchpad.net/CommunityARMBuilds

It looks like there are some sile packages for Arch Linux who have enabled in some arm-based architectures, I guess that means it's doable for other distros as well? 

Thanks!

**Comment by alerque** [comment]
SILE builds and runs on Arm64 just fine, I already use it on some Raspberry Pi boards myself. It builds on ARMv6 ARMv8 too. Prebuilt packages are available for Arm64 in Arch Linux, Nix, and I *think* Homebrew.

I've already tried requesting builds for the Ubuntu PPA but the builders were running so far behind (days) that I dropped it because I could never tell if the other platforms were working or now because it was always hung waiting is some queue.

I'll look into enabling them again, maybe the build infrastructure has gotten worked out.

**Comment by n7s** [comment]
Glad to hear that sile works just fine on this new architecture, I really appreciate all your work on this! Thank you. I must have missed something when I tried building sile on my Raspberry Pi 4 (arm64). 

(looks like the Launchpad builders are more available now: https://launchpad.net/builders - I have also experienced slowdowns on the build queue especially when Ubuntu is gearing up for a release and doing full rebuilds of the archive).

**Comment by n7s** [comment]
how soon do you think you would be able to look at this? Thanks.

**Comment by ctrlcctrlv** [comment]
He said it works, so why not try building it? Why does it have to be through Ubuntu's PPA? Not understanding.

**Comment by n7s** [comment]
yes, it does work when building locally (once I sorted out some deps issues), but others need it pre-built in the PPA.

**Comment by ctrlcctrlv** [comment]
I understand, sorry :)

**Comment by ctrlcctrlv** [comment]
Now that you have a working .deb and know which dependencies are needed maybe you could take over? Does it work like AUR?

**Comment by n7s** [comment]
no problems. I mean it works as in "I can build the codebase from source on the target architecture. But sorry I lack the extra time to tackle the packaging myself, and I'd rather leave the ongoing work in Caleb's more capable hands.

**Comment by alerque** [comment]
I'm sorry I've been traveling for a couple weeks and still have until the end of this week in Kazakhstan. I've been doing what I can here and there but won't be able to make serious progress on any OSS front until I'm back at my desk.

**Comment by n7s** [comment]
no hurry, enjoy your trip!

**Comment by alerque** [comment]
I'm back and starting to dig my way out.

I've enabled arm64 (ARMv8) builders on the SILE PPA and started the process of resubmitting all packages for rebuilds. This will have to start with all the dependencies and eventually SILE itself. I'll by babysitting the bumps and builds while I work on other things but expect it to take a day or so.
