### ISSUE TITLE
Error in the Manual: Page 26 fails to complete sentence.

### ISSUE THREAD

**Issue by ThatGeoGuy** [sile-typesetter/sile#1586]
Reading [the manual](https://sile-typesetter.org/manual/sile-0.14.3.pdf), I found a bit of a jarring break on the end of page 26:

![Screenshot from 2022-11-02 19-10-03](https://user-images.githubusercontent.com/5060863/199630228-418b3d42-aa56-48a1-bf66-64ff4d2cc8a3.png)

The sentence ends with: 

>  This means that for the environment block version (\begin{script}) there must

There must...?

**Comment by alerque** [comment]
Sentences must not
