### ISSUE TITLE
AST parser is duplicating nodes

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1611]
Our last few versions have gone out with the version string on the cover page duplicated:

![image](https://user-images.githubusercontent.com/173595/202536610-1bfa1347-00d6-4ca0-9b5f-9c0e3dc5226f.png)

I've actually seen it before, but I always assumed the cause was too trivial to open an issue for a copy/paste duplication and that I'd just fix it. As it turns out the root cause is not trivial at all. Our new shiny SIL input parser is massaging the AST returned by the PEG parser and detecting some things twice. Notably some kinds of pass-through content is getting returned as both a string and a more detailed info node, but when the AST is cleaned up with end up with both versions. Hence anything in a `\lua{}` command is actually getting executed twice! This is almost certainly responsible for some weird stuff I've seen lately because running Lua code twice is not always idempotent (although I guess this would be a good way to stress test that it is!).

**Comment by ctrlcctrlv** [comment]
> running Lua code twice is not always idempotent

Honestly working on this project has not made me love Lua… but perhaps familiarity breeds contempt. :)
