### ISSUE TITLE
Boustrophedon package issue at page break

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1614]
Observed with SILE 0.14.4

I was working on the SILE manual with the aim of experimenting and proposing some improvements, when due to my page changes, I stumbled upon this issue. Extracting a scenario from the documentation:

```
\begin[papersize=a7]{document}
\neverindent
\nofolios
\use[module=packages.boustrophedon]
\font[size=20pt,family=Gentium Plus,language=grc]

Lorem ipsum dolor...

Good case
\skip[height=4cm]

\begin{boustrophedon}
ΧΑΙΡΕΔΕΜΟΤΟΔΕΣΕΜΑΠΑΤΕΡΕΣΤΕΣΕΘΑΝΟΝΤΟΣΑΝΦΙΧΑΡΕΣΑΓΑΘΟΝΠΑΙΔΑΟΛΟΦΘΡΟΜΕΝΟΣΦΑΙΔΙΜΟΣΕΠΟΙΕ
\end{boustrophedon}

After

Lorem ipsum dolor...

\end{document}
```

Observed:
![image](https://user-images.githubusercontent.com/18075640/202768143-08779ab6-1b45-4d8d-82cd-7250b400a374.png)

~~I did not investigate further, but~~ something is still active outside the boustrophedon environment after the page break occurred.

Obviously, removing or commenting out the vertical skip introduced here just to push the text at page boundary, the issue doesn't appear:
![image](https://user-images.githubusercontent.com/18075640/202768690-8328bee0-f031-4761-870b-15969a42e849.png)

FWIW, in the broken scenario above, adding more regular paragraphs at the end of the document: things are actually back to normal after a subsequent page break.

**Comment by Omikhleia** [comment]
Issue closed in https://github.com/sile-typesetter/sile/milestone/40 (or is there a reason to keep it open?)

**Comment by alerque** [comment]
Nope, just the PR link to this issue didn't explicitly mark it as closed and I missed it in triage.
