### ISSUE TITLE
Deprecate "quote" and "listitem" commands (plain class)

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1625]
SILE 0.14.5

While looking at #543, I couldn't avoid noticing the `quote` and `listitem` commands in the **plain** class...
- The latter is not typographically sound. It should be deprecated with recommendation to use the **lists** package.
- The former doesn't allow quote nesting, has poor code quality, weird decisions (explain the "noindent" there...) and side effects (switches to justified afterwards, rather than restoring the previous values). IMHO it has nothing to do in the plain class , but would we want to keep it, it ought to be replaced by a better alternative...

**Comment by alerque** [comment]
I agree, both should be marked as deprecated.
