### ISSUE TITLE
REPL is broken

### ISSUE THREAD

**Issue by raphCode** [sile-typesetter/sile#1664]
The manual mentions `SILE.repl()` but it doesn't work:

```
error summary:
        Processing at: /usr/share/sile/core/sile.lua:391: in <snippet>:
                [[SILE.repl()]] near test.sil:3:1: in \script
        Using code at: [string "SILE.repl()"]:1: attempt to call a table value (field 'repl')
```
I tried `\script{SILE.repl()}` in a document as well as calling it from a lua module.

**Comment by ctrlcctrlv** [comment]
Strange. When not called from a script the REPL works (just as `sile`). Perhaps compare that invocation to yours and update the manual or fix the function to do whatever init is needed.

**Comment by raphCode** [comment]
I noticed that the `sile` drops me into the repl, but I haven't looked into the code.
Thanks for making me do it, it was really simple :)
