### ISSUE TITLE
libtexpdf.lua:148: attempt to concatenate a table value (local 'options')

### ISSUE THREAD

**Issue by khaledhosny** [sile-typesetter/sile#1670]
When loading a font that SILE can not embed in PDF (e.g. a font with CFF2 table), SILE produces a not so much helpful error message:
```
$ sile test.sil
SILE v0.14.6.r6-gcb9495a (Lua 5.4)
<test.sil> as sil
/usr/local/bin/lua: ./sile/outputters/libtexpdf.lua:148: attempt to concatenate a table value (local 'options')
stack traceback:
	./sile/outputters/libtexpdf.lua:148: in function 'outputters.libtexpdf.setFont'
	./sile/core/nodefactory.lua:183: in method 'outputYourself'
	./sile/core/nodefactory.lua:222: in method 'outputYourself'
	./sile/core/nodefactory.lua:502: in method 'outputYourself'
	./sile/typesetters/base.lua:588: in function 'typesetters.base.outputLinesToPage'
	./sile/typesetters/base.lua:424: in function 'typesetters.base.buildPage'
	./sile/classes/base.lua:562: in function 'classes/plain.finish'
	./sile/core/sile.lua:436: in function 'core.sile.finish'
	/bin/sile:138: in main chunk
	[C]: in ?
```

This comes from the line:

https://github.com/sile-typesetter/sile/blob/a9295838e2639dee9fde71d29717957deaf650d5/outputters/libtexpdf.lua#L148

Which have been like this since it was introduced in 82bee4d41, so I’m not sure if something changed elsewhere in the meantime or whether it was always broken.

**Comment by alerque** [comment]
What changed is we droped using Lua `stdlib` (which is not an standard as its name implies). One of many things it was doing was monkeying with the string concatenation operator and making it NIL safe and adding a table concatenation method. It no longer has those magic properties. I can fix this debug statement so the error case doesn't also throw an error.

**Comment by alerque** [comment]
The error message throwing an error message has been fixed, hopefully that will help you track down the original error better. Obviously something else is wrong in order to hit this code. I'm happy to review even WIP if you are having trouble tracking down the original error still.

**Comment by khaledhosny** [comment]
Ah, sorry. I know why the font is not loaded. It contains a `CFF2` table and libtexpdf only knows how to load fonts with `CFF` or `glyf`/`loca` tables. I’m working on a PR for #1182 that adds support for variable fonts using `glyf`/`loca` but `CFF2` is not supported and I was testing it to make sure it gives an error message when I came across this issue.

**Comment by alerque** [comment]
Sure. Let me know if there is anything I can do to facilitate your work, I know (even speaking for myself) that is a very desired feature right now!
