### ISSUE TITLE
Missing license file for lunamark in released tarball

### ISSUE THREAD

**Issue by hegjon** [sile-typesetter/sile#1685]
[LICENSE-lunamark](https://github.com/sile-typesetter/sile/blob/master/lua-libraries/LICENSE-lunamark) is missing in the 0.14.7 release tarball.

**Comment by hegjon** [comment]
Seems like all the external Lua libraries are missing the license file

**Comment by Omikhleia** [comment]
See #1610 where Lunamark would be removed from SILE core distribution anyway.

**Comment by Omikhleia** [comment]
BTW all _source_ files have their licenses in them, unless mistaken, or link to thereof. As far as I know (I am not a lawyer and have no official role here), this is usually sufficient, based on my experience.

**Comment by ctrlcctrlv** [comment]
No, that's insufficient.

The MIT license states:

> The above copyright notice and this permission notice shall be included **in all copies** or substantial portions of the Software.

The GNU GPL v3 states:

> You may convey verbatim copies of the Program's source code as you receive it, in any medium, provided that you conspicuously and appropriately publish on each copy an appropriate copyright notice; keep intact all notices stating that this License and any non-permissive terms added in accord with section 7 apply to the code; keep intact all notices of the absence of any warranty; and give **all recipients** a copy of this License along with the Program.

It's no legal problem if it's a mistake, so long as the project in question returns to compliance if the author asks. This bug is valid.

**Comment by alerque** [comment]
Yes our Lunamark fork will be removed in a future release, but that release will necessarily be marked as a breaking one (major version bump). Since our next couple scheduled releases are non-breaking (minor version bumps) and we've spotted this issue I don't see any reason not to fix the packaging. I'll tag the file for distribution.
