### ISSUE TITLE
fill glues created with an argument are no longer fill glues

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1721]
SILE 0.14.8

`(SILE.nodefactory.)hfillglue()`, `vfillglue()` (and `hss()` and `vss()`) are "most" of the time (= read "always" as far as the core distribution is concerned) called without argument, resulting in "0 plus infinity" (resp. "0 plus infinity minus infinity").

... but they can actually take an argument.
However, as implemented, invoking them with such an argument will just override the infinite stretch/shrink: they call the parent glue constructor with the argument, and thus will override completely their default length.

In other terms, `SILE.nodefactory.hfillglue("20pt")` is the same as `SILE.nodefactory.glue("20pt")`

That's completely useless: passing an argument has no interest at all... It looks a bit dumb too...

Expectation: `SILE.nodefactory.hfillglue("20pt")` --> 20pt plus infinity
I.e. keeping the fixed length part of the argument, and setting the strech (and shrink, for the hss/vss variants) to infinity.

That would make the task of nesting things much easier for developers (e.g. centering _within_ a block indent with margins on both sides, etc.).

**Comment by alerque** [comment]
Hm, I've never considered that constructor to take a value, but I suppose since the existing behavior is less than useless that this change wouldn't hurt anything. Personally I've just used `SILE.nodefactory.hfillglue("20pt plus 99999999pt")` (where I've never sure off the top of my head what a sane value for infinity is unless I stop and look it up). I can see how having a different constructor for that that fixes the infinite value to balance them with the values used internally would be a nicer UX.

**Comment by Omikhleia** [comment]
Yep, my point indeed is to avoid having the user guess what "infinity" is. (At one stage, I was even considering proposing something similar to TeX (which has `1fil` units etc.) but it does not seem that appropriate to SILE's way.)

**Comment by alerque** [comment]
If we can do this without TeX's concepts of different sizes and multiples of infinities that would be great. We already *do* have multiples, but not as a unit so much as repeated use (e.g. `\vfill{}content here\vfill\vfill` for a ⅓/⅔ vertical centered block). Maybe I'm trying to pretend that isn't a think and we should just make it a unit (`\skip[height=2inf]`). I'm rambling, I need to go drive to the office...

**Comment by Omikhleia** [comment]
`\skip[height=2inf]` would not be the same thing: I would read it as some infinite width).
Maybe `\skip[height=0 plus 2inf]` would mean what you imply (= some infinite stretch). But this is beyond the scope of this very issue, and I'm not to sure either about introducing such constructs.
