### ISSUE TITLE
Infonode errors with some debug options enabled

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1724]
SILE 0.14.8

Pretty minor IMHO, and only found so far with `-d break` on a book chapter:

```
Using code at: ./packages/infonode/init.lua:21: attempt to concatenate a table value (field 'value')
```

This line:

https://github.com/sile-typesetter/sile/blob/4dd91e323b077f0b66626cc09045e81f77ce2183/packages/infonode/init.lua#L20

Ought to be
```
return "I<" .. self.category .. "|" .. tostring(self.value).. ">"
```

N.B. The issue does not show up with `-d all` in my case -- It turns out the line break check for debugging mode bypasses it.  That's probably quite expected, though: It gets VERY verbose when enabled! (My only reason for enabling line break debugging was to check some personal experiments there, initially.) There might possibly be other debug scenarios where an infonode would need to be displayed, though, hence the report.

**Comment by Omikhleia** [comment]
After the suggested change:
```
...
[break] considering node I<toc|table: 0x55720719cd20>^
...
```

Not so sure showing the table address has any interest for debugging, so perhaps it could even be fixed as:

```
return "I<" .. self.category .. ">"
```

**Comment by alerque** [comment]
I think the output might vary depending on the info node. If the info node itself has some creative output when cast to a string it would be usable, if it doesn't have anything then you'll get the `table <hash>` blurb. I think I'll just leave it like that. Note that the table hashes can be useful if running a debug environment where you can lookup what they are.
