### ISSUE TITLE
Table of contents may warn it has changed when it hasn't

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1732]
SILE 0.14.8 (and earlier)

If a section title contains a command, e.g. `\section{Some \em{fancy} title}`, and the input text is slightly changed before it, but the eventual ToC would not be unaffected (the section has the same title, and still lands on the same page), the **tableofcontents** package will however warn for a re-run (`! Warning: table of contents has changed, please rerun SILE to update it.`)

As can be seen in the `.toc` file, this is due to the dumped content tree containing the position (pos, lno, col) of the original text, where the command occurs:
```
...
    label = {
      "Some ",
      {
        "fancy",
        col = 12, -- DOH
        command = "em",
        id = "texlike_command",
        lno = 264, -- DOH
        options = {
        },
        pos = 11214 -- DOH
      },
      " title",
      id = "stuff"
    },
...
```

Obviously, we don't need to care of the _exact_ positions in that context, so I would suggest stripping the information in such a case where a content is dumped.

I.e. possibly have a `SU.stripContentPos()` utility:

```
--- Strip position, line and column recursively from a content tree.
-- This can be used to remove position details where we do not want them,
-- e.g. in table of contents entries (referring to the original content,
-- regardless where it was exactly, for the purpose of checking whether
-- the table of contents changed.)
--
utilities.stripContentPos = function (content)
  if type(content) ~= "table" then
    return content
  end
  local stripped = {}
  for k, v in pairs(content) do
    if type(v) == "table" then
      v = SU.stripContentPos(v)
    end
    stripped[k] = v
  end
  if content.id or content.command then
    stripped.pos, stripped.col, stripped.lno = nil, nil, nil
  end
  return stripped
end
```

And then to use it in the `\tocentry` command (`label = SU.stripContentPos(content)` instead of `label = content`).

BTW, having it in the utilities could make it useful for other components (e.g. I'll have to add that to ~~my own labelrefs and~~[^1] resilient.tableofcontents packages; the indexer package might eventually need it too if we make it use a save file too someday).

Any opinion whether this is the right way to avoid that extra warning?

EDIT: Edited the proposal code, a shallow copy isn't needed there.
EDIT2: Re-edited, for I am dumb today ;)

[^1]: Since labelrefs uses the last ToC entry, it's not affected (i.e. it get fixed too if the ToC entries no longer contain positions, without needing anything special.)

**Comment by alerque** [comment]
Yes at least for the ToC package this makes sense. I have some doubts about dropping POS data more generally on info nodes, but the ToC data file use case shouldn't matter.
