### ISSUE TITLE
`--help` flag exits with code `1`

### ISSUE THREAD

**Issue by orhun** [sile-typesetter/sile#1736]
Hello! 🐻 

I'm the author of an open source tool called [halp](https://github.com/orhun/halp) and it is basically responsible for checking the exit codes of common command-line arguments.

Recently one of the users reported that `halp` cannot _discover_ the `--help` option of `sile`: https://github.com/orhun/halp/issues/20

I'm not sure if it is on purpose but it is because `sile --help` returns with code `1` <s>`130` which is CTRL-C / SIGINT.</s>

```sh
$ sile --help
...

$ echo $?
1
```

I'm not fluent in lua so it would take some time for me to dive into the codebase and find the exact place where this happens. Thus I thought it would be best to create an issue and ask about this :3

**Comment by alerque** [comment]
Thanks for reporting this back upstream. (Ve İzmir'den selamlar.)

I'm not able to replicate the 130 exit code. I get 1, which is also arguably wrong but seems to be hard coded into the argument parser library we used when handling help. I can probably fix that, but that doesn't explain the 130 business.

What do you have for `sile --version`?

**Comment by orhun** [comment]
> Thanks for reporting this back upstream. (Ve İzmir'den selamlar.)

Ankara'dan selam olsun 👋🏼

> I'm not able to replicate the 130 exit code. I get 1, which is also arguably wrong but seems to be hard coded into the argument parser library we used when handling help. I can probably fix that, but that doesn't explain the 130 business.

It is weird, I just got `1` as well. I was executing in a chroot before which should affect anything normally but maybe there was some quirks happened in my terminal, don't really know. I will update the issue.
 
Nevertheless, I think it should return `0` instead. It would be so great if you can fix it! :3

> What do you have for `sile --version`?

`SILE v0.14.8 (Lua 5.4)`

**Comment by alerque** [comment]
I have a fix for `1` to be `0`. I can't replicate `130` anywhere (Arch, Nix, Ubuntu, Docker, under Lua, LuaJIT, OpenResty, etc.) so unless anybody can replicate that I'm going to ignore. The 0 return for explicitly calling `--help` should be in the next release.

**Comment by orhun** [comment]
Thank you so much!
