### ISSUE TITLE
Issue 210 regressed, rskip incorrectly carried into footnotes

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1758]
It looks like #210 regressed and the test expectations were incorrectly updated in my merge snafu back in #1216 that shipped as far back as v0.12.0.

**Comment by alerque** [comment]
Per comments in 3795a4e, this is clearly intentional, even though the original test case was expecting different results.

I'd say it's not a clear win either way, but we do need to decide in order to figure out whether #1700 is working or breaking...

@Omikhleia Do you have strong opinions for how this *should* work? Obviously it is badly mixed up in our settings not being properly scoped to frames/typesetters/etc. but we do need to decide if the footnote typesetter follows rskip/lskip from the sending context or not.

**Comment by Omikhleia** [comment]
The (deprecated) "quote" environment should not set the skips at top level, and restore them to nil afterwards (overriding any value they could have before....), but it should have do that in a temporary environment... It's a bad implementation -- and IMHO opinion unrelated to #1700.

**Comment by Omikhleia** [comment]
e.g. if the text was ragged right, and a "quote" is invoked, then back after the text is justified... If "quote" had used a temporary environment, nothing of that sort would have happened, and the footnote test would have worked.

As of whether the footnote typesetter should follow the invoking one regarding the lr skips, it could be debated. But I'd assume that if one sets, say, an infinite rskip globally to have a document ragged right, the footnotes logically should be ragged right too. Maybe :)

**Comment by Omikhleia** [comment]
N.B. We deprecated "quote" here in 0.14.6: #1625
The reasons still do seem good to me.
So we could either:
- remove test 210 since it was using it, and doesn't reveal any real issue nowadays.
- re-implement nested quotes with sound defaults properly. 
    - IMHO In the book class rather than the plain class, because such a thing can have many different implementations...
    - ... I've two implementations, a "simple lame one" as fallback for Markdown quotes (when using the SILE book class, precisely), and a fuller one, but using my styling paradigm, in my resilient.book class.

**Comment by alerque** [comment]
Thanks for helping me reason through this, and I think I agree.

I'm starting to look *forward to* tearing apart our settings scope and just breaking it down to fix right rather than playing whack-a-mole with the latest bugs trying to get out a patch release. Trying to shim compatibility / deprecations is going to be a bear though, perhaps impossible.
