### ISSUE TITLE
DocBook imagedata width unit interpretation

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1767]
The DocBook `imagedata` width conversion is wrong:
https://github.com/sile-typesetter/sile/blob/5bc372ac66174a0cd3c15930a73e20825621e250/classes/docbook.lua#L358

- The default 100%pw is probably dubious (shouldn't it rather be a %fw... or even %lw ?)
- It invokes `parseComplexFrameDimension()` but should rather use a `SILE.measurement()`...
- ... Or should actually have its own parser and interpretation, as "50%" for instance would be legit here (see https://tdg.docbook.org/tdg/5.2/imagedata.html#viewport.area), but would then need to be interpreted in terms of %pw, %fw or %lw for SILE to get it right :cat:

**Comment by alerque** [comment]
Docbook image sizing is dubious.

I've changed this all up to be closer to docbook specs, with the assumption that the "viewport" size corresponds more to the line width than the page size, and that images without sizes are to be printed at 300 DPI. Neither assumption is anything but an arbitrary guess at intent.
