### ISSUE TITLE
Weird line spacing in SILE manual 0.14.9

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1782]
It seems we have introduced a small regression somewhere, see image below.

... Or the issue was present, but not apparent? Commenting this line, the issue "disappears":

https://github.com/sile-typesetter/sile/blob/5c9805b8bc9ccf2e1dfdf0971818664333c75165/packages/linespacing/init.lua#L97-L99

Maybe another edge-case of multiple instantiation / partial instantiation? (#1531) 

![image](https://user-images.githubusercontent.com/18075640/232131079-7a75d26b-6eb3-47c7-9d94-36826434a696.png)

**Comment by alerque** [comment]
this bisects to 0f6c1c53b. I'm guessing @ctrlcctrlv was trying to test changes to the manual by building one chapter at a time, but ya importing the macros twice isn't going to do nice things, especially for relative measurements.
