### ISSUE TITLE
My document shows repeated ToC entries?

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1787]
It's a monster of a document.

https://github.com/ctrlcctrlv/OkinawanKanaUnicodePaper/blob/12067562103f47908e58468a19d9d3648a1af327/okana.sil

Junk PDF output: https://github.com/ctrlcctrlv/OkinawanKanaUnicodePaper/blob/12067562103f47908e58468a19d9d3648a1af327/okana.pdf

![Screenshot_20230419_171049](https://user-images.githubusercontent.com/838783/233201432-050d3990-3280-4960-9e1b-7ca085bd029d.png)

To be clear that repetition is not intended nor in the text. :thinking:

**Comment by ctrlcctrlv** [comment]
Good work on \ptable{} though @Omikhleia 
![Screenshot_20230419_175945](https://user-images.githubusercontent.com/838783/233209411-65d6eaa9-b58f-45e6-985d-767d3e7d302f.png)

**Comment by Omikhleia** [comment]
"I don't even know where to begin to untangle it"

Step One:
1. The document uses non-standard packages/scripts (lists, highlight, etc.) and does weird things (e.g. re-defining `\tocentry` at one point). Try simplifying. I removed them all for a check, replacing needed commands by a no-operation... (Hopefully it's not a 300-page monster document)
1. The document needs several fonts and lots of images. Try simplifying. I removed them all for a check...
1. Then try removing tables and simplifying from the end. Surely you can reduce the document to a MWE with less things... I did that too...

Then indeed, with a much simpler document to work with, there are repetitions in the ToC... Time for Step Two:

1. Your document is using the book class, which does already come with table of contents support. Why are you re-loading the **tableofcontents** package explicitly? Try removing the extra re-loading....

Er. Re-running for a check. Wait. **Repetition problem solved**. Yay.

**Conclusion**: remove the `\script[src=packages/tableofcontents]` line, the book class already does it for you.

... And so, indeed, another case where multiple package instantiation causes havoc = Known issue #1531. This issue annoys me so much that I went on killing those multiple instantiation in my own uses (and e.g. in my resilient classes). But, heh...

Other unrelated notes:
1. Regarding "Good work on \ptable{} though @Omikhleia" -- Well thanks for the congratulation, although it seems this document uses "legacy" simple tables, so I had no part here ^^ ;)
1. That EB Garamond font looks pretty cool :)

**Comment by ctrlcctrlv** [comment]
Oh no you did have a part in my master I migrated it :D
