### ISSUE TITLE
Pullquote note boxes in manual have uneven margins

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1817]
The new note box style is doubling up on parindent: once is being used as lskip and then again for parindent inside the note. The result is off balance: the lskip and rskip don't match.

I think either the rskip should be increased to match or the lskip removed. Also parindent should probably be suppressed at the start of notes.

![20230603_01h17m37s_grim](https://github.com/sile-typesetter/sile/assets/173595/f6bce48c-a7ba-404d-9494-42906468665f)

**Comment by Omikhleia** [comment]
The are a few notes inside bulleted lists - so some lskip is needed there (at least the same amount of left skip). Otherwise it's a matter of taste, I'd say.
