### ISSUE TITLE
foliostyle definition

### ISSUE THREAD

**Issue by leorosa** [sile-typesetter/sile#1820]
Hi,
The folio package provides the 'foliostyle' command, which can be defined in a document to format its pages numbering.
Inside a class, something like `SILE.registerCommand("foliostyle")` used to work, at least in older versions of sile.
But this syntax was deprecated in version 0.14, and using it (or, as suggested, `class:registerCommand`) has no effect on the numbering style.
How can the page numbering for documents be formatted using a custom class in sile's current version? Is it still possible?
Thanks.

**Comment by Omikhleia** [comment]
Showing a working example with a minimal "custom" class:
```
local plain = require("classes.plain")
local class = pl.class(plain)
class._name = "custom"
function class:_init (options)
  plain._init(self, options)
  self:registerCommand("foliostyle", function (_, content)
    SILE.call("em", {}, content) -- or any other formatting!
  end)
end
return class
```
There's a small "trick" here: the override must be done in the custom's class `_init` method, after the full initialization of the parent (here `plain` class) that loads the **folio** package.

In other terms, command overrides from packages loaded by a parent class cannot be done in the child class' `registerCommands()`, as the latter occurs too soon
N.B. I don't know this was intended... but it's understandable to me (= the latter method is only for (new) commands defined by the class); and I've used that trick several times (e.g. my own resilient.book uses it to make commands such as `foliostyle`, `urlstyle` etc. subscribe to my generic styling mechanism)...
Anyhow, perhaps it should be documented somewhere.

**Comment by leorosa** [comment]
Thanks! My mistake was not defining this command in the `_init` method.

**Comment by alerque** [comment]
While functional, I think there is a better solution:

```lua
local plain = require("classes.plain")
local class = pl.class(plain)
class._name = "custom"
function class:_init (options)
  plain._init(self, options)
end
function class:registerCommands ()
  plain.registerCommands(self)
  self:registerPostinit(function ()
    -- Must be loaded after class:loadPackages() has been run
    self:registerCommand("foliostyle", function (_, content)
      SILE.call("em", {}, content) -- or any other formatting!
    end)
  end)
end
return class
```

This should keep the code a bit easier to read because all the command registrations are found in the expected method while also marking the necessity of re-registering that command *after* package load.

**Comment by Omikhleia** [comment]
At the cost of a `self:registerPostinit`. Also somewhat hiding the command overload. I'm not convinced it's better - it's different, but same effect and same code weirdness overall. But it's so far from typography that I'm not going to nitpick about the details.

**Comment by alerque** [comment]
True points. The cost is mostly code complexity not speed though. I bet you couldn't even get tooling to come up with a speed difference due to the way Lua handles closures. Personally I prefer the more verbose code to keep things where my brain logically expects them.

Honestly using commands like this for styling hooks while also using them to provide the default action was always kind of a hack.

The other thing I do in many of my projects is provide both a class *and* a related package and use the class to override things provided by the parent class and using the package to provide overrides to things provided by other packages. Just another way to skin the cat and try to keep some sense to the code.
