### ISSUE TITLE
Old version of Penlight in Ubuntu PPA

### ISSUE THREAD

**Issue by celtic-coder** [sile-typesetter/sile#1825]
Hi Caleb (@alerque),

I recently installed both the SILE Typesetter and "markdown.sile" in WSL (Ubuntu 22.04.2 LTS) on Windows 10. I attempted to create a PDF from one of the example Markdown files, but got a Penlight math "kpairs" error as noted in the https://github.com/Omikhleia/markdown.sile/issues/78 issue.

Didier (@Omikhleia) did some troubleshooting and asked me to check the version of Penlight installed on my system. I had used the Ubuntu PPA to install the SILE Typesetter and the version of Penlight installed was _1.12.0_. The version on his system was _1.13.1_.

It turns out that the failing math "utils.kpairs" functionality was added to the Lunarmodules Penlight by commit https://github.com/lunarmodules/Penlight/pull/413/commits/db77fb88fe3ac258f3a30bfe9192b1f9fd62856c back in February 2022, which was **after** the _1.12.0_ release.

The last update of Penlight for the SILE Typesetter on [Launchpad](https://code.launchpad.net/~sile-typesetter/lua-penlight/packaging) was on 2022-10-24, but uses version _1.12.0_ as noted by these lines from my installation log:

```
Selecting previously unselected package lua-penlight:amd64.
Preparing to unpack .../09-lua-penlight_1.12.0-2ppa1~ubuntu22.04_amd64.deb ...
Unpacking lua-penlight:amd64 (1.12.0-2ppa1~ubuntu22.04) ...
```

_**Note**_: The latest version of Penlight on Launchpad is [1.13.1-3](https://launchpad.net/ubuntu/+source/lua-penlight/1.13.1-3), the Lunar Lobster (current stable release), and was updated on 2022-12-13.

I resolved my own particular PDF generation problem (using "markdown.sile") by updating Penlight to the latest version via Luarocks. However, other users who might need the "utils.kpairs" functionality will be hampered by the version currently available in the PPA.

Might you be able to update the Ubuntu PPA at some time, so that it includes the latest version of Penlight?

Kind Regards,
Liam

**Comment by alerque** [comment]
I can bump the Penlight version in the PPA. We need to supply it there overriding the Ubuntu ones because for older versions of Ubuntu their packaged version is too old for SILE.

**Comment by celtic-coder** [comment]
Great - thanks Caleb! (@alerque) 👍

**Comment by alerque** [comment]
For a little tiny Lua library that takes about 10 seconds to build/install with LuaRocks or even less with a distro package manger, bumping packages for it across a bunch of Ubuntu releases is a somewhat larger operation: hundreds of gigs of LXC images, several days for system update scripts to run across them all before packages will even build, then bumps and builds of the actual packages, then sending them to the PPA for rebuilding the same.

Anywhoo that last step is queued up now and assuming the PPA builders don't fail at the 11th hour packages should be updated in the PPA when their caches clear.

**Comment by celtic-coder** [comment]
Hi Caleb (@alerque),

Given my past experience in the corporate IT world (I am now retired), I can appreciate that system updates are never "simple". Thanks for the effort in getting this sorted!

Kind Regards,
Liam
