### ISSUE TITLE
SILE 0.14.10 cannot properly include a file with same base name as the master file.

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1833]
SILE 0.14.10 cannot properly `\include` a file with same base name as the master file.
It used to work in 0.14.9  and earlier.

MWE with a markdown file (my own initial full case was using an XML file and a much longer SIL wrapper) follows.

Main SIL file `myfile.sil`:

```
\begin{document}
\use[module=packages.markdown]
\include[src=myfile.md]
\end{document}
```

Included markdown file `myfile.md`:

```
_Hello world_
```

Expected: The markdown file (or resp. XML etc.) is included with appropriate inputter.

Observed: The inputter is not triggered and the file is included as SIL.
That's even the case if we enforce `format=markdown` on the `\include`

Analysis:
The "detection" bypass is here -- indeed ignoring file extension.

https://github.com/sile-typesetter/sile/blob/83d142305846800bb5121b13f0a626e3f205dba3/core/sile.lua#L294-L295

Introduced by #1738

Workaround:
Well don't use files with same base names but different extensions in your project... That's confusing though!

**Comment by alerque** [comment]
Hmm, if memory serves me that hack was so that you could have a file with any extension and explicitly process it with any specific inputer, but something is sideways ... that's not *where* that hack needs to be.

**Comment by simoncozens** [comment]
Sorry, yeah, that was a mistake. Too much TeX influence.
