### ISSUE TITLE
Running sile in a directory with lua files causes it to crash

### ISSUE THREAD

**Issue by hegjon** [sile-typesetter/sile#1836]
```
jonny in ~
❯ pwd
/home/jonny

jonny in ~
❯ /usr/bin/sile --version
SILE v0.14.10 (Lua 5.4)

jonny in ~
❯ cd tmp/

jonny in ~/tmp via ☕ v17.0.7 via  v16.14.0 via 🦀 v1.59.0
❯ /usr/bin/sile --version
/usr/bin/lua: error loading module 'cassowary' from file './cassowary.lua':
	cannot read ./cassowary.lua: Is a directory
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	/usr/share/sile/core/frameparser.lua:2: in main chunk
	[C]: in function 'require'
	/usr/share/sile/core/sile.lua:87: in main chunk
	[C]: in function 'require'
	/usr/bin/sile:22: in main chunk
	[C]: in ?

jonny in ~/tmp via ☕ v17.0.7 via  v16.14.0 via 🦀 v1.59.0
❯ ls *cassowary*
 lua-cassowary-2.3.2-1.fc36.noarch.rpm   lua-cassowary-2.3.2-1.fc36.src.rpm

cassowary.lua:
 cassowary   cassowary-scm-0.rockspec   LICENSE   README.md   rockspecs   spec
```

**Comment by hegjon** [comment]
> I'm happy to consider what use case we actually should provide for if there is one.

My use case was just a smoke test of the new version installed via RPM.

I have a `~/tmp/` folder with lots of random files laying around. So without thinking I wanted to run `echo -n '\document{foo}' | /usr/bin/sile - -o foo.pdf` inside of `~/tmp/`.

It's up to you to see this as a bug or a feature.

**Comment by hegjon** [comment]
The `cassowary.lua` folder probably stems from a `git clone` a while ago

**Comment by alerque** [comment]
I hadn't even considered the use case @Omikhleia just mentioned, but I do use projects where the project root provides libraries and the SILE sources are in an assortment of subfolders. I don't see how we can both provide that kind of power/flexibility *and* not trip up if you do something like provide a directory named what we need that also isn't valid for loading that thing.

**Comment by hegjon** [comment]
> Unsure what you are aiming at or if I really understand the point

Running `sile --version` in a folder containing a folder with a wrong name will confuse a lot of end-users when it crashes.

I thought `LUA_PATH` was used for situations like this.

**Comment by Omikhleia** [comment]
> I thought LUA_PATH was used for situations like this.

Might be tricky to set well when running SILE (in various versions and changes) from various custom docker images...
I dunno. Does it really confuse "lot of users" running sile in random places of their OS with conflicting files there?

**Comment by hegjon** [comment]
> I dunno. Does it really confuse "lot of users" running sile in random places of their OS with conflicting files there?

It confused me when I did quick smoke test. I first assumed that I did something wrong in the RPM package for Fedora Linux.

**Comment by alerque** [comment]
If this ever comes up again or anybody comes along with a concrete suggestion of how to make it better without taking away established workflows I'll be happy to reconsider, but I'm pretty sure no change is warranted here. We've mucked with `package.path` sooooo ... manyyyyyy ... tiiiiimes. I know it isn't ideal for everybody but there are trade offs to consider with the way Lua handles modules and I think we have a nice balance now.

We could completely override it and not have it follow it's usual patters, but that cuts us off from system installed LuaRocks, etc. We can change the order, but that gives people a lot less control over customizing things. Running in Docker containers and CI add more issues with what users can reach into and change. I'm reasonably sure the situation you ran into is limited to git clones of a handful of dependencies being found in the CWD, which I don't think is going to happen to many beginners.
