### ISSUE TITLE
SU.deprecated issue after we reached 0.14.10

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1840]
SILE 0.14.10 no longer warns/errors on some deprecations:
```
SU.deprecated("\\quote", "\\pullquote", "0.14.5", "0.16.0") -- prints nothing now!
```

Due to performing a mere string comparison.

**Comment by alerque** [comment]
Yuck. I actually hadn't realized we weren't doing actual semver comparisons there. I agree a utility function to do so (split on dots, then compare segment by segment starting at the left) would be in order.

**Comment by alerque** [comment]
I'm always reluctant to add dependencies, but I think adding [semver](https://github.com/kikito/semver.lua) might serve us well. I've been starting to be bothered by the assortment of versions of 3rd party packages (including my own) and how they affect my projects. Reproducible builds right now basically means keeping around the right Docker container with all the dependencies preloaded. I would like to be at the point where something akin to our current `-d versions` output would include version data on the packages used like it does for fonts and system libraries now, and something like that could be made into a manifest used to build an environment that could rebuild the project properly even in the event of new upstream releases with breaking changes.

**Comment by Omikhleia** [comment]
> Alternatively we could fake it for the rest of the current release cycle (...)

FWIW, here is what I'm using in my compatibility layer:
https://github.com/Omikhleia/silex.sile/blob/42462c30a7c975f4529afecf8beca16a1f907782/silex/compat.lua#L3-L39

**Comment by alerque** [comment]
I'm tempted by the shim, but I think I'm actually going to take this down the dependency route. I actually want to work on making sure our LuaRocks handling is easy and robust and feel at where we are at with that downstream. We have some pain points like the Ubuntu PPA needing me to package it separately, but at the end of the day if pure Lua Rocks are a problem for us we're probably doing something wrong.

**Comment by alerque** [comment]
I'm going to backtrack this. WE're in a minor release cycle and adding new dependencies is not friendly to downstream packagers and might delay rollout more than necessary. For the next major version if we have Rust anyway we will probably be able to provide a robust parser using an external library at no cost to packagers. Since it turns out our development versions aren't even using semver correctly and we'd have to pre-parse to smooth that out, I think I'll just rip off the hacked version and make it a shim for now.
