### ISSUE TITLE
Lua 5.4 undefined symbol _gettop

### ISSUE THREAD

**Issue by meerfrau** [sile-typesetter/sile#1874]
I've built sile _develop_ against lua 5.4:
```
    export RUSTUP_TOOLCHAIN=stable
    export CARGO_TARGET_DIR=target
    ./configure \
        --prefix /usr \
        --docdir /usr/share/doc/$pkgname \
        --with-system-luarocks
    make all
```
Result:
```
Error: runtime error: error loading module 'lua-utf8' from file '/usr/lib/lua/5.4/lua-utf8.so':
	/usr/lib/lua/5.4/lua-utf8.so: undefined symbol: lua_gettop
stack traceback:
	[C]: in ?
	[C]: in ?
	[C]: in function 'require'
	/usr/share/sile/core/sile.lua:24: in main chunk
	[C]: in function 'require'
	[string "src/lib.rs:13:10"]:1: in main chunk
```

**Comment by alerque** [comment]
I've run into several unexpected results in the new *develop* branch having exposed it to an assortment of systems in the last few hours. Picking the right Lua *and* package paths to match a system Lua even when you're actually using an internal VM is a bit tricky. Most of my problems have been with the `package.path` though, I haven't seen this one.

This looks like you've adapted the build from the Arch Linux PKGBUILD for sile-git, no? Can you can confirm a couple things for me?

```console
# List of lua packages installed:
$ pacman -Qqs lua | grep '^lua'

# Actual result of detected Lua version, run after your `./configure`:
$ grep MLUAVER Makefile
```

**Comment by alerque** [comment]
Don't worry about the extra info, I found a scenario that gives me similar result. My error is slightly different (`lua_callk` instead of `lua_gottop`) but close enough that I assume it is the same root cause. I'm working on making the new Rust build robust enough to handle different systems with different Lua setups.

**Comment by alerque** [comment]
I take that back, my case is not really useful and debug information from your setup would help. My case was using `cargo run --features luajit` after having `./configure --without-luajit`, or vise versa. That mixmatch is not supported anyway, so we're back to trying to sort up what scenario you ran into and how to resolve it...

**Comment by meerfrau** [comment]
ArchLinux user, adopted your PKGBUILD indeed!
Lua packages:
```
lua
lua-bit32
lua-busted
lua-cassowary
lua-cjson
lua-cldr
lua-cliargs
lua-cosmo
lua-dkjson
lua-expat
lua-filesystem
lua-fluent
lua-linenoise
lua-loadkit
lua-lpeg
lua-luaepnf
lua-luarepl
lua-luassert
lua-luautf8
lua-mediator
lua-penlight
lua-say
lua-sec
lua-socket
lua-stdlib
lua-system
lua-term
lua-vstruct
lua-zlib
luajit
luarocks
```

**Comment by alerque** [comment]
And the output of `grep MLUAVER Makefile` from the SILE source directory after you finish your configure?

**Comment by alerque** [comment]
The develop branch *defaults* to `--with-luajit`. You're also configuring `--with-system-luarocks` but all the packages you have installed on your system are for Lua 5.4. You need to either use `--without-luajit` or install the `lua51-*` variant of SILE's dependencies. Something like this should do the trick for the latter option:

```console
$ pacman --needed -S glibc fontconfig freetype2 harfbuzz gentium-plus-font git icu libpng luajit lua51-cassowary lua51-cldr lua51-cliargs lua51-compat53 lua51-expat lua51-filesystem lua51-fluent lua51-linenoise lua51-loadkit lua51-lpeg lua51-luaepnf lua51-luarepl lua51-luautf8 lua51-penlight lua51-sec lua51-socket lua51-vstruct lua51-zlib zlib
```

Of course just adding the `--without-luajit` should work if you are just after a Lua 5.4 based build.

If that doesn't do it for you, please include the output of the commands suggested above so we can look into it farther. I'm pretty sure this is your trouble, but I'm happy to re-open this for review if that info doesn't do it for you.
