### ISSUE TITLE
Alignment problem when using \makecolumns

### ISSUE THREAD

**Issue by jodros** [sile-typesetter/sile#1900]
The right edge of the frames which are bond to the content one doesn't shift as the number of columns increases.

![notaligned](https://github.com/sile-typesetter/sile/assets/15092760/836f920f-59a9-468a-9963-ddec90416ae6)

So I did the following changes:

```lua
  self:registerCommand("makecolumns", function (options, _)
    local aligned = {}
    options.columns = options.columns or 2
    for key in pairs(SILE.frames) do
      -- this must be checked before makecolumns() call, since the function changes the right() value of content
      if SILE.getFrame(key):right() == SILE.getFrame("content"):right() and key ~= "content" then
         table.insert(aligned, key)
      end
    end

    makecolumns(options)

    for _, frame in ipairs(aligned) do
      SILE.getFrame(frame):constrain("right", SILE.getFrame("content_col"..options.columns-1):right())
    end
  end, "Split the current frame into multiple columns")
```
And now they do:

![aligned](https://github.com/sile-typesetter/sile/assets/15092760/8c47493e-90c6-4c1b-b44b-dc5b39a3b2bb)

---

The footnote frame is also overwritten if its top and the bottom of content frame are linked, I know this has more to do with the frameset definition than with the makecolumns method, but I think it worth mentioning...

![footnote](https://github.com/sile-typesetter/sile/assets/15092760/ac7a20ac-8893-4e03-a087-2ddc882420e6)

```sil
\begin[papersize=a5]{document}
\script[src=packages/frametricks]
\script[src=packages/lorem]
\script[src=packages/footnotes]
\makecolumns
\lorem[words=100]
\showframe[id=all]
\footnote{\lorem[words=20]}
\lorem[words=500]
\end{document}
```

But when the bottom of content is set to a constant value, e.g. 80%ph like this, it works well:

![footnote2](https://github.com/sile-typesetter/sile/assets/15092760/1d29c972-95f6-4fa1-948a-c47e57c092ce)

**Comment by alerque** [comment]
It looks like the footnote thing might need adjusting so that "steal from" can act on more than one frame. Also I have a vague recollection about another bug that made insertions act up in a similar way...

**Comment by alerque** [comment]
This isn't the same problem as #420, but it is conceptually related. After tinkering with frames the wiring between them that helps them interact is lost...
