### ISSUE TITLE
Dropcap with descenders introduces uneven lines

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1925]
Ran with docker `siletypesetter/sile:v0.14.13`:

```
\begin[papersize=a6]{document}
\use[module=packages.lorem]
\use[module=packages.dropcaps]
\dropcap[join=true, lines=4]{J}\lorem[words=50]
\end{document}
```

![image](https://github.com/sile-typesetter/sile/assets/18075640/bfe88fb3-90eb-4a16-9b79-49d1785c98aa)

Same issue with a Q.

No font specified, so using default font Gentium Plus -- which happens to have capitals with descenders. Might occur with other fonts, though I wouldn't have noticed used most of the time fancy fonts such as Zalmann Caps ^^ i.e. fonts without descenders.

And it seems indeed that the depth being overlooked or not being taken into account somewhere:

![image](https://github.com/sile-typesetter/sile/assets/18075640/b9ff7f43-1fba-4e4c-a9cd-4b8b667a73b1)

**Comment by Omikhleia** [comment]
> I'm a little surprise this turned up by stretching that first line leading and not by just over-running the space at the bottom and drawing on top of the 5th line.

Same surprise here! My guess is that the first line inherits the depth of the dropped caps, but I haven't checked that code for some time...
1. Scaling the whole glyph (height and depth) is what LibreOffice does, but it doesn't look very nice (that J or Q become much _thinner_ than other dropped capitals. 
2. We could also compute if we'd need another extra hanged lines for these cases, 
     a. but scaling that would make the letter _heavier_ and taking more space horizontally...
     b. ... unless we do not try to change the letter scale (at the risk of having a space below it)
4. Or we could account for an extra hanged line but use PDF scaling (à la "scalebox") to fit in the space vertically. That would avoid the horizontal stretching but will distort the glyph vertically... besides, it's a bit more complex!

I wonder if (2b) is not the best choice (= detect, introduce an extra line, but keep scaling and alignment unchanged, possibly with a warning for visual check)

**Comment by kyrias** [comment]
I _just_ ran into what appears to be the same issue while trying to use the EB Garamond Initials font and was wondering if I was doing something wrong.

![image](https://github.com/sile-typesetter/sile/assets/2285387/9f173eab-b3c1-4fa9-a0c8-5307661c2745)

**Comment by Omikhleia** [comment]
@kyrias Seems to be the same issue, yes (to be real sure you could run SILE with `-d all` and see the red frames around frames and boxes): EB Garamond Initials has _all_ letters, not just J and Q, with descenders below the baseline:

![image](https://github.com/sile-typesetter/sile/assets/18075640/85d2ad92-104c-49f9-8e49-80e0cd5a0923)

Interestingly in such a case, solution 1 would be better than solution 2b... So we _could_ shape, say, a "A" (I wouldn't expect descenders here in most fonts) and if it has a depth, pick solution 1, otherwise pick 2b... Interesting coding example :)

**Comment by Omikhleia** [comment]
(But probably such initials weren't done for dropped capitals in the first case)

**Comment by kyrias** [comment]
Myeah.

![image](https://github.com/sile-typesetter/sile/assets/2285387/0d12198e-2db7-46e1-af25-2fcb9c222830)

---

> 
> (But probably such initials weren't done for dropped capitals in the first place)

Hm, what do you mean?  They come from [this bible](http://www.bvh.univ-tours.fr/Consult/consult.asp?numtable=B372615206%5F18229&numfiche=571&mode=1&ecran=0&offset=15&index=18).

**Comment by Omikhleia** [comment]
> Hm, what do you mean? They come from this bible

I mean the decision to have them encoded, in that font, with such a baseline offset on all characters (or, that is, top-aligned with ascenders, it seems, looking at my image above)... That's kind of neat actually for display at the same point size as the main text, on a single line (as in my image above), but that's sort of unusual (it seems to me). Anyway, it's another case for the general issue. Even some fonts specifically designed for dropped capitals with descenders, e.g. [Ehmcke-Fraktur Initialen Regular](https://www.1001fonts.com/ehmcke-fraktur-initialen-font.html)

**Comment by Omikhleia** [comment]
Self-assigning the issue, unless someone wants to give it a stab?

**Comment by Omikhleia** [comment]
Some fonts have both capitals with descenders _and_ bigger J's:

![image](https://github.com/sile-typesetter/sile/assets/18075640/eb0777fe-8581-44d4-a630-09a4087f1b28)

Would need to test that one lol.
