### ISSUE TITLE
Hyphenation on words joined with hyphen in Polish

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1960]
Rumour has it that in Polish, when a word containing a hyphen is cut at that point, the hyphen must be repeated on the next line -- and that several typesetting systems have unaddressed enhancement requests on that topic:

Typst (issue in 2024): https://github.com/typst/typst/issues/3235
OpenOffice (issue in 2006): https://bz.apache.org/ooo/show_bug.cgi?id=71679

If this typography convention for Polish is correct, then SILE too is currently wrong:

```
\begin[papersize=a5]{document}
\language[main=pl]
\lua{
    for i = 1,100 do
       SILE.typesetter:typeset("biało-czerwony ")
    end
}
\end{document}
```

![image](https://github.com/sile-typesetter/sile/assets/18075640/daf89a4a-a08c-4190-ad4b-c8886a69e538)

Except that it would be a _fairly trivial thing_ to fix... Just a few lines of code, possibly:
(EDIT: Well, a bit more, see PR)

```
-- Put this in languages/pl.lua
SILE.nodeMakers.pl = pl.class(SILE.nodeMakers.unicode)

function SILE.nodeMakers.pl:handleWordBreak (item)
  if item.text == "-" then
    self:addToken(item.text, item)
    self:makeToken()
    coroutine.yield(SILE.nodefactory.discretionary({
      postbreak = SILE.shaper:createNnodes("-", self.options)
    }))
  else
    self._base.handleWordBreak(self, item)
  end
end
```

![image](https://github.com/sile-typesetter/sile/assets/18075640/ad7d99ac-d275-4c52-8259-192103a3b270)

Yay! :smile: 

---

I could make a PR, but the details are in the devil. Here I stack the "-" onto the previous word, and insert a postbreak discretionary. 
But we could also stack the "-" on the next word, or even wholly ignore it (of course, each time using an adequate postbreak/prebreak/replacement discretionary). 

The question at stakes is how is supposed to be hyphenated the first word?

With the above fix, we get bia•ło-•czer•wony (I am marking the hyphenation points with • to distinguish them from the word's hyphen)
... because `SILE.typesetter:typeset(SILE.showHyphenationPoints("biało-, "pl"))` :arrow_right:  bia•ło-

But note that `SILE.showHyphenationPoints("biało", "pl")` :arrow_right:  biało (EDIT: no hyphenation point currently)
... so depending on how we do it, we can get different hyphenations...

It _seems_ to me that bia•ło-•czer•wony might be correct, but we'd need a Polish friend to confirm the expectations :poland: 

EDIT I corrected `SILE.showHyphenationPoints("czerwony", "pl")` :arrow_right:  czer•wony (not czer•wo•ny) with default settings.

**Comment by Omikhleia** [comment]
Perhaps it's not too impolite to ask @jakubkaczor (who opened the Typst issue) on that matter?

**Comment by Omikhleia** [comment]
> If this typography convention for Polish is correct,

Some 2022 (LaTeX) [Babel for Polish](https://tug.ctan.org/language/babel/contrib/polish/polish.pdf) manual also mentions it: "According to Polish rules, when a break occurs at an explicit hyphen, the hyphen gets repeated at the beginning of the new line."

(Of course they "fix" it by requiring the user to typeset some specific markup, with active "catcodes"... _Sigh_.)

**Comment by jakubkaczor** [comment]
It is not impolite at all to ask me. If I understood the question correctly, you wonder whether there should be any hyphenation points in the word between a hyphen if it occurs. I am not knowledgeable enough in the topic, but I can link some sources.

I believe the most common package, and the one I used, for correcting hyphenation in LaTeX is `polski` package. The author provides commands for hyphen (`dywiz`), en-dash (`ppauza`), and em-dash (`pauza`). These are explained in the (english!) [documentation for the package](https://texdoc.org/serve/polski/0). As far as I understand it, the author uses `\kern` to allow hyphenation in words between and after hyphen, so the answer would be: yes, the first word should also be considered for hyphenation. Please, correct me if I am misunderstanding. As far as I am informed, the active author is a professional typographer, member of the [GUST](https://www.gust.org.pl/?set_language=pl) and one of the authors of the [TeX Gyre fonts](https://www.gust.org.pl/projects/e-foundry/tex-gyre).

**Comment by Omikhleia** [comment]
@jakubkaczor Many thanks! Indeed on p. 11 of the document you mentioned: "... allow both parts of the word to be considered
for hyphenation"

That answers my question. (I can't understand the 0-valued kerns in TeX, but whatever, the conclusion is the key.)

**Comment by Omikhleia** [comment]
Editing the issue title:
Apparently also in [Czech](https://tex.stackexchange.com/questions/640446/optex-how-to-repeat-hyphen-on-next-line-when-hyphenating-prehyphenated-words-au)

**Comment by alerque** [comment]
Thanks for looking into this @Omikhleia, and thanks for the feedback @jakubkaczor. This should be working properly in the next patch release. It might even be worth adding an example to the website to showcase this. I could then add an Turkish example too so we have some samples of how atypical hyphenation rules are or can be handled.
