### ISSUE TITLE
Generalize/refactor language-specific discretionary handling

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1966]
With Catalan, we now have another special case, similar to Turkish, of specific discretionary handling in `core/hyphenator-liang.lua`

I would suggest we discuss moving those in some dedicated language-specific classes for handling post-segmentation exceptions. Other noteworthy points
- We should likely cache those discretionary nodes (here below and for Turkish as well), instead of rebuilding them each time they are needed...
- Specific files for these hacks would need to use a language-based filename rather that merely comparing the language string. When supporting qualified BCP47 languages, we may want to distinguish `ca` (canonical Catalan = `ca-ES`) from `ca-FR` (as used in the French Pyrenees)...

_Originally posted by @Omikhleia in https://github.com/sile-typesetter/sile/pull/1964#discussion_r1460863582_

**Comment by alerque** [comment]
The main issue was addressed, but not the subpoints.

* Performance broadly is in #884 and hyphen node memoization is in #1971.

* Language code handling is in #1368 and #1631.
