### ISSUE TITLE
Support parts above chapters

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#207]
As clumsy as the LaTeX paradigm of using _Chapter_ as the top level sectioning only in the absence of _Part_ breaks—in which case _Part_ becomes the top level sectioning—is crazy, the reality is this is a common issue with books. Most books just have chapters and work down from there—except for the ones that also have parts.

This is easy enough to build into a custom class, but supporting `\part` out of the box in the `book` class would make life a lot easier and keep people from re-inventing the wheel.

**Comment by Omikhleia** [comment]
Duplicating #601 which was opened later but has more details.
