### ISSUE TITLE
Bibliography: support CSL?

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#2074]
Some of the issues regarding bibliographies (eg. #2027, #2049) are hampered by the fact that SILE has it's own-made Chicago style implementation. I know of at least one similar attempt at implementing another style on the same grounds (@jodros 's [ABNT](https://github.com/jodros/abnt.sile/blob/main/packages/bibtex/styles/abnt.lua))

Question 1. What would be SILE's position on deprecating these hand-made styles, and switch to CSL?

 - Proper localization is provided by [CSL locales](https://github.com/citation-style-language/locales)
 - Lots of standard styles have a [CSL implementation](https://github.com/citation-style-language/styles), incl. various versions of the Chicago style.

Question 2. Would SILE be ok with its own implementation of (a decent subset) of CSL in Lua?
 
 - CSL is not that hard of a schema (compared, say, to USX and all its implications (#1398)...
 - The alternative is to use an existing CSL processor (but it is not that easier to hook back into SILE and it's far less fun IMHO)

**Comment by Omikhleia** [comment]
Note on license issue: CSL local and styles files are CC-BY-SA.
AKAIK, it means we can't just vendor them with SILE (MIT) -- but submodules, or a build dependency, could be acceptable.

**Comment by jodros** [comment]
> I know of at least one similar attempt at implementing another style on the same grounds (@jodros 's [ABNT](https://github.com/jodros/abnt.sile/blob/main/packages/bibtex/styles/abnt.lua))

That file is only a draft, since I din't understand well how to use...

BTW I'm glad to see that a refactor of bibliography is underway, I hope I can help.

**Comment by Omikhleia** [comment]
Self-assigning: I'm experimenting a CSL engine (the 80% easy are reached, the question is how to get the 20% difficult right, lol).
(Just for you to know -- It might take a bit of time, and the points raised above are valid however this goes)

**Comment by Omikhleia** [comment]
_Teaser._

Our legacy Chicago style vs. CSL "author-date" Chicago style for the exact same bibtex entry...

![image](https://github.com/sile-typesetter/sile/assets/18075640/b755bcef-4985-43c9-b073-e4dc06d37a22)

**Comment by Omikhleia** [comment]
_Teaser no. 2_

Same bibtex entry, but French CSL locale and French "author-date" Chicago CSL style. Yay, honoring gender for the ordinals :)

![image](https://github.com/sile-typesetter/sile/assets/18075640/4cfdacf3-eb7e-482b-afbf-afa7db3bce10)
