### ISSUE TITLE
Lua 5.4 contains broken package on NixOS

### ISSUE THREAD

**Issue by victorklos** [sile-typesetter/sile#2090]
Tested on both 0.15.3 and 0.15.4:

<details>
❯ RUST_BACKTRACE=full sile

thread 'main' panicked at src/lib.rs:63:44:

called `Result::unwrap()` on an `Err` value:
RuntimeError("...a6-sile-0.15.3-6404c53-flake/share/sile/core/globals.lua:10: module
'pl.import_into' not found:\n\tno field package.preload['pl.import_into']\n\tno file
'./sile/pl/import_into.lua'\n\tno file './sile/pl/import_into/init.lua'\n\tno file
'./pl/import_into.lua'\n\tno file './pl/import_into/init.lua'\n\tno file
'./lua_modules/share/lua/5.1/sile/pl/import_into.lua'\n\tno file
'./lua_modules/share/lua/5.1/sile/pl/import_into/init.lua'\n\tno file
'./lua_modules/share/lua/5.1/pl/import_into.lua'\n\tno file
'./lua_modules/share/lua/5.1/pl/import_into/init.lua'\n\tno file
'=[C]/sile/pl/import_into.lua'\n\tno file '=[C]/sile/pl/import_into/init.lua'\n\tno file
'=[C]/pl/import_into.lua'\n\tno file '=[C]/pl/import_into/init.lua'\n\tno file
'=[C]/lua_modules/share/lua/5.1/sile/pl/import_into.lua'\n\tno file
'=[C]/lua_modules/share/lua/5.1/sile/pl/import_into/init.lua'\n\tno file
'=[C]/lua_modules/share/lua/5.1/pl/import_into.lua'\n\tno file
'=[C]/lua_modules/share/lua/5.1/pl/import_into/init.lua'\n\tno file
'/nix/store/3blg5i89c0kr6wy5xp4rk6di1pim2n78-luarocks-nix-0-unstable-2024-04-29/share/lua/5.4/sile/pl/import_into.lua'\n\tno
file
'/nix/store/3blg5i89c0kr6wy5xp4rk6di1pim2n78-luarocks-nix-0-unstable-2024-04-29/share/lua/5.4/sile/pl/import_into/init.lua'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/lib/sile/lua-libraries/pl/import_into.lua'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/lib/sile/lua-libraries/pl/import_into/init.lua'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/lib/sile/pl/import_into.lua'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/lib/sile/pl/import_into/init.lua'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/lib/sile/lua_modules/share/lua/5.1/sile/pl/import_into.lua'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/lib/sile/lua_modules/share/lua/5.1/sile/pl/import_into/init.lua'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/lib/sile/lua_modules/share/lua/5.1/pl/import_into.lua'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/lib/sile/lua_modules/share/lua/5.1/pl/import_into/init.lua'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/share/sile/lua-libraries/pl/import_into.lua'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/share/sile/lua-libraries/pl/import_into/init.lua'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/share/sile/pl/import_into.lua'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/share/sile/pl/import_into/init.lua'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/share/sile/lua_modules/share/lua/5.1/sile/pl/import_into.lua'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/share/sile/lua_modules/share/lua/5.1/sile/pl/import_into/init.lua'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/share/sile/lua_modules/share/lua/5.1/pl/import_into.lua'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/share/sile/lua_modules/share/lua/5.1/pl/import_into/init.lua'\n\tno
file
'/nix/store/3blg5i89c0kr6wy5xp4rk6di1pim2n78-luarocks-nix-0-unstable-2024-04-29/share/lua/5.4/pl/import_into.lua'\n\tno
file
'/nix/store/3blg5i89c0kr6wy5xp4rk6di1pim2n78-luarocks-nix-0-unstable-2024-04-29/share/lua/5.4/pl/import_into/init.lua'\n\tno
file './justenough/.libs/pl/import_into.so'\n\tno file './libtexpdf/.libs/pl/import_into.so'\n\tno
file './sile/pl/import_into.so'\n\tno file './pl/import_into.so'\n\tno file
'./lua_modules/lib/lua/5.1/sile/pl/import_into.so'\n\tno file
'./lua_modules/lib/lua/5.1/pl/import_into.so'\n\tno file
'=[C]/justenough/.libs/pl/import_into.so'\n\tno file '=[C]/libtexpdf/.libs/pl/import_into.so'\n\tno
file '=[C]/sile/pl/import_into.so'\n\tno file '=[C]/pl/import_into.so'\n\tno file
'=[C]/lua_modules/lib/lua/5.1/sile/pl/import_into.so'\n\tno file
'=[C]/lua_modules/lib/lua/5.1/pl/import_into.so'\n\tno file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/lib/sile/justenough/.libs/pl/import_into.so'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/lib/sile/libtexpdf/.libs/pl/import_into.so'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/lib/sile/pl/import_into.so'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/lib/sile/lua_modules/lib/lua/5.1/sile/pl/import_into.so'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/lib/sile/lua_modules/lib/lua/5.1/pl/import_into.so'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/share/sile/justenough/.libs/pl/import_into.so'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/share/sile/libtexpdf/.libs/pl/import_into.so'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/share/sile/pl/import_into.so'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/share/sile/lua_modules/lib/lua/5.1/sile/pl/import_into.so'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/share/sile/lua_modules/lib/lua/5.1/pl/import_into.so'\n\tno
file './justenough/.libs/pl.so'\n\tno file './libtexpdf/.libs/pl.so'\n\tno file './sile/pl.so'\n\tno
file './pl.so'\n\tno file './lua_modules/lib/lua/5.1/sile/pl.so'\n\tno file
'./lua_modules/lib/lua/5.1/pl.so'\n\tno file '=[C]/justenough/.libs/pl.so'\n\tno file
'=[C]/libtexpdf/.libs/pl.so'\n\tno file '=[C]/sile/pl.so'\n\tno file '=[C]/pl.so'\n\tno file
'=[C]/lua_modules/lib/lua/5.1/sile/pl.so'\n\tno file '=[C]/lua_modules/lib/lua/5.1/pl.so'\n\tno file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/lib/sile/justenough/.libs/pl.so'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/lib/sile/libtexpdf/.libs/pl.so'\n\tno
file '/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/lib/sile/pl.so'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/lib/sile/lua_modules/lib/lua/5.1/sile/pl.so'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/lib/sile/lua_modules/lib/lua/5.1/pl.so'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/share/sile/justenough/.libs/pl.so'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/share/sile/libtexpdf/.libs/pl.so'\n\tno
file '/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/share/sile/pl.so'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/share/sile/lua_modules/lib/lua/5.1/sile/pl.so'\n\tno
file
'/nix/store/4x4q6xw319xr5p997hj94wsf027jida6-sile-0.15.3-6404c53-flake/share/sile/lua_modules/lib/lua/5.1/pl.so'\nstack
traceback:\n\t[C]: in ?\n\t[C]: in function
'require'\n\t...a6-sile-0.15.3-6404c53-flake/share/sile/core/globals.lua:10: in main chunk\n\t[C]:
in function 'require'\n\t...jida6-sile-0.15.3-6404c53-flake/share/sile/core/sile.lua:8: in main
chunk\n\t[C]: in function 'require'")

stack backtrace:
   0:     0x55808bc9fc79 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4886110ae7835fd2
   1:     0x55808bc4f790 - core::fmt::write::h6fab83f0f5bc0c8f
   2:     0x55808bcb452d - std::io::Write::write_fmt::h64824cb874054607
   3:     0x55808bca0628 - std::sys_common::backtrace::print::hb8fea9d041077138
   4:     0x55808bca0443 - std::panicking::default_hook::{{closure}}::hc60f0f690c67943c
   5:     0x55808bca0dc3 - std::panicking::rust_panic_with_hook::hd61e30fe5971d187
   6:     0x55808bca0890 - std::panicking::begin_panic_handler::{{closure}}::h95d2684e28f89fd2
   7:     0x55808bca07e6 - std::sys_common::backtrace::__rust_end_short_backtrace::h48780d898316fff8
   8:     0x55808bca07d3 - rust_begin_unwind
   9:     0x55808bbea964 - core::panicking::panic_fmt::hdb89b5c14a056cec
  10:     0x55808bbea922 - core::result::unwrap_failed::h850510ea6c159887
  11:     0x55808bc7ebf0 - sile::load_sile::h87cadcb27a6436de
  12:     0x55808bbeff35 - sile::main::h454e62bcba99b25f
  13:     0x55808bbee813 - std::sys_common::backtrace::__rust_begin_short_backtrace::hde6e446c33ab98d9
  14:     0x55808bbf4fdc - main
  15:     0x7fb3ae82810e - __libc_start_call_main
  16:     0x7fb3ae8281c9 - __libc_start_main@@GLIBC_2.34
  17:     0x55808bbee6c5 - _start
  18:                0x0 - <unknown>
</details>

I am on NixOS using a flake (see below). In both cases, `sile-lua` runs just fine.

The flake loads `sile.packages.${system}.sile-lua5_4`, but from the logging it is clear that some files that are referenced are from lua 5.1. Am I doing something wrong?

This is my flake, invoked from `direnv`:

```
{
  description = "Flake with a shell to use sile in its latest version";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    sile.url = "github:sile-typesetter/sile/v0.15.3";
  };

  outputs = { nixpkgs, flake-utils, sile, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        sile-app = sile.packages.${system}.sile-lua5_4;
      in
      {
        devShells.default = pkgs.mkShell {
          packages = [ pkgs.lua54Packages.luarocks-nix sile-app ];
        };
      });
}
```

**Comment by victorklos** [comment]
Ah my computer is so fast I didn't notice this error earlier:

    error: Package ‘lua5.4-markdown-0.33-1’ in /nix/store/s1aj0acgjnl4h91yz1gm1bdq2y9196l2-source/pkgs/development/lua-modules/generated-packages.nix:2388 is marked as broken, refusing to evaluate

Changing to lua5_3 fixes it.

**Comment by victorklos** [comment]
So the `markdown` package for Lua 5.4 on NixOS is marked broken, making the flake refusing to evaluate by default. Maybe you can `allowBroken` in your own flake?

**Comment by Omikhleia** [comment]
AFAIK, there's nothing in SILE depending on this `lua5.4-markdown-0.33-1` module so I wonder where the dependency comes from. Are you sure it's a SILE issue?

**Comment by victorklos** [comment]
Oops, removing the `luarocks-nix` package solved this. Sorry!

**Comment by alerque** [comment]
Glad you got it sorted.
