### ISSUE TITLE
Detect cross compilation and adjust Cargo output directory

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#2099]
Cross compiling with Cargo adds a segment to the output directory with the host info. Currently we don't have a way to detect this and adjust, we just blindly assume the Cargo directory will be "target/release" instead of perhaps "target/x86_64-unknown-linux-gnu/release".

This is a problem for some distro packages, e.g. [Void bumped into this](https://github.com/void-linux/void-packages/pull/51222#pullrequestreview-2273484297).

Somehow we should detect whether cross compilation is being used and what the target triple is.

**Comment by alerque** [comment]
@Luciogi Any hints on how Void's build system is initializing cross compilation? Are you using the `--host <target>` configure option or env vars or what?

I think what I did in #2178 will address this by *always* building into a target directory with the target triple specified, hence not needing the patch you setup. But I'm not 100% sure this will cover all cases. I'd be happy to test some more if I know more about the scenarios where this is an issue.

**Comment by Luciogi** [comment]
I am not completely familiar with xbps-src internal functions.
Following will be my guess.

sile - template uses
```
build-style=gnu-configure
build-helper=rust
```
as problem is with rust output binary location, 
xbps-src loads this script before compiling 
https://github.com/void-linux/void-packages/blob/master/common/build-helper/rust.sh
https://github.com/void-linux/void-packages/blob/master/common/build-style/gnu-configure.sh
