### ISSUE TITLE
AST differences between begin-end and command syntax

### ISSUE THREAD

**Issue by davidchisnall** [sile-typesetter/sile#2106]
According to the documentation, the following should be equivalent:

Option 1:

```tex
\itemize{
	\item{Item 1}
	\item{Item 2}
}
```

Option 2:

```tex
\begin{itemize}
	\item{Item 1}
	\item{Item 2}
\end{itemize}
```

Option 3:

```xml
<itemize>
	<item>Item 1</item>
	<item>Item 2</item>
</itemize>
```

Indeed, options 2 and 3 provide identical output.  Option 1; however, crashes sile:

```sh
SILE v0.14.17 (Lua 5.4)
<test.sil> as sil

! Unexpected Lua error

error summary:
	Processing at: test.sil:2:2: in \itemize
	Using code at: ...Cellar/sile/0.14.17_1/share/sile/packages/lists/init.lua:76: attempt to concatenate a nil value (local 'cmd')

Run with --traceback for more detailed trace leading up to errors.
```

Full test case:

```tex
\document[class=book]{\use[module=packages.lists]
\itemize{
	\item{Item 1}
	\item{Item 2}
}
}
```

Full working version:

```tex
\document[class=book]{\use[module=packages.lists]

\begin{itemize}
	\item{Item 1}
	\item{Item 2}
\end{itemize}
}
```

**Comment by alerque** [comment]
Something is amiss, and I'll look into it, but it seems the problem is with the `\document{}` at the top level, not with `\itemize{}`, so your option 1 works too but just not when nested in a command form (as opposed to block form) of a document:

```sile
\begin[class=book]{document}
\use[module=packages.lists]
\itemize{
	\item{Item 1}
	\item{Item 2}
}
\end{document}
```

**Comment by Omikhleia** [comment]
The variant with `\document{...}` generates `id = "content"` in the AST, the other with `\begin{document} ` does not. (In other terms, begin-end groups and commands do not generate the same AST.

**Comment by alerque** [comment]
Yes. I just came to the same conclusion myself — and it's the same in v0.14 and v0.15. That doesn't feel right, they should be interchangeable. An `XML` variant or other inputter should also be able to generate an identical AST.

**Comment by Omikhleia** [comment]
I wouldn't consider the issue critical though, as there are workarounds (use begin-end constructs in the cases!), but it would be nice to get rid of this "SIL parsing artifact" item (the `texlike_stuff` > `content` id nodes),  I assume?

**Comment by Omikhleia** [comment]
I'm on it. An occasion to check something from an old discussion.
