### ISSUE TITLE
Wrong position of sub/superscripts in math on big content

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#2122]
**Observed**
 (the square root comes from #2119, but this is orthogonal to the issue)

![image](https://github.com/user-attachments/assets/c4237c80-01a2-4759-b211-2d61140f2836)
![image](https://github.com/user-attachments/assets/7551db12-272a-4c7f-a51f-3182aed64e41)

The exponents on "big" blocks (bracketed blocs with fractions, etc.) are really off.

**Note**

There's some commented out code in our implementation, let's check what restoring it does:

```diff
diff --git a/packages/math/base-elements.lua b/packages/math/base-elements.lua
index ea58071e..18af78cb 100644
--- a/packages/math/base-elements.lua
+++ b/packages/math/base-elements.lua
@@ -610,7 +610,7 @@ function elements.subscript:shape ()
       self.sub.relX = self.width + subShift
       self.sub.relY = SILE.types.length(math.max(
          constants.subscriptShiftDown * scaleDown,
-         --self.base.depth + constants.subscriptBaselineDropMin * scaleDown,
+         (self.base.depth + constants.subscriptBaselineDropMin * scaleDown):tonumber(),
          (self.sub.height - constants.subscriptTopMax * scaleDown):tonumber()
       ))
       if self:is_a(elements.underOver) or self:is_a(elements.stackbox) or self.base.largeop then
@@ -629,7 +629,7 @@ function elements.subscript:shape ()
       self.sup.relY = SILE.types.length(math.max(
          isCrampedMode(self.mode) and constants.superscriptShiftUpCramped * scaleDown
             or constants.superscriptShiftUp * scaleDown, -- or cramped
-         --self.base.height - constants.superscriptBaselineDropMax * scaleDown,
+         (self.base.height - constants.superscriptBaselineDropMax * scaleDown):tonumber(),
          (self.sup.depth + constants.superscriptBottomMin * scaleDown):tonumber()
       )) * -1
       if self:is_a(elements.underOver) or self:is_a(elements.stackbox) or self.base.largeop then
```

**Result**:

![image](https://github.com/user-attachments/assets/6fcfc8d5-9f2c-4170-ba45-453e9a88b151)
![image](https://github.com/user-attachments/assets/df7382ea-c5b2-4404-aa2a-f24021320dca)

--> Maybe can we bisect why this code was commented out? It seems it was doing something more or less expected!

**Comment by Omikhleia** [comment]
Partly relates to #1799 (although the question was more general)

**Comment by Omikhleia** [comment]
Ah, maybe those lines do adverse things in inline (non-display) math:

Current:
![image](https://github.com/user-attachments/assets/798beed5-23cb-4329-b045-8c3d0db89e8c)

With commented out code reverted: The exponent is slightly raised and moves the interline...
![image](https://github.com/user-attachments/assets/045b53c4-046f-4260-be11-e174ad7bd4b6)

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Omikhleia** [comment]
Yet, the commented-out lines:
 - Are correct as per MathML Core §3.4.1.2 and §3.4.1.3 (Nov. 2023 Working Draft)
 - and TeMML is consistent with the output above when the code is restored, consistent with MathML core
 - ... but MathJax apparently knows better

Bisected to a97792c37b757ac7c7668f0fedc61a66cb3feaf9 = commented out by @OlivierNicole as part of changes "largely based on Ulrik Vieth's OpenType Math Illuminated."

Referenced document by Vieth found as [PDF](https://www.ntg.nl/maps/38/03.pdf), see p. 49
 - SuperscriptBaselineDropMax (= TeX σ18) and SubscriptBaselineDropMin (= σ19) in table 5
 - Illustration on fig. 4, and subsequent discussion = σ18 and σ19 apply "on a boxed subformula" (and other cases not at stake here).

A "boxed subformula" is not defined in that document, but on fig. 4 and its caption it seems to be opposed to "a single character". Testing with `{(k^2r^2)}^{1/3}` i.e. ${(k^2r^2)}^{1/3}$
 - LaTeX raises the 1/3 but both 2 on _k_ and _r_ are at the same position
 - TeMML shows the 2 on _k_ higher than the _2_ on _r_  (GitHub too, at least on my browser)
 - MathJax gives the same result as LaTeX... even for `(k+1)^2r^2`, and has the extra raising on e.g. `(k+1)^2r^2` -- and checking the MathML it's the same but with some `data-` attributes... They might be cheating a bit :)

Digging deeper, this [TeX Stack Exchange](https://tex.stackexchange.com/questions/88362/by-default-how-much-do-and-raise-and-lower-the-text-box-in-superscript-and) discussion gives some more pointer.

Notably this [TUGboat 27 no. 1 article](https://tug.org/TUGboat/Articles/tb27-1/tb86jackowski.pdf) by Jackowski, see esp. fig. 11 and discussion p. 89: the kernel is a "symbol", vs. a "boxed formula".

This is finicky :rofl:

Anyway, the case for the kernel being a symbol is easy. I'll at least push it in #2151
