### ISSUE TITLE
TeX-like math operator with sup-only part has the latter incorrectly place

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#2130]
**Input**

Formula in TeX-like syntax:

```
\prod_{n=1}^{\infty}
\prod_{p\,\in\,ℙ}
\prod^{ℙ} 
```

I.e. large operator, with (1) both sup and sub elements, (2) only sub elements, (3) only sup elements.

**Expected**

As obtained on https://latexeditor.lagrida.com/ and also https://saxarona.github.io/mathjax-viewer/

![image](https://github.com/user-attachments/assets/e5acc1a4-480a-4297-928e-1c53a08d1ce0)

**Observed**

![image](https://github.com/user-attachments/assets/b293c8c3-2e32-4857-b85e-276f67b8e54f)

= The last case does not have the sup part above the operator.

**Analysis**

The math package code is insane and poorly commented, sorry to say.
Yet a line for the sup-only case (which differs from the sub-only case) looks dubious:

```
diff --git a/packages/math/texlike.lua b/packages/math/texlike.lua
index 5d1073fe..5abb03c6 100644
--- a/packages/math/texlike.lua
+++ b/packages/math/texlike.lua
@@ -328,7 +328,7 @@ local function compileToMathML_aux (_, arg_env, tree)
       tree.options = {}
    -- Translate TeX-like sub/superscripts to `munderover` or `msubsup`,
    -- depending on whether the base is a big operator
-   elseif tree.id == "sup" and tree[1].command == "mo" and tree[1].atom == atomType.bigOperator then
+   elseif tree.id == "sup" and tree[1].command == "mo" and symbolDefaults[tree[1][1]].atom == atomType.bigOperator then
       tree.command = "mover"
    elseif tree.id == "sub" and tree[1].command == "mo" and symbolDefaults[tree[1][1]].atom == atomType.bigOperator then
       tree.command = "munder"
```

And with the shown change, yay! (**EDIT** but see comment, I was a bit too naive here)

![image](https://github.com/user-attachments/assets/cb9b6244-183e-4377-a4d3-7f2cdbf74ec7)

Dear math-aware friends, what do you think?

**Comment by Omikhleia** [comment]
>  Yet a line for the sup-only case (which differs from the sub-only case) looks dubious:

Seems both conditions are right, depending on whether the mo was defined via macro or not. OMG.

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
