### ISSUE TITLE
TeX-like math limits are not supported

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#2131]
_**My dear math friends**_...
Do you really expect SILE will thrive without the "limits"?
I don't know for other countries and recent school programs... but in my youth it was taught in "classe de terminale (scientifique)" (~ grade 12 maybe ?), that is to say indeed a scientific cursus, but not something _very_ advanced...

Surely all math friends would want limits natively supported in TeX-like syntax, wouldn't they?

**Input**

```
\lim_{x\to\infty} \frac{1}{x}
```

**Expected**

As obtained on https://latexeditor.lagrida.com/ (corresponding to display math mode):

![image](https://github.com/user-attachments/assets/22a0e670-9718-4aa1-a5b8-a1e6ffb4cdef)

**Observed**

Error: The `\lim` and `\to` commands aren't supported. (And I know `\to` comes from amsmath, I'm not even going to dicuss using `\rightarrow` as if amsmath hadn't existed for years...).

**Analysis**

First attempt at just adding these in my math formula

```
\def{lim}{\mi{lim}}% Note: crashes with \mo instead of \mi
\def{to}{\mo[atom=bin]{→}}
```

![image](https://github.com/user-attachments/assets/3dca8777-125e-4118-8606-bb6b53cf8c5c)

So we need something else to enforce `\lim` to be considered as a "big" operator...

Regarding the note "crashes with mo instead of mi, it crashes on the sub-handling line just following the dubious sup-handling line reported in #2130...)

Anyway, another attempt:

```
diff --git a/packages/math/texlike.lua b/packages/math/texlike.lua
index 5d1073fe..343b4e04 100644
--- a/packages/math/texlike.lua
+++ b/packages/math/texlike.lua
@@ -479,6 +479,8 @@ compileToMathML(
   \def{sqrt}{\msqrt{#1}}
   \def{bi}{\mi[mathvariant=bold-italic]{#1}}
   \def{dsi}{\mi[mathvariant=double-struck]{#1}}
+  \def{lim}{\mo{lim}}
+  \def{to}{\mo[atom=bin]{→}}
 
   % Standard spaces gleaned from plain TeX
   \def{thinspace}{\mspace[width=thin]}
diff --git a/packages/math/unicode-symbols.lua b/packages/math/unicode-symbols.lua
index 830a718c..32291b90 100644
--- a/packages/math/unicode-symbols.lua
+++ b/packages/math/unicode-symbols.lua
@@ -2649,6 +2649,7 @@ symbolDefaults["]"] = { atom = atomType.closeSymbol, stretchy = true }
 symbolDefaults["{"] = { atom = atomType.openingSymbol, stretchy = true }
 symbolDefaults["}"] = { atom = atomType.closeSymbol, stretchy = true }
 symbolDefaults["mod"] = { atom = atomType.binaryOperator }
+symbolDefaults["lim"] = { atom = atomType.bigOperator }
 symbolDefaults["%"] = { atom = atomType.binaryOperator }
 
 return {
```

Ya hey! Ya-harri-hey! Ya hoy!

![image](https://github.com/user-attachments/assets/bf560376-f381-4039-9891-3bc096290b18)

Frankly, I have the feeling of monkey-patching a messy and undocumented piece of code... That must be me, so what do you think, O Great Ones Who Master Maths?

**Subsidiary question**

What about `\limsup` and `\liminf`?
Hint (which unfortunately cannot be shown in a GitHub comment): It _can_ be done if the operator symbols are entered as "lim inf" and "lim sub" with the space here being a narrow no-break space (U+202F). A regular space doesn't work due to the way parsing is done somewhere... AFAIK, it does look somewhat good, but it seems a bit dubious. Sure the Great Ones would frown?

**Comment by OlivierNicole** [comment]
> Frankly, I have the feeling of monkey-patching a messy and undocumented piece of code... That must be me, so what do you think, O Great Ones Who Master Maths?

You’re welcome to rewrite it from the ground up if you have that sort of time. Maybe I would have, if there had been any traction around the feature since I made it work 4 years ago. Now typst seems to have the upper hand, and I’m not a fan of Lua’s slowness and lack of types, so I’ve lost interest.

**Comment by Omikhleia** [comment]
> so I’ve lost interest.

I'm really sad about this. So you helped pouring code into a software, that you are not even using?

> if there had been any traction around the feature since I made it work 4 years ago

So one posts issues, then even goes on a challenge https://github.com/sile-typesetter/sile/discussions/1802
...
What _traction_ did you expect, if you don't respect your own user base?

**Comment by Omikhleia** [comment]
> Now typst seems to have the upper hand

**This** is disrespectful, by the way.

**Comment by Omikhleia** [comment]
BUT let's back on focus: there's an issue here, and a even a PR. Move forward?

**Comment by OlivierNicole** [comment]
> > Now typst seems to have the upper hand
> 
> **This** is disrespectful, by the way.
> 
> EDIT: as well as " if you have that sort of time". You must be kidding.

You’re right, these are snarky comments and not helpful, so I apologize.

FYI, I was irritated by your comment about the code which strikes me as similarly disrespectful, and mostly false: I think the code is reasonably self-explanatory and commented, but of course one can disagree.

In any case, sorry but I won’t be allocating time to reviewing SILE PRs in the foreseeable future.

**Comment by Omikhleia** [comment]
>  I was irritated by your comment about the code which strikes me as similarly disrespectful, and mostly false

It wasn't intended to be personal (although I admit to a bit of dry humor in my appeal to math friends in these issues).
I am hard with the code[^1]...

... and I admit I was annoyed by the numbers of indirections for what seems to be the same thing, not being sure what I was doing at all:
 - atomType (openingSymbol) = 13 values, some of which aren't used in the code base...
 - atomTypeShort mapping ("open" etc.) = 13 values, just a different naming...
  - mkAtomType mapping ("mathopen" etc.) = 12 values, not corresponding fully to the previous... and many mapping to ordinary even operators...
 - addSymbol() by hexadecimal code points
 - symbolDefaults with explicit unicode characters... and some seem to override the previous definitions... and yet, some  seem to be missing[^2]...

> In any case, sorry but I won’t be allocating time to reviewing SILE PRs in the foreseeable future.

And what about reviewing a show-case booklet eventually? Would make me very happy ;)

[^1]: I regularly browse all the code and "evaluate" it on a range 1 (= rather bad) .. 5 (= fairly good), one decimal allowed. I filter out some 0 (= those few files I never really looked into yet), and average... SILE hardly reaches 1.5. But my own code in my resilient modules (which I should be proud of, logically, and be biased towards my own style...) hardly passes 2 (and one file is even at 0.5) :rofl: - This question is always debatable, and scoring criteria are obviously a matter of personal taste. The lack of comments amounts to a negative -1 in all cases (so in a way, the scores are not that bad overall, and does not imply the code isn't working well!) - Here for instance, I'd have expected lots of references to the MathML specs and/or some TeX sources...

[2]: Example, today's attempt at the "[Schwinger–Dyson equation](https://en.wikipedia.org/wiki/Schwinger%E2%80%93Dyson_equation#Derivation)" using [Joe's MathML example](http://eyeasme.com/Joe/MathML/Code/MathML/schwinger_dyson.txt) as a basis... Should ⟨ and ⟩ be overridden symbolDefaults, and additionally set to stretchy? It seems so... (Or to put it otherwise: every single equation I tried so far hits an issue.)

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
