### ISSUE TITLE
Support ICU 76.1. Build fails on macOS. Runtime missing symbols on Linux

### ISSUE THREAD

**Issue by cho-m** [sile-typesetter/sile#2152]
Seen while updating to new ICU 76.1 release in Homebrew https://github.com/Homebrew/homebrew-core/pull/193114

Might be related to https://github.com/unicode-org/icu/commit/199bc827021ffdb43b6579d68e5eecf54c7f6f56. May need a direct `icu-i18n` in
https://github.com/sile-typesetter/sile/blob/3b62dab9cdfdfcebbe86fa91d1896792ec925ab1/configure.ac#L149-L150

On macOS, build fails with:
```
libtool: link: clang  -o .libs/justenoughicu.so -bundle  .libs/justenoughicu_la-justenoughicu.o .libs/justenoughicu_la-compat-5.3.o   -L/opt/homebrew/opt/luajit/lib -L/opt/homebrew/Cellar/icu4c@76/76.1/lib -licuuc -licuio -lluajit-5.1  -g -O2  
libtool: link: ar cr .libs/svg.a  svg_la-svg.o svg_la-compat-5.3.o
Undefined symbols for architecture arm64:
  "_ucol_close_76", referenced from:
      _je_icu_collation_destroy in justenoughicu_la-justenoughicu.o
```

On Linux, sile builds but then fails at runtime:
```
error loading module 'justenoughicu' from file '/home/linuxbrew/.linuxbrew/Cellar/sile/0.15.5_2/lib/sile/justenoughicu.so':
	/home/linuxbrew/.linuxbrew/Cellar/sile/0.15.5_2/lib/sile/justenoughicu.so: undefined symbol: ucol_strcollUTF8_76
stack traceback:
	[C]: in ?
	[C]: in ?
	[C]: in function 'require'
	...llar/sile/0.15.5_2/share/sile/core/utilities/numbers.lua:4: in main chunk
	[C]: in function 'require'
	.../Cellar/sile/0.15.5_2/share/sile/core/utilities/init.lua:818: in main chunk
	[C]: in function 'require'
	....linuxbrew/Cellar/sile/0.15.5_2/share/sile/core/sile.lua:64: in main chunk
	[C]: in function 'require'
```

I believe these symbols are part of `libicui18n.{dylib,so}`.

**Comment by alerque** [comment]
Thanks for the report, I'll look into what we can do.

I also see [Harfbuzz is having some trouble with this ICU update](https://github.com/harfbuzz/harfbuzz/issues/4915), so that needs to get worked out before we'll be able to build too.

**Comment by cho-m** [comment]
> I also see [Harfbuzz is having some trouble with this ICU update](https://github.com/harfbuzz/harfbuzz/issues/4915), so that needs to get worked out before we'll be able to build too.

Personally haven't seen an issue with Harfbuzz but may be different build toolchains. On Linux, Homebrew builds with GCC 11 on Ubuntu 22.04.

**Comment by alerque** [comment]
I just gave the tree a quick shake over on [this branch](https://github.com/alerque/sile/tree/icu-761) (*not* using the last commit of course) using Nix's `icu76` package which seems to be 76.1rc right now. Both the default gcc based Flake (`nix run . -- --version`) and the clang variant (`nix run .#sile-clang -- --version`) seemed to build fine. I'm not 100% sure I'm debugging it right though.

In the mean time Arch Linux is still stick on ICU 75, so this is not very easy for me to dig into.

> May need a direct icu-i18n ...

If you can apply [this patch or equivalent](https://github.com/alerque/sile/commit/bd3ca1fa50005d11116fb3732a403eb4121525a0.patch) and confirm this is the only change needed I'd be happy to get it applied early and out in a release before other distros get hung on this.

**Comment by cho-m** [comment]
> If you can apply [this patch or equivalent](https://github.com/alerque/sile/commit/bd3ca1fa50005d11116fb3732a403eb4121525a0.patch) and confirm this is the only change needed I'd be happy to get it applied early and out in a release before other distros get hung on this.

I am using something similar in Homebrew PR[^1] (specifically adjusting `configure` to avoid regeneration). Based on ongoing CI run, build is successful and no issues with basic test we run.

Behavior should be backwards compatible.

[^1]: https://github.com/Homebrew/homebrew-core/pull/193114/files#diff-3eb1279f99561316a5b5d8760ed698b7e59328c530212cc887e177dda19289e2R148

**Comment by Anshsahu0802** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
