### ISSUE TITLE
Fix the \autodoc:codeblock I botched during the last release

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#2168]
While jumping through all the hoops releasing v0.15.6 last night (c.f. #2157) it became apparent that the verbatim fix for #2128 as addressed in #2129 looked great in the regression test but actually blew up the manual. The rule used above and below code blocks was wildly miss-spaced in some places and bloated the PDF by 40 some pages.

I probably should have just given up and gone to bed, but instead I tinkered with the autodoc package until the manual generation looked sane and forged ahead. In the light of the morning it is apparent that fix might have gotten the job done for the manual but it wasn't the *right* fix and it has broken the related regression test.

**Comment by Omikhleia** [comment]
Hint: The problem is not the base line skip... but the parskip ?

**Comment by alerque** [comment]
No it seems to have to do with the beginning and trailing newlines being passed inside `\raw`, which of course is different than the trimmed content of `\verbatium` or `\autodoc:codeblock`.
