### ISSUE TITLE
Outdated math example in user manual 0.15.6

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#2169]
The new pairing of opening/closing operators in TeX-like math makes this part of the package documentation outdated:

![image](https://github.com/user-attachments/assets/9382a30a-ddee-4003-b127-de8714c500a7)

But the effect of braces for grouping would still have to be explained and is still valid for solving certain cases ("un-paired" stretchy operators). We should revise this part of the documentation, possibly depending on how other topic in #2148 are eventually addressed.

**Comment by alerque** [comment]
I wouldn't mind seeing a more exhausting example page of math for the website too. You've had some nice samples in issues, we should cobble together a page worth showcasing some more of the bits that are coming together.

**Comment by alerque** [comment]
Linking an 80+ page booklet would absolutely be appropriate, from the manual, from the website, whatever. I'm more than up for that, feel free to PR things to the manual or website any time.

For the sake of the examples section of the website where folks with only a casual interest or evaluating whether SILE is even remotely the right tool for them, a single page example document to put in the gallery would still serve a different purpose. If it happened to be an equivalent of some sample page from another typesetter that I could also add to [polytype](https://polytype.dev/) that would be cool too.
