### ISSUE TITLE
Text "width" in tate mode wrongly computed?

### ISSUE THREAD

**Issue by shirat74** [sile-typesetter/sile#245]
I am currently trying to implement simple support for ruby annotation.
I noticed a strange behavior in calculating text "width" in TTB writing direction.

I prepared the following files test.lua

```
SILE.registerCommand("test", function(options, content)
   local rb = SILE.Commands["hbox"]({}, {content[1]})
   print("width=",rb.width)
   print("height=", rb.height)
end)
```

and test.sil

```
\begin[papersize=a4,class=jplain,layout="tate"]{document}
\script[src=test]
\test{longlonglonglongword}
\end{document}
```

Processing test.sil with SILE gives the result

```
width=  10pt
height= 10
```

in the "tate" layout. While it gives

```
width=  102.744140625pt
height= 7.6708984375
```

in "yoko" layout.

I tested with SILE after commit 2a36d77d4874d9bdd5818350d3d48de1391c04bf.

**Comment by simoncozens** [comment]
Will look at this later but have you noticed the ruby package?

**Comment by alerque** [comment]
This issue has been fixed, the width & hight reported by this test code is now correct both in tate and yoko layout modes.

Note there is another problem with the jplain class, namely that the content frame is hard coded to a specific size and does not adapt to the paper size. I'll open a separate issue to track that.
