### ISSUE TITLE
Setting  font weights and styles not fixed

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#307]
I started ripping out the hacks working around #203 in my common publisher library today and discovered all is not as well as could be hoped. Some individual cases work, but nesting font commands throws the whole thing off. Below is one set of examples for an MWE, but there are more. For example besides the style vs. weight  conflicts going on here, setting font properties in a SILE function rather than with the built in `\font` command means this sort of nesting doesn't work for whole documents even when no style attributes are set anywhere.

``` TeX
\begin[papersize=180mm x 90mm]{document}
\nofolios
\set[parameter=document.parindent,value=0]
\set[parameter=document.parskip,value=1ex]

\font[size=14pt]

\font[family=Crimson]{\font[style=Italic]{I am italic but \font[weight=600]{these words} should be bold.} Whereas \font[weight=600]{these words} actually are.}

\font[family=Libertinus Serif]{\font[style=Regular]{But it's not just italic style that throws off \font[weight=600]{these words} not being bold, Regular does too.}}

\font[family=Libertinus Serif]{\font[style=Roman]{But style Roman doesn't throw off \font[weight=600]{these words} being bold.}}

\font[family=Libertinus Serif]{\font[style=Italic]{I am italic but \font[weight=600]{these words} should be bold.} Whereas \font[weight=600]{these words} actually are.}

\font[family=Montserrat]{\font[style=Italic]{I am not italic because this font doesn't have one and weight selection is going to work here, but why am I weight 200 \font[weight=300]{when 300 is thin,} \font[weight=400]{400 is normal,} \font[weight=600]{and 600 is bold?} \font[weight=800]{Not to mention black.}}

\font[style=Regular]{Oh but wait, setting style Regular sets the font weight to 300 instead of the 200 default and lets you \font[weight=400]{manually set 400} \font[weight=600]{but not 600!}}}
\end{document}
```

![selection_194](https://cloud.githubusercontent.com/assets/173595/14388602/8d1bde7c-fdb7-11e5-8c24-41436445eb77.png)

**Comment by simoncozens** [comment]
OK, several things. The obvious thing is that the default weight of 200 is clearly wrong, and should be 400. That's an easy one. (I think.)

The harder part is with FontConfig, and I am going to need @behdad's help here. As far as I can tell SILE is doing the right thing, and the `macfonts.m` font selection code does what you want expect, but fontconfig does not. And I think we are asking fontconfig the right question but not getting the right answers.

Here is the first part of the document, which is correct:

    [fonts] Looking for Crimson Text;14;400;Italic;normal;;LTR
    Asking FC for a font that is Crimson Text,Times\-Roman,Times,Helvetica-14:style=Italic:weight=40
    [fonts] Resolved font family Crimson Text -> /Users/simon/Library/Fonts/CrimsonText-Italic.ttf

(The FC pattern is in the middle.) Here is the next one, which doesn't work:

    [fonts] Looking for Crimson Text;14;600;Italic;normal;;LTR
    Asking FC for a font that is Crimson Text,Times\-Roman,Times,Helvetica-14:style=Italic:weight=180
    [fonts] Resolved font family Crimson Text -> /Users/simon/Library/Fonts/CrimsonText-Italic.ttf

This is wrong. It should return `/Users/simon/Library/Fonts/CrimsonText-SemiboldItalic.ttf`. Taking SILE out of the equation:

    $ fc-match 'Crimson Text:style=Italic:weight=900'
    CrimsonText-Italic.ttf: "Crimson Text" "Italic"

The problem is that FontConfig is merging the concepts of style and weight in a way that is not useful:

    $ fc-match 'Crimson Text:style=Italic:weight=900'
    CrimsonText-Italic.ttf: "Crimson Text" "Italic" # NO!
    $ fc-match 'Crimson Text:style=BoldItalic:weight=100'
    CrimsonText-BoldItalic.ttf: "Crimson Text" "BoldItalic" # YES!

Here's why the Libertinus example fails:

    $ fc-match 'Libertinus Serif:style=Regular:weight=900'
    libertinusserif-regular.otf: "Libertinus Serif" "Regular" # NO!
    $ fc-match 'Libertinus Serif:style=Bold:weight=100'
    libertinusserif-bold.otf: "Libertinus Serif" "Bold" # YES!

So if I want a bold font, I have to ask for it in the "style" pattern, not in the "weight" pattern - that is counterintuitive (=UK understatement)... @behdad?

**Comment by simoncozens** [comment]
OK, got it. "Style" should be "Slant".

**Comment by alerque** [comment]
Almost. At least in my test from HEAD just now the second line is still missing the bold. The other managery of issues seems to be working properly.

**Comment by simoncozens** [comment]
Works for me replacing "Crimson" with "Crimson Text".

**Comment by behdad** [comment]
lgtm

**Comment by alerque** [comment]
If this worked for you then something is up on the Mac, but it's still broken for me on Linux. The wording of the test is really confusing because it was meant to describe the broken scenario I was originally seeing not the working state it should be in. Some of the issues got fixes, but at least two things are still broken for me. Paragraphs 2 and 6 don't have  bold.

I'm updating the test to be more readable so the issues are apparent when manually reviewing it. If we want to mark it KNOWNBAD again I guess we can, but I'm not updating the `.expected` output to match the current test be cause it is not in fact outputting the correct result for me.

**Comment by alerque** [comment]
Here's what I'm seeing with the two still outstanding issues highlighted:

![selection_297](https://cloud.githubusercontent.com/assets/173595/20090417/b2692cf8-a595-11e6-951f-718cfeaf4b0d.png)

**Comment by simoncozens** [comment]
Hah! On OS X I get the first two paragraphs in plain ol' Roman, (no italic, no bold) but everything else looks good.

**Comment by alerque** [comment]
@simoncozens I think you might have an old version of *Crimson* on macOS that calls itself *Crimson Text*. Changing that in the test might make that bit work for you. Paragraph 2 sounds like you have the same issue I do. I'm surprised the last paragraph had the bold for you though.

**Comment by simoncozens** [comment]
You're right. I deleted the Crimson Text font, and now I have this:
![screen shot 2016-11-10 at 16 21 26](https://cloud.githubusercontent.com/assets/106728/20165484/c4600b52-a761-11e6-814c-25afa97723e8.png)

So for me it's just the second paragraph, and for you the last one as well.

**Comment by simoncozens** [comment]
This is a fontconfig issue, so I'm asking on the mailing list there.

**Comment by alerque** [comment]
@simoncozens I *think* this issue can probably be closed, but it's hard to be sure. Literally **all** the cheese has moved, but I can't replicate any part of this that still looks like a bug in anything. Every single one of the fonts being tested here has seen major overhauls that add weights and styles and fixed bugs, fontconfig has been updated an returns different answers, and typesetting the examples above I get the expected output in every case.

It's hard to say what combination of changes "fixed" this, but I don't see anything actionable right now. Am I missing something?

**Comment by alerque** [comment]
Feel free to re-open if I overlooked something.
