### ISSUE TITLE
Command line arguments should be accepted more than once

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#405]
When parsing command line arguments we should iterate over all of them and accept  multiple values for each. In the case of items such as `backend` or `output` where only one value can stand the last given argument should take precedence. For all others, each should be processed appropriately: `include` should build a table of things  to include, `evaluate` should run code as many times as parsed, `debug` should add flags, etc.

**Comment by Omikhleia** [comment]
With SILE 0.14, I am used to have e.g. several `-u packages.xxx` command-line arguments.
Was anything else at stakes here?

**Comment by alerque** [comment]
Yes, this stuff all landed in v0.14.0.

Thanks for helping with issue triage.
