### ISSUE TITLE
Strange error about missing language

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#407]
Sometime last week —and I can't correlate this with any change I'm aware of— SILE started throwing this warning pretty much any time I use it:

```
[1] [2] [3]
! Error loading language en-u-va-posix: /home/caleb/projects/sile//core/sile.lua:62: module 'languages/en-u-va-posix' not found: 
        no field package.preload['languages/en-u-va-posix'] 
...
<the usual list of search paths tried>
```

What page it falls on varies from document to document, but if nothing else it seems to give this at the end of a document if it hasn't happened before then. Sometimes it gets thrown many times per document.

I can't find anything in my environment, document or libraries where the string `en-u-va-posix` could be coming from.

**Comment by simoncozens** [comment]
You know, I would be debugging this the dumb-stupid way. At the top of `core/languages.lua:loadLanguage`, add `if language == "en-u-va-posix" then SU.error("WHAT",1) end`.

**Comment by alerque** [comment]
So this gets triggered any time I tag content as not having a language using `\font[language=und]{...}` or similar. Using `xx` or some other bogus value value produces the usual error about  there being no language support file for xx, but passing `und` results in en-u-va-posix (which doesn't even match my system's locale setting).

**Comment by simoncozens** [comment]
The culprit is `icu.canonicalize_language`.

**Comment by Darkyenus** [comment]
This seems to be still happening:
```tex
\begin{document}

\font[language=und]{Hello.}

\end{document}
```

Leads to:
```
This is SILE 0.9.5.1
<bug.sil>

! Error loading language en-u-va-posix: no support for this language
[1] 
```

However, the file seems to be generated correctly.

**Comment by alerque** [comment]
I routinely tag text in my books such as transliterations and pseudo-language words with _und_ and the typsetting works fine. I've become blind to this error. As much as it makes more sense than  the old error, I do think we should figure out a way to stop throwing it at all for text that is specifically tagged as being undefined. It's counter intuitive to have a language code you didn't specify showing up as an error.

**Comment by alerque** [comment]
This has been fixed.
