### ISSUE TITLE
Best markup for poetry regions (Markdown→Sile)

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#408]
I'm touching up some odds and ends in the Pandoc SILE writer and am not sure the best solution for a format. Markdown supports blockquotes of course, but Pandoc's flavor also has a nestable style that forces hard line wrapping. Here's an except from the wild:

``` Markdown
Tanrı’nın yürekleri katılıştırma işi sadece İsrailli olmayanlarla sınırlı
değildi. Aslında bu gerçek, tarihin bu döneminde İsrail’in yaşamında merkez bir
rol oynamaktadır. Romalılar 11:7–9’da Pavlus, İsrail’in aradığı kurtuluşa ve
doğruluğa ulaşmaktaki başarısızlığından bahsetmektedir:

> İsrail aradığına kavuşamadı, seçilmiş olanlar ise kavuştular. Geriye
> kalanlarınsa yürekleri nasırlaştırıldı. Yazılmış olduğu gibi:
>
> | “Tanrı onlara uyuşukluk ruhu verdi;
> | Bugüne dek görmeyen gözler, duymayan kulaklar verdi.”
>
> Davut da şöyle diyor:
>
> | “Sofraları onlara tuzak,
> | Kapan, tökez ve ceza olsun.
> | Gözleri kararsın, göremesinler.
> | Bellerini hep iki büklüm et!”

Her ne kadar Tanrı’nın buyruğunun, halkının görmesi, duyması ve imanla cevap
vermesi (Yeşaya 42:18) olmasına rağmen yine de, sadece kendisinin bildiği
nedenlerden ötürü bazı kişilerin buyruklarına uymaması için inatçılık ruhu
vermektedir.
```

That's a couple paragraphs with a blockquote in between. Inside the blockquote are four paragraphs, two normal and two specifically poetry formatted so the line breaks have to come across.

At the moment the way Pandoc's internal representation of this works is the blockquote section is a block level item but the line break thing is inline. Right now this comes out in SILE looking like this:

``` Tex
Tanrı’nın yürekleri katılıştırma işi sadece İsrailli olmayanlarla sınırlı
değildi. Aslında bu gerçek, tarihin bu döneminde İsrail’in yaşamında merkez bir
rol oynamaktadır. Romalılar 11:7–9’da Pavlus, İsrail’in aradığı kurtuluşa ve
doğruluğa ulaşmaktaki başarısızlığından bahsetmektedir:

\begin{quote}
İsrail aradığına kavuşamadı, seçilmiş olanlar ise kavuştular. Geriye
kalanlarınsa yürekleri nasırlaştırıldı. Yazılmış olduğu gibi:

“Tanrı onlara uyuşukluk ruhu verdi;\break
Bugüne dek görmeyen gözler, duymayan kulaklar verdi.”

 Davut da şöyle diyor:

“Sofraları onlara tuzak,\break
Kapan, tökez ve ceza olsun.\break
Gözleri kararsın, göremesinler.\break
Bellerini hep iki büklüm et!”
\end{quote}

Her ne kadar Tanrı’nın buyruğunun, halkının görmesi, duyması ve imanla cevap
vermesi (Yeşaya 42:18) olmasına rağmen yine de, sadece kendisinin bildiği
nedenlerden ötürü bazı kişilerin buyruklarına uymaması için inatçılık ruhu
vermektedir.
```

This would render alright if inside a ragged environment, but what happens when it is justified is not pretty:

![selection_299](https://cloud.githubusercontent.com/assets/173595/20181594/74c7865a-a767-11e6-9c45-335bccd24836.png)

I can think of a couple options. One would be to output `\hfill\break` in this scenario. That's nice for most documents, but what if the document was typeset ragged left? Or center? That would mess everything up.

Of course everything is messed up anyway in those cases because it's possible to indent poetry lines like this:

```Markdown
| Line one
|     Line two
| Line three
|     Line four
```

This I'm outputting using `\kern[width=1spc]` for each space of indent. Which works, but again a centered document would get all wonky pretty fast.

Another option would be to wrap each line in  some kind of function that could then be styled. Or I can try to hack on it to make this a block level format that wraps all the affected lines.

What would be the best scenario for this markup to end up looking like in a SILE document?

**Comment by simoncozens** [comment]
Does the verbatim package give you any clues? I think in terms of markup your best possible situation would be to have a `\begin{verse}...\end{verse}` style of markup. I'll note in passing that Latex's `verse` environment requires help from the user to get centered verses right.
