### ISSUE TITLE
Correct for advance direction changes when switching to/from italics 

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#428]
Per discussion on my recent [Libertinus font issue](https://github.com/khaledhosny/libertinus/issues/50), it sounds like SILE could (optionally?) implement some sort of correction when switching to/from italic text to avoid this kind of display issue.

**Comment by Omikhleia** [comment]
After those 6+ years... You meant having proper "italic correction", right?

Would I be close here?

![image](https://user-images.githubusercontent.com/18075640/235096961-8d7e5a06-1a3d-4b8c-8ecc-6eb3b2ef9dae.png)

**Comment by alerque** [comment]
Yes.

I think the hard part of implementing this is we're necessarily in different chunks, and should probably only apply this when the only difference between font properties is the style or weight but not size or script.

**Comment by Omikhleia** [comment]
Oh it's tricky... and (relative) size matters:

![image](https://user-images.githubusercontent.com/18075640/235107510-b3ca8499-9eba-44ec-b5c2-9672d378a879.png)

I'll clean up my messy code and propose a PR, eventually.
