### ISSUE TITLE
Add Lilypond support

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#435]
Add package with commands to embed Lilypond code either inline or as external files that is engraved externally before being included in SILE for layout.

**Comment by alerque** [comment]
Note that this will be conceptually similar to adding MathJax support (#220) in that a block of content will be passed out to some other program to be rendered and the result embedded in the output.

**Comment by simoncozens** [comment]
Can't you do this yourself? ;-) I think there's an example of using the inputfilter package for this kind of thing.

**Comment by alerque** [comment]
Yes I think I can wire this up, I just haven't had the necessary combination of time and motivation. I'm sure the next time I have to fix something in one of my PDF build pipelines that uses LaTeX I'll get in gear and make this happen. Note I'd already self-assigned this issue.

**Comment by alerque** [comment]
Progress report: I have basic systems rendering in a sile document. Cutting through the hack jobs surrounding the TeX implementations of this is crazy hard but this is going to be a lot easier it SILE than it ever was in TeX!

![Lilypond in SILE]()

**Comment by alerque** [comment]
Progress report: now detecting some basic layout parameters like font size, line width, indent, ragged vs. flush formatting, etc. from the SILE context and passing them  to Lilypond.

![selection_030](https://user-images.githubusercontent.com/173595/33514770-c41df55c-d76a-11e7-89f1-9f8c808c0078.png)

**Comment by alerque** [comment]
It's probably worth reviewing the [lyluatex](https://github.com/jperon/lyluatex) project for pointers in implementing this.

**Comment by Omikhleia** [comment]
This issue (and related PR #499 should be moved to [lilypond.sile](https://github.com/sile-typesetter/lilypond.sile) and closed here as "rejected - to be handled in a 3rd-party package]. 
(Noting in passing: I'd be interested in Lilypond support to be resurrected there...)

**Comment by ctrlcctrlv** [comment]
"rejected - to be handled in a 3rd-party package"
