### ISSUE TITLE
Questions: Any (business) letter style and disable page numbering?

### ISSUE THREAD

**Issue by clintolsen** [sile-typesetter/sile#453]
Hi:

It's probably a silly question, but is there a business letter template yet? I understand Sile is pretty new and may not have that yet.

Also, I tried `numbering=no` in the `\begin` attribute section and this didn't seem to get rid of page numbers. I realize I co-opted that from a section describing chapters, so I didn't expect it would work.

`begin[papersize=letter,numbering=no]{document}`

Thanks,

-Clint

**Comment by simoncozens** [comment]
Business letter: Not yet, but if you write one I'll commit it. :-)

Folios: The command to turn off folios completely is `\nofolios`, and the command to turn off folios for one page is `\nofoliosthispage`. It turns out that this is not documented yet, which is a bug.

**Comment by clintolsen** [comment]
I can take a crack at it. Should I follow the instructions ~Chapter 9 like with Bringhurst or is there an easier way to go about it?

I was always somewhat unconvinced with LaTeX's letter template. I'm a block-style guy myself.

**Comment by simoncozens** [comment]
The chapter 9 instructions should be fine, but you may find it easier to have a look at the other classes and modify one of them.

I never know what a letter class is meant to do, to be honest. Maybe my letters are not typographically sophisticated enough.

**Comment by clintolsen** [comment]
OK, if you could give me a target class to consult, that'd be great. I don't currently have the git repo checked out. It sounds like I may have to do this if I really want to dig into it.

So, letters don't have to be super fancy, but they have some pretty basic elements: A date, a sender address, a receiver address, a greeting, a body, and often a salutation. The LaTex template I think made template arguments out of the sender and receiver. Maybe it auto-generated the date. I'd have to go look.

There are some variations documented here: https://owl.english.purdue.edu/owl/resource/653/01 for example. In there they have suggested top margins and distances between some elements.

Nothing is stopping you from doing this by hand of course, but if there was something that sped up the process a little that would be helpful.

**Comment by alerque** [comment]
See also #455.

**Comment by simoncozens** [comment]
I've started you off with `classes/letter.lua`. See what else you want it to do (and see the example in `tests/letter.sil`). Let me know if there are things you want it to do but can't get working.

**Comment by clintolsen** [comment]
OK, I just tried to sync the HEAD with sile using brew, and it didn't update anything. I'm still new to brew. Do I have to use git manually to get this?

**Comment by simoncozens** [comment]
I don't know, I'm sorry. But if you just want to grab the file and put it into your `classes` directory it's at https://raw.githubusercontent.com/simoncozens/sile/master/classes/letter.lua

**Comment by alerque** [comment]
@clintolsen when you did the brew install did you `brew install sile` or did you run `brew install sile --HEAD`? The former would give you the last released version and the latter would fetch the latest version from the source repository. You should be able to tell by running `sile --version` which would either tell you something like 0.9.4 (the last release) or 0.9.5-unreleased (which would indicate you have a version from HEAD at whatever time you installed it).

**Comment by clintolsen** [comment]
I did run `brew  install --debug sile --HEAD` and it says that:

`Warning: sile-HEAD-6dd57bd_2 already installed`

I do have `0.9.5-unreleased` as my version but I don't think this represents the HEAD on github.

**Comment by simoncozens** [comment]
So it looks like you installed the git version as of a few weeks ago, and Homebrew is now happy that you have a git version and doesn't want to install it again; it's just that the git HEAD has moved on. You could uninstall and reinstall, but if you want to work on stuff you may find it easier to work on a git checkout directly.

**Comment by clintolsen** [comment]
I performed a reinstall, and this seemed to have worked. Before I saw:

`Warning: sile-HEAD-6dd57bd_2 already installed`

Now if I install again, I see:

`Warning: sile-HEAD-bd8111d_2 already installed`

And letter.lua is there now. I have to admit I'm pretty underwhelmed with how brew works. It's not clear to me why reinstalling is better than having some kind of install --force (which apparently has been removed from brew).

**Comment by simoncozens** [comment]
Yeah, I think the `--HEAD` support is a bad hack, but it does its job: "Just give me the version of this as of now."

Please note that the `letter.sil` example relies on a command I only just committed to `plain.lua`:

```
\define[command=cr]{\hfill\break}%
```

**Comment by Omikhleia** [comment]
Unless @clintolsen wants to add something to it, @simoncozens had included a "letter" basic class to SILE in 2017 - Was there anything else that prevented this old issue to be closed?

**Comment by alerque** [comment]
Happy to re-evalute if there is something missing.
