### ISSUE TITLE
\open-double-page is overzealous

### ISSUE THREAD

**Issue by simoncozens** [sile-typesetter/sile#454]
And forces a pagebreak even when it doesn't need to.

**Comment by alerque** [comment]
Yes. I have another version of it that I think is better, but every time I think about contributing it I find another edge case comes up. It's a harder problem than I expected.

**Comment by alerque** [comment]
See also @Omikhleia's implemtation in [this comment](https://github.com/sile-typesetter/sile/issues/1283#issue-1051933941) and my alternative [in CaSILE](https://github.com/sile-typesetter/casile/blob/6529e93163add0ec9c2ff87dee52b437595108b7/casile.lua#L213).

https://github.com/sile-typesetter/sile/issues/1283#issue-1051933941

**Comment by alerque** [comment]
Five years later I finally found the bug in my CaSILE implementation that made it fickle. Long story short, my variable scoping was wrong and a incrementor-hook was being added on every use so it leaked iteration information from previous runs.
