### ISSUE TITLE
Fedora: blank pages after Font 'Gentium Plus' not available, falling back to 'Helvetica'

### ISSUE THREAD

**Issue by william8000** [sile-typesetter/sile#487]
I just built sile from the github source under Fedora 25.
`sile simple.sil`
shows the messages below and creates simple.pdf, but when I view it, it is just two blank pages.
```
This is SILE 0.9.5-unreleased
<simple.sil>

! Font 'Gentium Plus' not available, falling back to 'Helvetica'
[1] [2]
```
It looks like sile embedded a subset of Helvetica but maybe messed up the encoding.
```
$ pdffonts simple.pdf 
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
KFRTDH+Helvetica-Identity-H          CID Type 0C       Identity-H       yes yes no       5  0
```
If I edit simple.sil and add `\font[family=Utopia]`, then the text shows, but sile seems unable to handle the majority of fonts that come with Fedora. The difference might be unicode.
```
$ pdffonts simple3.pdf 
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
DYCTKZ+Utopia-Regular-Identity-H     CID Type 0C       Identity-H       yes yes yes      5  0
CFQURM+Helvetica-Identity-H          CID Type 0C       Identity-H       yes yes no       7  0
```
I would like to be able to run the examples, and I don't mind if sile substitutes fonts, as long as it picks a font that it can use.
How do I install the Gentium fonts and other fonts used by the examples? `dnf` provides '*/Gentium'` suggests texlive-base-6:2016-33.20160520 and texlive-gentium-tug-doc-6:svn37378.1.1-33.

I tried adding `\font:add-fallback[family=Utopia]` near the top instead of `\font[family=Utopia]`, but sile says `! Unknown command font:add-fallback at simple.sil l.2, col.1` What is the correct syntax?

Also, when I go to the docbook example directory and run `sile -I docbook article-template.xml`, it says
```
This is SILE 0.9.5-unreleased
Loading docbook<article-template.xml>

! This isn't a SILE document! at article-template.xml
```
I took the command from the manual. I don't need to process docbooks, but I am thinking about processing XMLs.

Thanks, William

**Comment by simoncozens** [comment]
Urgh, I'm sorry; that's not a great introduction to SILE for you! I will try and get a Fedora VM up soon and take a look. I don't see a Gentium Plus RPM for Fedora, which is a bit of a pain; there's only RPMs for the (deprecated) Gentium, and we've had this discussion before (See #369).

But if it does find Helvetica instead, then it should absolutely typeset it with Helvetica, and I don't know why it isn't. The font fallback support only works with the appropriate package loaded; you would need to say:

```
\script[src=packages/font-fallback.lua]
```

I will have a look at the docbook issue. I have had to make some changes to the markdown input format recently to make that work again, so I will see if similar changes need to be done to the docbook handler.

**Comment by william8000** [comment]
Thanks!
Fedora 25 still has a number of packages matching sil-*-fonts. After reading #369 I installed all of them but did not get Gentium Plus (used by the simple.sil example). I got Gentium Plus from the sil web site:
```
https://software.sil.org/gentium/download/
unzip GentiumPlus-5.000.zip
cd GentiumPlus-5.000
mkdir /usr/share/fonts/sil-gentiumplus
cp -p GentiumPlus-* /usr/share/fonts/sil-gentiumplus/
chmod 755 /usr/share/fonts/sil-gentiumplus
chmod 444 /usr/share/fonts/sil-gentiumplus/*
fc-cache -r -v
fc-list | grep Gentium
```

> `\script[src=packages/font-fallback.lua]`

It didn't work for me like that. I had to remove the .lua. So with
```
\script[src=packages/font-fallback]
\font:add-fallback[family=Gentium Basic]
```
after the first line of showoff.sil, sile still complains
```
! Font 'Baskerville' not available, falling back to 'Helvetica'
! Glyph T not found in Baskerville
! Glyph h not found in Baskerville
...
! Font 'Gill Sans' not available, falling back to 'Helvetica'
! Glyph T not found in Gill Sans
! Glyph h not found in Gill Sans
...
Error detected:
/usr/local/share/sile/core/libtexpdf-output.lua:100: bad argument #1 to 'imagebbox' (string expected, got nil)
```
and writes an incomplete pdf with only 15 bytes.
If the message says `falling back to 'Helvetica'`, why is it still saying that it can't find glyphs in `Baskerville` and `Gill Sans`?
I am pretty sure that my Helvetica font is good. It is a Type1 PFB with the StandardEncoding. It should have normal ascii letters. `ghostscript` can use it, and `fontmatrix` can browse it.

Does the `add-fallback` affect the entire document or just the following line?
I tried again with
```
\script[src=packages/font-fallback]
\begin[family=Gentium Basic]{font:add-fallback}
```
after the first line of showoff.sil and `\end{font:add-fallback}` before the last line, and then sile didn't show any warnings or errors, and pdffonts shows that the only font is a GentiumPlus subset, but the pdf shows only a blank page, and when I edit the pdf, it has a few flate-encoded streams but no commands to draw text.

I downloaded Gill Sans from http://www.freefontspro.com/14233/gill-sans.ttf and Baskerville from https://cooltext.com/Download-Font-Baskerville
Now when I run the original showoff.sil, I have the fonts, but I still get the imagebbox error and a truncated 15 byte pdf.
```
This is SILE 0.9.5-unreleased
<showoff.sil>

! Font 'Gill Sans' not available, falling back to 'GillSans'

Error detected:
/usr/local/share/sile/core/libtexpdf-output.lua:100: bad argument #1 to 'imagebbox' (string expected, got nil)
```

Regards, William

**Comment by pkulchenko** [comment]
> `\img[src=examples/images/sile-logo.jpg,height=20pt]`

The `imagebbox` error is related to the different path where the logo image is located; the .sil file should be updated to `examples/docbook/images/sile-logo.jpg`. I'm not sure why the files were moved, but that fixed the issue for me.

@simoncozens, I think a bit more graceful degradation may be useful, like inserting some `[x]` image and sending a message to the console.

**Comment by william8000** [comment]
Thanks, I updated the path to `examples/docbook/images/sile-logo.jpg`, and now showoff.sil (with only that change) passes that point and gets the error below. If I also restore the font-fallback lines (`\script[src=packages/font-fallback]` and `\begin[family=Gentium Basic]{font:add-fallback}` near the top and `\end{font:add-fallback}` near the bottom), sile runs cleanly :smile: but the resulting page looks blank when I view it :disappointed: (and when I edit the pdf, the only text object seems to be the digit `1` which might be a page number).

```
$ sile examples/showoff.sil 
This is SILE 0.9.5-unreleased
<examples/showoff.sil>

! Font 'Gill Sans' not available, falling back to 'GillSans'
[1] 
! Font 'Hiragino Mincho Pro' not available, falling back to 'Helvetica'

Error detected:
/usr/local/share/sile/core/base-shaper.lua:84: /usr/local/share/sile/core/base-shaper.lua:129: attempt to index a nil value (local 'item')
```

**Comment by alerque** [comment]
It seems we've kind of dropped the ball on responding to this issue, but there is actually a lot of progress on it and I think this might be obsolete.

@william8000 Regarding your last output there, it's slightly confusing because the messages about font fallbacks (lines starting `! Font ...`) and just warnings, they don't actually stop SILE from functioning. The subsequent error is completely unrelated. We have much better error reporting now with the `-t` option that will trace the actual code sequence that arrived an an error condition.

That being said I'm pretty sure the errors being hit here have all been addressed, but there is one other thing in the original issue that I don't see addressed. Specifically this command:‌

    sile -I docbook article-template.xml

This was a victim of and early issue in SILE where it was trying to be too smart about guessing file types and sometimes shooting itself in the foot. This has since been fixed and you'll find the corrected command in the documentation. The error about "this not being a SILE document" is actually because the docbook class that teaches SILE what to do with that document type never got loaded. It didn't get loaded because `-I docbook` loaded a Lua file, but in this case the class itself is written in SILE's TeX-like macro language and needs to be loaded with `-I docbook.sil`. That SIL file actually loads the Lua file of the same name for some of it's work, but just loading the Lua file itself isn't enough.

This should probably be refactored to just all be in the Lua file, but the errors shown in this issue are actually all taken care of.

**Comment by william8000** [comment]
Thanks! I still have my notes from three years ago, and I'll try it when I finish my current project.
