### ISSUE TITLE
Comments before opening tags break parser

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#502]
Both the TeX-flavor and XML-flavor markups have issues with comments appearing before the start of the document.

1. Comments cannot come before the opening tag in TeX-flavor at all.
1. The XML flavor sniffing only works if an opening angle bracket is found in the first 100 characters, which can be broken by `!DOCTYPE...` text at the top of a document.
1. The XML flavor sniffing can mistakenly pick up angle brackets in comments (or body content) in TeX-flavor markup.

I think the whole file type sniffing and comment parsing grammar needs to be revisited.

**Comment by Omikhleia** [comment]
Doesn't it somehow relates to #1595 ?

**Comment by alerque** [comment]
Yes. This was largely fixed by our inputter overhaul and touched up by the fix you linked. The only thing we're missing now is a test, so I'll repurpose this issue to add tests before the next release.
