### ISSUE TITLE
A docker image for sile

### ISSUE THREAD

**Issue by neofob** [sile-typesetter/sile#520]
It would be nice to have a docker to run `sile`, ja?

Where should I start? Reverse-engineering the travis build code to isolate the necessary steps to build the binary?

**Comment by neofob** [comment]
@simoncozens : Thanks for the tip!

**Comment by alerque** [comment]
See also #588 and the idea in #638 of having Flatpack and/or Snap packages that bundle _all the things_ required to run in a containerized package format. The leg work for those is likely much the same as for Docker. The difference in my mind would be for desktop use vs. sever/CI deployments. No?

**Comment by alerque** [comment]
I have SILE working in a Docker image. I'll be releasing it to Docker Hub soon after I strip out any unnecessary cruft leftover from the build phase. If you are interested in having an early look check out the [source repo](https://github.com/sile-typesetter/dockerfiles).
