### ISSUE TITLE
Content re-ordered

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#532]
I've had a freaky problem come up in multiple projects now where _some_ rendering passes will miss-order content. Anything that is wrapped in some markup (font style or weight change, etc.) can get pushed to the end of the line it's supposed to be in. Usually running another rendering pass clears this up. It's not consistent on whether the first pass or the second or the third or whatever will fail like this.

Compare the order of italicized bits:

![selection_046](https://user-images.githubusercontent.com/173595/38577957-245dd076-3d0b-11e8-8aa2-de9a6e5830ca.png)

With the source:

```TeX
...
\footnote{Smarto, \em{Pursued}, 122.}
...
\footnote{Anthony A. Hoekema, \em{Saved by Grace} (Grand Rapids, MI: Eerdmans, 1989), 178.}
...
```
Note the `\em{}` tagged content is typeset out of sequence.

**Comment by alerque** [comment]
Here is an MWE from #972, which seems to be a duplicate:

```
\begin{document}
\script[src=packages/rebox]
\begin{script}
  local inputfilter = require("packages/inputfilter").exports
  local noop = function (input, _) return input end
  SILE.registerCommand("nondet", function(_, content)
    SILE.process(inputfilter.transformContent(content, noop))
  end)
\end{script}
\nondet{\rebox{foo \em{bar} baz}}
\end{document}
```

Interestingly I couldn't get rid of either the rebox or inputfilter, but the example production project shown above doesn't use inputfilter at all, and only uses rebox for the list numbers. The content being re-ordered is not inside a rebox.

**Comment by simoncozens** [comment]
That was weird - found it, thought, it's `pairs()`:
```lua
local function transformContent(content, transformFunction, extraArgs)
  local newContent = {}
  for k, v in pairs(content) do
```

"In Lua, the order that pairs iterates through the keys is unspecified." Every time we use `pairs()` on a content stream, we need to do `ipairs()` first and then `pairs()` for the non-integer keys.
