### ISSUE TITLE
Consider using luarocks as a package manager for SILE extensions

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#538]
Today I noticed [some discussion](https://github.com/awesomeWM/awesome/issues/1171#issuecomment-254629024) in regard to the [awesome window manager](http://awesome.naquadah.org/) that is also build in and can be extended in Lua. I know the idea of contributed packages has come up before (see #60) and that for now most stuff is making it's way into core, but I've also noticed that this isn't going to work indefinitely. Even as a SILE developer and managing my own release branch so that I have just the patches I want running on my CI servers that build SILE projects, the pace of developing helper libraries that get used across different projects is a different page that what is comfortable in core. Likewise having the same code duplicated on a per-project basis is undesirable.

I think we should consider normalizing a file format for packaging extended features not shipped in the SILE core but possibly useful as building blocks in other projects and also way of interfacing with them that allows a document to specify dependencies, not just as in a local file path but to request that SILE have access to a luarock.

**Comment by simoncozens** [comment]
I've started thinking about SILE package management today, and have an idea for a way to do this. I don't think I'm planning on using luarocks, but having it clone git repositories into a packages directory. It's turning out to be useful for something else as well.

**Comment by alerque** [comment]
That sounds like [vim-plug](https://github.com/junegunn/vim-plug). I'm a long time user and only half a fan. Also for my own projects I'm using git submodules to version required packages, but that's a little harry too. my point with luarocks is that developing a package management system is a lot harder than it looks (have you followed the `nmp` vs. `yarn` war? It's hard to get right) and I don't want to reinvent a wheel that somebody else has fixed.

P.S. CTAN is the pits.

**Comment by simoncozens** [comment]
You're right. I've been thinking about plugins in Glyphs, which uses a "clone the git repository" approach. But that does nothing for dependencies.

**Comment by simoncozens** [comment]
PS Don't use CTAN! Use TeXLive and tlmgr!

**Comment by simoncozens** [comment]
OK, I looked at luarocks but it's not really simple to configure it in the way that we want: i.e. a) as an API that we can call from inside SILE, and b) to put the files it installs into a specific tree and make them available. So I have gone and implemented a simple package manager in e64f161. It essentially clones git repositories and makes them available to the SILE load path. Docs coming soon.

**Comment by alerque** [comment]
I haven't really reviewed what you hack in yet (at least not to the point of trying to use it) but given that your alternative to this idea is in the last release I think I'll close this issue off until such a time as I feel like making a case for something different.

**Comment by alerque** [comment]
I'm re-opening this issue because I think we should revisit the pros and cons of using `luarocks`. See also recent [comments in #324](https://github.com/sile-typesetter/sile/issues/324#issuecomment-693602129) [and #1059](https://github.com/sile-typesetter/sile/issues/1059#issuecomment-693539323). I still don't know whether re-purposing Luarocks or re-inventing the wheel is going to be better, but at the very least I think the decision should be re-evaluated.

**Comment by alerque** [comment]
Given the idea of using the `luarocks` tool with our own package registry (not luarocks.org, our own repository of manifests), and probably providing a CLI wrapper that called `luarocks` with the relevant repository and tree paths so that people don't have to fill them out by hand...

Pros:

* Nested dependency tracking (this is hard to write from scratch)
* Proper dependency versioning with all needed operators
* Track Lua interpreter version as a dependency (with Lua & LuaJIT this is starting to matter)
* System, Home directory, and project local installation options.
* Easy integration with *actual* LuaRocks, something that can be project dependencies—hence people only need one tool not multiple.
* Easy integration with other languages (packages could include C, Rust, etc).
* Baked in support for packages that require building rather than just copying sources (supporting several build systems including custom ones)

Cons:

* Confusion about what should be given a home as a LuaRock vs. what should be a SILE package.
* Rockspec version management is a minor fiasco (requires renaming files to bump versions)
* No lockfile support by default (although relatively easy to retrofit, see SILE's Makefile).

Alternative tools or models:

* vim-plug (& friends: pathogen, deinit, etc.) (also similar to Glyphs plugins)
* Git submodules (very precise control and ultimate flexibility, but cat get sticking even with my pretty advanced level of Git foo)
* cargo (by far the best language package manager experience I know of)
* npm/yarn (yes they could be re-purposed to distribute Lua code)
* go (...can die in a fire, this is an anti-model)

**Comment by alerque** [comment]
Hey @hishamhm, I was wondering if you might have any input here.

* Do you consider `luarocks` (either directly or via a wrapper that feeds it a config) a viable way to manage packages that are basically plugins for this specific Lua based application where the primarily content being distributed is Lua code (but not exclusively: images, text files, other code, etc. could be included)?
* Would keeping packages that doesn't have any general utility to Lua users and only make sense to be consumed by SILE on Luarocks.org under a dedicated manifest make any sense, or would hosting our own manifest server or some other kind of simplified directory for them make more sense?

**Comment by hishamhm** [comment]
> Do you consider luarocks (either directly or via a wrapper that feeds it a config) a viable way to manage packages that are basically plugins for this specific Lua based application where the primarily content being distributed is Lua code (but not exclusively: images, text files, other code, etc. could be included)?

Mostly yes, but non-Lua code is still a little awkward. But it's probably about time we think about fixing this. What does the use case look like in concrete examples, i.e. where would you install those files? (My original concern about supporting arbitrary files has been mostly about worries with messing with files and folders belonging to other applications, as it's generally easier to assume that something like `/usr/local/share/lua/5.*` is under the control of LuaRocks than some more general path like, say, `/usr/local/share/icons`).

> Would keeping packages that doesn't have any general utility to Lua users and only make sense to be consumed by SILE on Luarocks.org under a dedicated manifest make any sense, or would hosting our own manifest server or some other kind of simplified directory for them make more sense?

I wouldn't mind any of these options, including just plain using the LuaRocks root manifest! In any package repository there are subsets of packages that are designed to work together, and those that are entirely incompatible. For example, Kong plugins live in the root repository and that works fine. The Torch community maintained its own separate manifest server. Both approaches work, but I generally think that just using the root manifest provides more opportunities for cross-pollination, even if only at the visibility level.

**Comment by alerque** [comment]
Thanks @hishamhm, that's useful feedback.

> Mostly yes, but non-Lua code is still a little awkward. But it's probably about time we think about fixing this. What does the use case look like in concrete examples, i.e. where would you install those files? (My original concern about supporting arbitrary files has been mostly about worries with messing with files and folders belonging to other applications, as it's generally easier to assume that something like `/usr/local/share/lua/5.*` is under the control of LuaRocks than some more general path like, say, `/usr/local/share/icons`).

The arbitrary files I have in mind would make sense to install side by side with the Lua code and referenced using paths that are relative to the Lua module. For example consider the example of a document class, lets say one for CV's called ‘curriculumvitae’. This might be a requirement for a SILE document that looks like this:

```sile
\begin[class=curriculumvitae]{documnet}
\name{Foo Bar}
\entry[start=2016,end=2018,category=education]{My School}
\entry[start=2016,end=2018,category=awards]{That Cup}
\end{document}
```

Now maybe the class includes some images, say SVG icons that go next to section headings. We can suppose that it also has a helper package. The files might look like this:


```
Package root
└─ classes
   ├─ curriculumvitae.lua
   └─ icons
      ├─ awards.svg
      └─ education.svg
```

When SILE sees a document class, it checks all off Lua's `package.path` entries for `classes/?.lua`. We also populate the `package.path` with SILE's installation directory as well as `$PWD` so that project-local classes get found. It would make sense to me that the extra icon files would just be alongside the source that requires them. Hence the package root for this could be `/usr/local/share/lua/5.x/sile-curiculumvitae` or `$HOME/.luarocks/lib/lua/5.3/sile-curiculumvitae`, or of course relative to the current project.

I wouldn't expect to be able to install anything outside the scope of where the Lua module would naturally end up.

**Comment by hishamhm** [comment]
> I wouldn't expect to be able to install anything outside the scope of where the Lua module would naturally end up.

In that case then yes, it should be all supported in the current version of LuaRocks, the only issue being that the syntax for non-Lua files in the rockspec is a little awkward. See for example: https://luarocks.org/manifests/sailor/sailor-0.5-4.rockspec

**Comment by alerque** [comment]
Wow that is a little bit obtuse, but given the alternative is writing our own package manager it's probably workable. I imagine we could do a little bit of creative Lua work there to make it simpler to maintain a file list too.

**Comment by hishamhm** [comment]
Since LuaRocks 3, it does a best-effort auto-detection of .lua files if you don't add the explicit list of modules, but it's generally hard for LuaRocks to do a lot of guessing given the lack of standards in the Lua world (some people want to take a tree of files from their repo and install them flat, others have a flat list in their repos and install them on a tree structure, and all sorts of in between... so we ended up just having people declare in the rockspec each input file and output module name...)
