### ISSUE TITLE
Documentation lacking

### ISSUE THREAD

**Issue by simoncozens** [sile-typesetter/sile#548]
The following areas should be documented:

* [x] Folios: how to turn them off, style them, etc.
* [x] Chapterverse package
* [x] SVG package
* [x] Specimen package
* [x] URL package (incl. PDF hyperlinks)
* [x] Language-based hyphenators
* [x] `-` filenames for input and output
* [ ] #1779
* [x] Ruby class
* [x] `\cr` command, `\neverindent` command
* [x] Preamble(s)
* [x] Space-related settings (`shaper.spaceshrinkfactor` and friends)
* [x] Other shaper options (`harfbuzz.subshapers` etc)
* [x] `document.letterspaceglue` setting.
* [x] `languages.am.justification` setting.
* [x] `languages.fr.punctuationspace` setting.
* [x] `languages.fr.highpunctuation` setting.

(add others here by editing this issue)

**Comment by Omikhleia** [comment]
Ticking boxes vs. SILE 0.14.8 manual
- `languages.am.justification` is documented (section "Amharic") setting.
- French current settings ` languages.fr.thinspace`, `languages.fr.colonspace` and `languages.fr.guillspace` are documented (section "French") replacing the older settings.

**Comment by Omikhleia** [comment]
Ticking "Language-based hyphenators": the whole topic seems addressed, to me, in the manual "Hyphenation" (§8.3 as of SILE 0.14.9). If something else was expected, please comment.

**Comment by Omikhleia** [comment]
Letter class documentation split in its own issue, this one is therefore considered complete. Again, feel free to either re-open with details, or open dedicated issues for other lacking areas in the documentation.
