### ISSUE TITLE
Book gutter on wrong side by default

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#598]
The default language & layout of the *book* class is LTR, but the gutter margin (and assumed binding) is on the right. This should be reversed.

**Comment by ctrlcctrlv** [comment]
#1729:
> * https://github.com/sile-typesetter/sile/issues/598 (Book gutter on wrong side) Close (Rejected/Wrong): As discussed in PR 1621, this is not true. Move on...

**Comment by alerque** [comment]
c.f. #1621.
