### ISSUE TITLE
[verbatim] Couldn't find face with no name

### ISSUE THREAD

**Issue by Darkyenus** [sile-typesetter/sile#604]
This is a very strange bug. Minimal file required for replication is included [here](https://github.com/simoncozens/sile/files/3129437/fontbug.sil.zip), but the main part is here:

```tex
\begin[class=book]{document}
\script[src=packages/verbatim]
\font[filename=libertine-font/LinLibertine_R.otf]%Probably any font file
\define[command=verbatim:font]{\font[family="Menlo"]}%Other fonts may probably need more or less verbatim lines
\chapter{x }%Required, no idea why
\begin{verbatim}
x
x
x
[... and many more x's]
\end{verbatim}
\end{document}
```

This leads to error `! Couldn't find face  at fontbug.sil`, or with --trace:
```
! Couldn't find face '' at fontbug.sil
  at verbatim on line: 6, column: 1
stack traceback:
	.../local/Cellar/sile/0.9.5.1/share/sile/core/utilities.lua:53: in function 'core/utilities.error'
	.../Cellar/sile/0.9.5.1/share/sile/core/harfbuzz-shaper.lua:64: in local 'callback'
	/usr/local/Cellar/sile/0.9.5.1/share/sile/core/font.lua:98: in field 'cache'
	.../Cellar/sile/0.9.5.1/share/sile/core/harfbuzz-shaper.lua:35: in method 'shapeToken'
	...ocal/Cellar/sile/0.9.5.1/share/sile/core/base-shaper.lua:53: in method 'measureChar'
	...cal/Cellar/sile/0.9.5.1/share/sile/core/measurements.lua:111: in function <...cal/Cellar/sile/0.9.5.1/share/sile/core/measurements.lua:110>
	(...tail calls...)
	/usr/local/Cellar/sile/0.9.5.1/share/sile/core/length.lua:9: in method 'absolute'
	...ocal/Cellar/sile/0.9.5.1/share/sile/core/base-shaper.lua:33: in local 'f'
	/usr/local/Cellar/sile/0.9.5.1/share/sile/core/settings.lua:48: in field 'temporarily'
	...ocal/Cellar/sile/0.9.5.1/share/sile/core/base-shaper.lua:29: in method 'measureSpace'
	...ocal/Cellar/sile/0.9.5.1/share/sile/core/base-shaper.lua:143: in method 'makeSpaceNode'
	...cal/Cellar/sile/0.9.5.1/share/sile/languages/unicode.lua:28: in method 'makeGlue'
	...cal/Cellar/sile/0.9.5.1/share/sile/languages/unicode.lua:109: in function <...cal/Cellar/sile/0.9.5.1/share/sile/languages/unicode.lua:84>
```

In generated pdf, last ~5 characters are missing (X's span two whole pages and then the document ends). I don't think that different fonts will fix it, but they may require different amount of verbatim characters. The fact that `filename` with `family` font specification is mixed seems significant, as adding 

```lua
  measureSpace = function(self, options)
    local ss = SILE.settings.get("document.spaceskip")
    if ss then
      SILE.settings.temporarily(function()
        SILE.settings.set("font.size", options.size)
        SILE.settings.set("font.family", options.family)
        -- FOLLOWING LINE
        if options.filename then SILE.settings.set("font.filename", options.filename) end
        ss = ss:absolute()
      end)
      return ss
    end
```

to `base-shaper.lua:32` seems to fix it. But I have no idea why, because the replication criteria seem extremely arbitrary, so it almost seems like there is a different underlying issue. But I may be mistaken, so instead of opening PR, I'd like someone else, with deeper knowledge of the internals, to look at it.

**Comment by alerque** [comment]
I'm unable to replicate this bug at all, so it's kind of hard to verify what affects it. Can you comment on whether the recent merge of #607 changed this at all?

**Comment by Darkyenus** [comment]
It happens 100% regularly for me, even on `master` - OS X 10.11.6.

It is important that default font is set as `filepath` and `verbatim:font` is set as `family`. Omitting either font setting or reversing their types "fixes" the error. But it happens for each font file/family I have tested.

Try adding more lines (`x`'s), what is included is the minimum required to trigger the bug on my computer, but if you have slightly different font it may need more verbatim lines. There is no upper bound of verbatim content to trigger this, only lower bound.
