### ISSUE TITLE
Documents can compile on one system and not another

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#649]
One of the disadvantages of our current implementation using the host system's Lua to run SILE is that peoples' documents might render on some systems and not others even with the same version of SILE. I've already run into this with my own projects assuming Lua 5.3 locally, then shipping them off to be built in CI with some old container's relic of a Lua.

Consider the following (contrived) document:

```tex
\begin[papersize=a7]{document}
\begin{script}
SILE.registerCommand("pairs", function (options, content)
	SILE.typesetter:typeset(tostring(options.num // 2))
end)
\end{script}
Hello \pairs[num=5.64] worlds!
\end{document}
```

![image](https://user-images.githubusercontent.com/173595/59741383-88787200-9273-11e9-9ae8-745a2024a30f.png)

This will work fine if your system has Lua 5.3, but with older versions it will fail. Sure you _could_ fix it my using the older idiom of `math.floor()` instead of the `//` operator, but who should we expect to know that?

A kind of contrary example would be my own book template system that depends on a YAML parser.

```lua
local yaml = require("yaml")
```

This doesn't require a specific version of Lua, but it does require the `lua-yaml` rock to be available. At the moment I'm not supplying that in my SILE libraries, I'm assuming it exists on the system. Using and embeded version of Lua would probably make this harder, not easier. The version of Lua would be consistent but what (and where) it could reach out for on the system.

Possible solutions:

* Distribute our own Lua runtime so that at least **SILE X.Y.Z** will always  work on the same input.

* Throw a warning on...

    - New Lua's compiled without compatibility modes?
    - Any non-SILE Lua input?
    - Along with a trace any time SILE crashes on non-SILE Lua input?

* Document it and make people live with it. Having access to the system's Lua Rocks is too good to pass up, it lets people do whatever they want with their own content.

* ?

One of the biggest issues I see with bundling Lua is that it locks us into a preferred interpreter, which means either Lua or LuaJIT (limiting our approach to #536). Maybe that's a good thing, maybe not. The Windows installer is already going that way (#410) and its quite common in Linux applications as well (.e.g. Pandoc). Lua was in fact designed to make this possible, which is probably the single largest contributing factor to it's popularity.

**Comment by Omikhleia** [comment]
So seeing the CI failures: number rounding (1.0 vs. 1) and type conversions (operations on length/measurement, likely) behave differently in various versions of Lua. That's annoying.

**Comment by alerque** [comment]
I don't think this status-quo will change until such a time as SILE is shipped as a Rust binary with an embedded Lua runtime and API surface to change out all the internals for Lua. If/when that happens one can hope that either the embedded Lua runtime is LuaJIT fast or the bits implemented in Rust by default are fast enough to make up for the difference.

For now we're just making people live with:

* SILE out of the box works 100% on Lua 5.1, 5.2, 5.3, 5.4, LuaJIT, and OpenResty.
* 3rd party packages are responsible for defining their own Lua support ranges using standard Luarocks dependency specs.
* Documents that include custom Lua code are expected to manage their own P's and Q's and either always run under the compatible interpreters or use lowest common denominator functions. This will limit document portability to some extent but give distro packagers and end users the greatest lee-way in how they run their systems. That's our chosen compromise.
