### ISSUE TITLE
Graduate project to it's own github organisation

### ISSUE THREAD

**Issue by rjmunro** [sile-typesetter/sile#666]
I feel like this project is big enough to have it's own github organisation, rather than be in @simoncozens personal namespace.

It's very easy to create an organisation on Github. You can then move the project to the organisation. Multiple people can then be managers of the organisation, meaning the project can have a canonical home, even if Simon was to no longer be involved.

**Comment by alerque** [comment]
What a devilish idea! :smiling_imp:

**Comment by simoncozens** [comment]
Sounds good to me, especially since @alerque is doing far more of the coding / release management than I am these days. :-) Very happy to recognise that officially.
