### ISSUE TITLE
Refactor table.flip()

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#685]
Reaching into the default language functions in Lua is cool, but it also has unexpected consequences when interfacing with user provided Lua code. In the case of the SILE core its an anti-pattern that should be avoided just so we don't make headaches for ourselves and others down the road.

I refactored out `table.nitems()` and `table.append()` as part of #682, but `table.flip()` is a bit more involved. Since I'm also mucking about with Lua lint stuff in #681 and don't want to mix up that change, I'm leaving this issue as a note to deal with this one some other time.

**Comment by alerque** [comment]
Note after messing with it a little my thought is this should probably be turned into a utility function that returns a copy of a table rather than munging the original. The code that uses this could also benefit from some help with iteration such as provided by `pl.tablex.foreachi()`.

**Comment by Omikhleia** [comment]
`table.flip` was later replaced in #682 by `SU.flip_in_place` and is no longer to be found in the code (at least as of 0.14.9 as of now).
See also commit log on 6f1595d3881e8b0373514951ef8a59a401ae0547.

Therefore, closing this issue. If there was anything else about it (non-obvious, from the description and comments), feel free to re-open and clarify. The main concern was addressed, and whether working on the original table or on a copy is a somewhat a different topic (there are pros and cons) - but the current name of the utility, at least, reflects the reality of what it does.
