### ISSUE TITLE
Unfinished capture for French language

### ISSUE THREAD

**Issue by gcat432** [sile-typesetter/sile#702]
Having special characters in a French language document including `^$()%.[]*+-?` will throw this error:

```
Error detected:
        ./core/base-shaper.lua:84: languages/fr.lua:26: unfinished capture
```

It is because of the following code in `languages/fr.lua`:

```
return string.match(SILE.settings.get("languages.fr.highpunctuation"), text)
```

This method requires the `text` variable to be escaped on special characters. I quickly tested this code before the preceding call on a simple document with some special characters and it worked:

```
if text == "(" or text == ")" or text == "?" or text == "." then
  text = "%" .. text
end
```

I don't know a proper way to fix it so I prefer to open an issue rather than making a PR.

**Comment by alerque** [comment]
Thanks for this report @gcat432.

I'm curious can you also mention exactly what version of SILE you are using? I have been working through some general coding cleanup and ran across some stuff in the French language support file that was just bogus Lua syntax so whole chunks of the file were being ignored if anything at all was being loaded. I fixed that but the fix just landed it git recently (see #681, esp. dd44c51), so I'm wondering if you even have a version in which French works at all. Do you get hyphenation?

**Comment by alerque** [comment]
Also could you include a sample document exhibiting this problem? I speak a few languages but French isn't one of them so it would be nice to have a real example, something like:

```tex
\begin{document}
\language[main=fr]
something here
\end{document}
```

**Comment by alerque** [comment]
You can disregard my question about SILE versions, this is clearly happening in the latest master. In fact it looks like the error may have just _started_ showing up because I fixed the syntax in the file in the first place, this code wasn't even getting executed for a while so the issue with it wasn't apparent. Having a proper French test document would be nice though, can you give me a sentence or two that is proper French that (at least on a very small page size) will need hyphenating, and also has high-punctuation marks and guillemots to test that spacing is working correctly, and something that triggers this issue? Thanks!

**Comment by gcat432** [comment]
@alerque 

```
$ ./sile -v
SILE v0.9.5.1-405-g69cfffb
```

I do get hyphenation when I fix the escaping issue. In fact I am sorry my report was wrong at first: it only happen when parenthesis are present in the text, other characters are fine. This simple example will trigger it:

```
\begin{document}
\language[main=fr]

(Lorem ipsum dolor sit amet, consectetur adipiscing elit.)

\end{document}
```

**Comment by alerque** [comment]
@simoncozens You can't just flip it like that either, it needs some more magic like looking for any of a class of characters, not the whole string. Working on it.

**Comment by alerque** [comment]
@simoncozens That would still have the issue that `?` in the high-punctuation list is one of the characters you're trying to find and has special meaning to `strfind()` (any Lua string functions actually).

**Comment by alerque** [comment]
@gcat432 That's Latin not French. I want something French for a test file because I want to prove that the hyphenation is working correctly on French input, hyphenation patterns vary by language.

**Comment by gcat432** [comment]
@alerque Hyphenation is dependent of the font and size used and I don't have the default one "Gentium Plus" so I think that we need to agree on an if possible open source font we can both use for the test.

**Comment by simoncozens** [comment]
`strfind` is old Lua, apparently. We want the fourth argument to `string.find`: 

> A value of true as a fourth, optional argument plain turns off the pattern matching facilities, so the function does a plain "find substring" operation

**Comment by simoncozens** [comment]
(I would rather do this than have to escape the characters.)

**Comment by alerque** [comment]
@simoncozens Okay I'll flip that around, I didn't know about the way to turn off the pattern facilities.

@gcat432 How about this:

> Il était une fois, dans un pays très lointain (dont le nom périlleux ne doit pas être prononcé), vivait Bernadette, qui nous disait « Rien d’important! ». As tu entendu?

![image](https://user-images.githubusercontent.com/173595/67560672-0833b300-f724-11e9-95ef-868325f6d4b2.png)

It might be rubbish (Google Translate) but it has high and low punctuation, guillemots, parenthesis, and also happens to hyphenate twice with the test suite's font defaults.

**Comment by gcat432** [comment]
@alerque I suggest a classic public domain book like Alice's Adventures in Wonderland (1866).

You can find a French translation here, maybe you can use the first paragraph whether it works well:
https://fr.wikisource.org/wiki/Alice_au_pays_des_merveilles/1

**Comment by alerque** [comment]
Thanks, I did try that first paragraph and it does mostly work if I hack in a par of parenthesis --- what doesn't work it SILE's line breaking. It's breaking lines leaving a hanging guillimont. Buggers.

Also we do apparently have a French test (bug-621.sil) but it isn't showing whether guillemot handling is correct nor does it include any parenthesis.

**Comment by gcat432** [comment]
If you prefer to use your text for the test, here is a corrected version:

> Il était une fois, dans un pays très lointain (dont le nom périlleux ne doit pas être prononcé), vivait Bernadette, qui nous disait « Rien d’important ! » As-tu entendu ?

**Comment by gcat432** [comment]
If you prefer to use your text for the test, here is a corrected version:

> Il était une fois, dans un pays très lointain (dont le nom périlleux ne doit pas être prononcé), vivait Bernadette, qui nous disait « Rien d’important ! » As-tu entendu ?

**Comment by alerque** [comment]
Thanks again for reporting this @gcat432, the fix is in `master` now so you should be able to update and keep working with French. Do let us know if other things come up. We're hardly experts in all the languages and orthographies SILE is supposed to handle.

**Comment by gcat432** [comment]
I confirm that your pull request fixes the issue. Thank you!
