### ISSUE TITLE
Failed to build on macOS

### ISSUE THREAD

**Issue by hajimehoshi** [sile-typesetter/sile#711]
```
$ make
find: lua_modules: No such file or directory
find: lua_modules: No such file or directory
touch: illegal option -- d
usage:
touch [-A [-][[hh]mm]SS] [-acfhm] [-r file] [-t [[CC]YY]MMDDhhmm[.SS]] file ...
make: *** [.lastcommit] Error 1
```

I'm not familiar with Lua system. I am not sure what I am missing.

**Comment by simoncozens** [comment]
It looks like we need the GNU core utils to be installed (and in the path) for the `touch` command to work. One workaround is to run `brew install coreutils` and add them to your path:

```
PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:$PATH"
```

Perhaps a better approach would be to rewrite the offneding Linuxisms in something more portable: Perl, or perhaps even Lua itself.

**Comment by alerque** [comment]
Did you run `./bootstrap` and `./configure` before this? Are you sure both of those returned no errors? Simon is right I was using a GNU specific option to touch (I'll just remove that and use a POSIX compliant one instead) but there is another problem before that I think.

**Comment by hajimehoshi** [comment]
> Did you run ./bootstrap and ./configure before this? Are you sure both of those returned no errors? 

Yes, and they didn't have errors.

**Comment by alerque** [comment]
I just fixed the issue with touch by reading the man page for BSD's version. These arguments work fine on GNU as well, they are just a bit less convenient to write. I don't see any problem with just fixing the utilities to work on either POSIX or GNU versions by using a lowest common denominator approach, in this case we're not going to need anything too fancy.

That being  said I am curious whether we're anywhere close to working on BSD make. I kind of doubt it. @simoncozens I think you've mentioned before some of my fancy-pants stuff only worked when you ran it in `gmake`. I may need to dig up a system to test on to fix that -- I wonder if I can get Github Actions or Travis to run an OSX check for us...

**Comment by hajimehoshi** [comment]
The building started with #712 (thank you!), but I found another errors:

```
Making all in src
  CCLD     justenoughicu.la
ld: library not found for -licui18n
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [justenoughicu.la] Error 1
make: *** [all-recursive] Error 1
```

I think this is due to environment variables. Let me think...

**Comment by alerque** [comment]
Hmm. It seems like `./configure` should have found ICU (if you have it) or errored (if you don't), and if you have it I don't understand why that reference wouldn't work to load it. For example it tells me:

```autoconf
checking for ICU... yes
```

Hopefully @simoncozens can help with that part because I don't have a system to test on.

**Comment by alerque** [comment]
What does `pkg-config` tell you about where ICU is?

For example the flags it suggests I use are:

```sh
$ pkg-config --libs icu-i18n
-licui18n -licuuc -licudata
```

**Comment by hajimehoshi** [comment]
After setting 

```
export PKG_CONFIG_PATH=/usr/local/opt/icu4c/lib/pkgconfig 
```

and rerunning `./configure`, it looked like building succeeded!

```
hajimehoshi@Hajimes-MacBook-Pro ~/sile 
$ make
Making all in libtexpdf
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
Making all in src
cp .libs/justenoughharfbuzz.so .libs/justenoughfontconfig.so .libs/macfonts.so .libs/justenoughlibtexpdf.so .libs/fontmetrics.so .libs/svg.so .libs/justenoughicu.so ../core
cd . && bash ./config.status sile
config.status: creating sile
hajimehoshi@Hajimes-MacBook-Pro ~/sile 
$ ./sile -v
SILE v0.9.5.1-413-gda03715
```

**Comment by alerque** [comment]
Not having the right `PKG_CONFIG_PATH` for your system is not really something we can fix on the code side of things. A system with a working ICU and proper tools to compile against it is a prerequisite for building from scratch. That being said I would be happy to see something in the install documentation helping people through that step if this is a common problem on OSX.

I've fixed the code bug that was blocking things, but I don't know where you came up with that path or what to tell future people to check. Perhaps you could write up a PR with instructions for coming up with that setting for the readme and/or manual.

**Comment by hajimehoshi** [comment]
I installed `icu4c` via Homebrew. When executing linking `icu4c` after installing, brew complained like this:

```
$ brew link icu4c
Warning: Refusing to link macOS-provided software: icu4c
If you need to have icu4c first in your PATH run:
  echo 'export PATH="/usr/local/opt/icu4c/bin:$PATH"' >> ~/.bash_profile
  echo 'export PATH="/usr/local/opt/icu4c/sbin:$PATH"' >> ~/.bash_profile

For compilers to find icu4c you may need to set:
  export LDFLAGS="-L/usr/local/opt/icu4c/lib"
  export CPPFLAGS="-I/usr/local/opt/icu4c/include"

For pkg-config to find icu4c you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig"
```

Then, as long as a user installs `icu4c` via brew, they should notice. I don't know the other way to install `icu4c`. Should we add notes about this to README?

**Comment by simoncozens** [comment]
OK, that's weird. I must have somehow managed to convince Homebrew to link  /usr/local/lib/pkgconfig/icu-i18n.pc at some point in the past:

```
$ ls -ald /usr/local/lib/pkgconfig/icu-i18n.pc
lrwxr-xr-x 1 simon staff 49 Apr 22  2019 /usr/local/lib/pkgconfig/icu-i18n.pc -> ../../Cellar/icu4c/64.2/lib/pkgconfig/icu-i18n.pc
```

What's even weirder is that brew is now saying that it is "macOS-provided software". This should mean that icu4c *is* installed by the OS, and so should be findable by software which uses it...

**Comment by simoncozens** [comment]
Huh: https://github.com/Homebrew/homebrew-core/blob/6a81ed1b388cbe4e3b7bb5b0255685e6c5078cca/Formula/icu4c.rb#L16

**Comment by simoncozens** [comment]
So yes, it looks like a note in the README/manual is the way forward here, unfortunately.

**Comment by hajimehoshi** [comment]
OK I'll try to add a note.
