### ISSUE TITLE
Unexpected 'glyph(s) not available' errors from font-fallback package

### ISSUE THREAD

**Issue by hajimehoshi** [sile-typesetter/sile#716]
I tested this with SILE c0542ca6715946192fdfe4abb239a3ea6705d784

```
\begin[class=jbook]{document}

\script[src=packages/font-fallback]

\font[family=Roboto]
\font:add-fallback[family=Noto Serif CJK JP]

こんにちは!

\end{document}
```

```
$ sile test.sil
This is SILE v0.9.5.1-413-gda03715
<test.sil>

! Some glyph(s) not available in any fallback font, run with '-d font-fallback' for more detail at in "␤␤こんにち…"

! Some glyph(s) not available in any fallback font, run with '-d font-fallback' for more detail at in "␤␤こんにち…"

! Some glyph(s) not available in any fallback font, run with '-d font-fallback' for more detail at in "␤␤こんにち…"

! Some glyph(s) not available in any fallback font, run with '-d font-fallback' for more detail at in "␤␤こんにち…"
[1] 
```

**Comment by hajimehoshi** [comment]
A similar error happens even with `book`:

```
\begin[class=book]{document}

\script[src=packages/font-fallback]

\font[family=Roboto]
\font:add-fallback[family=Noto Serif CJK JP]

あ

\end{document}
```

```
$ sile test.sil
This is SILE v0.9.5.1-413-gda03715
<test.sil>

! Some glyph(s) not available in any fallback font, run with '-d font-fallback' for more detail at in "␤␤あ␤␤"
[1] 
```

**Comment by alerque** [comment]
My previous fix for this appears to have not covered all the possible cases correctly.

In addition to not throwing the right messages, edge cases possible related to #647 also throw different messages AND with different position info about where the message was thrown depending on white space following the characters.

```tex
\begin{document}
\script[src=packages/font-fallback]
\font:add-fallback[family=Noto Serif CJK JP]
ん

\end{document}
```

With the blank line ending the paragraph this throws a glyph warning, without that line no warning is thrown.

**Comment by alerque** [comment]
I don't think my "fix" was the problem here, something is wonky about the actual looping logic. We probably need variable to track the overall pass/fail status, but it isn't immediately apparent to me what that should be.

The diff [since 8e42979c](https://github.com/sile-typesetter/sile/compare/8e42979c...master#diff-e5820cdb274a629d0481a8b31512052a) has a lot of noise, but most of it is refactoring and I don't think the fundamental logic has changed. Here is a diff view with whitespace changes and such ignored so the highlighting is more useful:

![image](https://user-images.githubusercontent.com/173595/71978524-9e0fb200-322c-11ea-91ae-7575c58f5a03.png)

@simoncozens I'm assigning this one to you because I still can't get my head around what is actually happening there. All I was trying to do is make the error messages useful, but what it says on the tin doesn't seem to be what's actually happening.

**Comment by Omikhleia** [comment]
(Observed with SILE 0.12.4 on Ubuntu 20.04, but I don't see any reason it would be different in SILE 0.13.0)

I likely met the same issue without any Japanese -- so the title of the issue (referring to "jbook") should at least be changed.

```
\begin[papersize=a6]{document}
\script[src=packages/font-fallback]
\language[main=en]
\font[family=Libertinus Serif]
\font:add-fallback[family=Symbola]

Ballot box with check (U+2611) is not in Libertinus, so fallback to Symbola: ☑

\end{document}
```
Getting:
`! Some glyph(s) not available in any fallback font, run with '-d font-fallback' for more detail at in "␤␤Ballot box with …"`

The output is correct, though:
![image](https://user-images.githubusercontent.com/18075640/174409997-e8624093-1955-4857-8b70-fab55760d505.png)

Would be nice to fix this... As might be guessed, those ballot box are useful for Markdown task lists ("GitHub flavor"). 
Or maybe I should ask the Libertinus maintainers to consider adding them :rofl: (Just kidding)

**Comment by alerque** [comment]
The language and class are irrelevant. As show above this isn't even about the specific character that is "missing", it is about the character being searched for being found at the end of a line/paragraph. Note either removing the empty line or adding a string to to the paragraph makes your MWE pass:

```sile
\begin[papersize=a6]{document}
\script[src=packages/font-fallback]
\language[main=en]
\font[family=Libertinus Serif]
\font:add-fallback[family=Symbola]

Ballot box with check (U+2611) is not in Libertinus, so fallback to Symbola: ☑ foo

\end{document}
```
...or...

```sile
\begin[papersize=a6]{document}
\script[src=packages/font-fallback]
\language[main=en]
\font[family=Libertinus Serif]
\font:add-fallback[family=Symbola]

Ballot box with check (U+2611) is not in Libertinus, so fallback to Symbola: ☑
\end{document}
```
