### ISSUE TITLE
What should be allowed in units and command names?

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#721]
Trying to fix some Lua scoping issues across the SILE code base I happened to notice some of the LPEG parsing is gibberish. Trying to fix it I notice some of it is probably not working as intended, but I'm not 100% clear on the intention.

1. Should units be allowed in upper case and normalized?

    Right now only lower case letters are allowed in units. I could easily see this being a good rule, but I can also think of a case where somebody was converting from another format that had, for example, CSS units which can be upper case. Forcing the user to convert these rather than just parsing them out of the box seems unnecessary. Should `1REM` be a valid unit interpreted as `1rem`?

2. What characters should be allowed in command names?

    Right now they may contain any upper or lower case letters, digits, underscore, colon, or hyphens. They may start with a colon, hyphen, underscore, or letter (but strangely not a digit!). Lots of languages have good reasons for starting identifiers with letters not digits, but typically they also avoid starting with `:` or `-` except in cases where that has meaning, such as `-` in Fluent being for private scope terms.

3. What should be allowed as frame names? Parameter names? Setting names?

   Currently start with letter or underscore, after with also digits.

   Dot is not allowed in frame names, but is is parameter and setting names where the resulting pseudo-scoping is entirely hand-waving, really its just part of the identifier.

My suggestion is to:

1. Allow any case input for unit matching, but normalize on lower case internally (so `REM` and `rem` would be the same unit).

2. Only allow letters or underscores as first character in command identifiers; then any amount of letters, underscores, digits, colons, or hyphens; followed by the last character being a letter, underscore or digit. (i.e not beginning with `[0-9:-]` and not ending with `[:-]`). My logic for excluding trailing `:` and `-` is to make their use as pseudo namespace separators more robust. Composed values would die with logical errors rather than silently allowing an empty value like `\my-space-${val}` to fall though to `\my-space-` which might be confused with `\my-space`.

3. I think this is fine. No pseudo namespacing for frame names (if we ever do nesting or inheritance of any kind that can be added) and the pseudo scoping of parameters and settings can stay, we might even be able to build more convenient functions based on them.

Thoughts?

**Comment by simoncozens** [comment]
1) I would say go for lowercase only. I see the point about allowing uppercase, but whenever I put automagic into SILE stuff it usually blows up in my face (actually more usually your face) and you tell me to take it out again. :-)

2) I was aiming at the XML element name definition, so that we are guaranteed to parse XML files, but never actually looked it up. It should at least be a superset of that. Here it is: https://www.w3.org/TR/xml/#NT-Name

3) I think it's fine too.

**Comment by alerque** [comment]
Just a note on the topic number 2 here —

The allowed character list for commands has been borked forever: we had different rules for single character commands than multiple character commands.

This got fixed as a side-effect of work in #940, but it has just occurred to me that the new implementation is overly complex. Rather than allowing a few exception commands for things that wouldn't otherwise be valid command names (like `\%`), then creating a registered command to output the character, we should just not allow these names as commands at all. This would free us up to let the PEG‌ grammar spot and remove the escapes where needed and pass clean data for a more logical AST in the first place.

cc: @ctrlcctrlv

**Comment by ctrlcctrlv** [comment]
@alerque Huh? Sorry, I definitely think `\%` should be a valid command, but if you're going to remove it, yes, I am happy to add it to sile-texmode, which I use for all my documents.

**Comment by alerque** [comment]
Why? I could be missing something, but‌ I don't see the logic. Other than acting as an escape for otherwise normal input, all we do is ruin shaping with a nested AST element than serves no purpose.

Why should input like `my number is $6` result in a simple string in the AST‌:

```
content = { "my number is $6" }
```

but `my number is \%6` result in a mess:

```
content = { "my number is", { cmd = "%" }, "6" }
```

...when what you want as output is just the string and the command is just a hack to escape the input?

**Comment by ctrlcctrlv** [comment]
Oh, I see what you mean. So, you won't break it in output, you'll just escape it. Clever. Yes, good plan. So ctrlcctrlv/sile-texmode#1 is _not_ what you want. I thought you were going to just start rejecting documents with `\%` as invalid.

Aside:

Hmmm...also, I have no idea how GitHub orgs work, but would it be possible to make ctrlcctrlv/sile-texmode sile-typesetter/texmode without giving me any "power" (push access, etc) over sile-typesetter/sile? While typing out "ctrlcctrlv/sile-texmode#1" I thought of how janky that name for the repo is.

**Comment by alerque** [comment]
> I thought you were going to just start rejecting documents with `\%` as invalid.

No no `%` has special meaning in the language so of course it needs an escape so you can get a literal percent sign in your input. The only question is when do we process the escapes? Right now they are being done at the last minute –after the fact even– by using a command to stuff glyphs back in the output via the typesetter. My idea is that it would be better to move those *way* up in the chain and be dealt with in the initial grammar parsing, thereafter the content as SILE processes from it's internal AST would be just the whole text as the user thinks about it.

> [...] how GitHub orgs work, but would it be possible to make ctrlcctrlv/sile-texmode sile-typesetter/texmode [...]

Yes, it would. And I'd definitely consider something like that, but lets hold off a little bit and see how it shapes up just a bit more. I expect it will change shape a little as you get farther along and it might be more clear where to move it later. Whether we move it to core or keep it as an add-on repository is still an open question. I think the development cycle would be easier to handle as it's own repository, lets see how it goes for a while. It's relatively easy to migrate repositories (and GitHub takes care of redirecting old links) but it gets really messy if you do it twice!

I‌ could also see us having a dedicated packages org. Honestly I need to take a good look at what Simon started to do with a package index repository. I haven't even used it yet, but I feel like the shape of the ecosystem is still a bit up in the air and needs some thought. For the moment I'd like to suggest just keeping the status quo for a little while, and we can migrate/merge when we're confident about the overall arrangement. But yes if there is any interest in this & other packages having a home near SILE's own repo that is something we can probably do.

**Comment by ctrlcctrlv** [comment]
@alerque No problem. I tend to ask things when I think of them, because if I don't, I forget to ask, usually forever :-)

For example, you just reminded me of a bug I was supposed to report last week, let me see if I can repro it...

**Comment by alerque** [comment]
@simoncozens For the moment this bit is going to remain a dream:

> I was aiming at the XML element name definition, so that we are guaranteed to parse XML files, but never actually looked it up. It should at least be a superset of that. Here it is: w3.org/TR/xml/#NT-Name

The XML namespace spec allows a bizarrely vast range of characters. If Lua even supported multibyte UTF8 it would look something like this:

```lua
local XMLNameStartChar = lpeg.S":_" + SILE.parserBits.letter + lpeg.R"ÀÖ"
  + lpeg.R"Øö" + lpeg.R"ø˿" + lpeg.R"Ͱͽ" + lpeg.R"Ϳ῿" + lpeg.R"‌‍"
  + lpeg.R"⁰↏" + lpeg.R"Ⰰ⿯" + lpeg.R"、퟿" + lpeg.R"豈﷏" + lpeg.R"ﷰ�" + lpeg.R"ᄑ󯿿"
local XMLNameChar = XMLNameStartChar + SILE.parserBits.digit + lpeg.S"-.·"
  + lpeg.R"̀ͯ" + lpeg.R"‿⁀"
SILE.inputs.TeXlike.identifier = XMLNameStartChar * XMLNameChar^0
```

... but it does not. The only solution I know of is using the Lua ICU regex module to build functions that detect byte rages based on those expressions, then teach LPEG about them with capture groups that do their own matching based on the return of those functions. This would involve iterating a host of regular expressions on every byte of input. I didn't actually benchmark doing that yet — it's so ugly I didn't feel like even starting down that road.

If full (or even anything remotely close to) XML tag naming is ever going to be our actual rule I think what I'd need to do is write a Lua module in Rust that offloads the PEG grammar parsing to someplace with proper UTF8 support. Since the parser itself is one thing that isn't really extensible via Lua at runtime anyway this might not be a bad way to go, but it beyond the scope of my current tweaks to the PEG grammar.

**Comment by ctrlcctrlv** [comment]
If what's needed are Unicode ranges, it may make sense to encode command names internally as UTF-32, and work on them as integer arrays, not Lua strings, until final write out.

**Comment by alerque** [comment]
@ctrlcctrlv There are several ways to store and ever manipulate such data in Lua, the issue is that LPEG isn't one of them. None of it's native grammar functions support multi-byte sequences.

**Comment by ctrlcctrlv** [comment]
Ah, okay; I was under the impression lpeg could work on data of any type
