### ISSUE TITLE
rules package doesn't respect text advance direction

### ISSUE THREAD

**Issue by simoncozens** [sile-typesetter/sile#723]
```TeX
\begin[papersize=a5]{document}
\script[src=packages/rules]
\thisframeRTL

A \hrule[width=200pt,height=5pt] B
\end{document}
```

**Comment by alerque** [comment]
I *might* have fixed this already. I found a couple such direction bugs actually while refactoring stdlib out of the code as part of #682. You might wait to try to fix this until that lands (it's currently not in operational order and I just got back from traveling).

**Comment by simoncozens** [comment]
No, it's still a bug.
