### ISSUE TITLE
Pagination error in manual (even/odd)

### ISSUE THREAD

**Issue by simoncozens** [sile-typesetter/sile#750]
The manual currently begins on the (unlabelled) page *2*, not page 1. From then on, we have odd pages on the left and even pages on the right.

We *probably* want to replace the pagenumber-nobbling code with:

```
\chapter{What is SILE?}
\set-counter[id=folio,value=1]
```

but I want to think a bit more if that's the right approach.

**Comment by alerque** [comment]
Personally I hate print books that don't make their PDF counterpart's page numbers so much that I've been publishing books with pages numbered starting at 1 for the half title page, 2 for the title page and so on. The first folio drawn is usually at least page 9 or 10. I know this bucks a most book publishing trends, but in a mixed digital and print world I find it worthwhile to make it easy to jump to the same content in another medium.

**Comment by Omikhleia** [comment]
As of current (0.14.9)
- The manual starts with with two unnumbered pages, then roman pages, then arabic pages.
- The above suggestion (`\set-counter[id=folio,value=1...]` in the "What is SILE?" chapter is actually there...

So the issue as it was formulated is invalid.
Feel free to open a correct issue and/or a PR if you think something should be changed in the manual.
