### ISSUE TITLE
attempt to call a nil value (field 'object')

### ISSUE THREAD

**Issue by Earnestly** [sile-typesetter/sile#787]
* sile: v0.10.0.r35-g99ec746
* lua: 5.3.5

I'm not too familiar with lua and am unsure what is causing this:

```sh
% sile
/bin/lua: /usr/share/sile/core/sile.lua:36: attempt to call a nil value (field 'object')
stack traceback:
        /usr/share/sile/core/sile.lua:36: in main chunk
        [C]: in function 'require'
        /usr/bin/sile:36: in main chunk
        [C]: in ?
```

**Comment by simoncozens** [comment]
OK, it looks like this means the `std` library is not properly installed. Did you use `--with-system-luarocks` when you run `./configure`? Could you try running lua from the command line:

```
$ lua
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
> require("std")
```

and tell me the output?

**Comment by Earnestly** [comment]
I should have mentioned some of my efforts to debug:

```
% lua
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
> std = require("std")
> foo = std.object
> foo = std.object {}
stdin:1: attempt to call a nil value (field 'object')
stack traceback:
        stdin:1: in main chunk
        [C]: in ?
>
```

From this I tried removing the `{}` from `sile.lua` but that only resulted in further errors of the same nature in `baseclass.lua` - this is where I stopped out of ignorance.

**Comment by Earnestly** [comment]
This is increasingly looking like my installation of `lua-stdlib` is wrong.

**Comment by alerque** [comment]
This sounds to me like stdlib doesn't understand it's own paths or something like that.

Does `sile -t` by any chance give you more detailed trace information? It probably will not at this point but it might be worth trying.

**Comment by Earnestly** [comment]
It's strange, the `stdlib` from github doesn't contain `std.object` while the installation from `luarocks` does.  I'll have to investigate this more fully, it is very unlikely a problem with `sile` so I'm going to close it for the time being.

**Comment by Earnestly** [comment]
Oh, this might explain it: https://github.com/lua-stdlib/lua-stdlib/blob/master/NEWS.md#incompatible-changes

**Comment by alerque** [comment]
Oh thanks for that heads up! That does explain it.

Hopefully we will have completely deprecated stdlib and removed it from SILE before they release that as stable so we don't have to worry about people that get it packaged. I was hoping that would be _this_ release, but the process of extricating it is pretty involved and likely to drag out a bit longer yet. Our class system still uses that object model...
