### ISSUE TITLE
Document full dependencies for --with-system-luarocks

### ISSUE THREAD

**Issue by simoncozens** [sile-typesetter/sile#795]
penlight, linenoise, etc. are required without us mentioning that anywhere.

**Comment by alerque** [comment]
For now the best place to check is the rockspec at `sile-dev-1.rockspec`, with the caveat that Lua version matters. Luarocks knows whether those are or are not needed for various versions of Lua. But32 is only needed for 5.1, compat53 is needed for 5.2 and below.

**Comment by alerque** [comment]
Also note the rockspec should be updated with notes about the minimum versions as we know them. Cassowary needs to be the latest, for everything else I don't think it much matters. The rockspec has current released versions that we've tested with which is great for consistent bundling, but it's not so nice for system packages which can often be behind.
