### ISSUE TITLE
Add self-check make target

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#835]
We need a "light" version of `make test` that doesn't run full regressions tests but does do some kind of internal self-check to make sure we can parse input and generate output. Right now we are in various places either recommend people compile the manual (huge time waster plus requires fonts, etc.), the examples (confusing to get to, also slow), the full regression tests (require fonts, slow), or just check `--version` (it turns out that doesn't validate libtexpdf is even working). I'm using `make busted` for the Arch Linux packaging, but that adds dependencies.

A light self check that just makes sure the cogs are turning would be nice to give as a tool to distro packagers.

**Comment by simoncozens** [comment]
This is what examples/simple.sil is designed for. Can we just add a .expected for that?

**Comment by alerque** [comment]
No because we don't want to test the debug backend output, we want to test the pdf output. Even `sile -o test.pdf <<< "<sile></sile>"` would be enough I think, we just want to know it runs without errors. I just need to try a few failure cases I've run into lately.
