### ISSUE TITLE
Page numbers not aligned in table of contents in manual v0.10.2

### ISSUE THREAD

**Issue by OlivierNicole** [sile-typesetter/sile#859]
The title says it all, I think. They used to be aligned in previous versions.

**Comment by alerque** [comment]
Confirmed in v0.10.4 and git HEAD.

**Comment by simoncozens** [comment]
This line in tableofcontents:item appears to be messing things up:

```
SILE.settings.set("typesetter.parfillskip", SILE.nodefactory.glue())
```

**Comment by simoncozens** [comment]
Actually even without that it isn't particularly lovely.

**Comment by simoncozens** [comment]
Here's an example that doesn't use tableofcontents:

```
\begin[pagesize=a5]{document}
\script[src=packages/frametricks]
\showframe
\script[src=packages/leaders]
\noindent\font[size=20pt]{ABC\dotfill{}1}\medskip
\noindent\font[size=10pt]{DEF\dotfill{}10}\medskip
\noindent\font[size=10pt]{GHI\dotfill{}100}\medskip
\end{document}
```

**Comment by simoncozens** [comment]
Oh dear, I'm being an idiot. Of course that one doesn't work because of the parfillskip. Here's another example. Something seems to be going wrong in the glue calculation when repetitions > 1. It's fine for <1 and ==1.

```
\begin[pagesize=a5]{document}
\script[src=packages/frametricks]
\showframe
\script[src=packages/leaders]
\set[parameter=typesetter.parfillskip,value=0pt]
\noindent\font[size=20pt]{A\dotfill{}A}\medskip
\noindent\font[size=10pt]{DEF\dotfill{}10}\medskip
\noindent\font[size=10pt]{GHI\dotfill{}100}\medskip

\noindent\font[size=10pt]{GHI\hfill{}100}\medskip

\end{document}
```

**Comment by alerque** [comment]
Currently `\dotfill` is defined as:

```lua
SILE.call("leaders", { width = "0pt plus 100000pt" }, { " . " })
```

Removing the spaces from the fill makes this alignment issue go away:

```lua
SILE.call("leaders", { width = "0pt plus 100000pt" }, { "." })
```

This probably has to do with spaces being stretchy and the stretchy glue we are using to get the alignment right getting _also_ applied to spaces?

**Comment by alerque** [comment]
Found it. Patch coming soon.
