### ISSUE TITLE
Pullquote with several paragraphs shows wrong indentation

### ISSUE THREAD

**Issue by OlivierNicole** [sile-typesetter/sile#865]
Trying to put several paragraphs in a pullquote, the first paragraph came out unindented (which is normal), but so did the second.

![image](https://user-images.githubusercontent.com/14031333/80868272-c6b72e00-8c99-11ea-92cd-72866720da16.png)

(The last line of every paragraph is stretched, but that’s an easy fix.)

I couldn’t find why this is happening. I only noticed that when commenting out [the mark typesetting](https://github.com/sile-typesetter/sile/blob/master/packages/pullquote.lua#L42), the second paragraph *is* indented.

**Comment by alerque** [comment]
My eyes start twitching and I get erratic muscle cramps in my neck whenever I see something that looks like it might turn out to be a `pushBack()` bug...

**Comment by OlivierNicole** [comment]
Would you happen to have any pointers to what a `pushBack()` bug is?

**Comment by alerque** [comment]
@OlivierNicole The `typesetter:pushBack()` function (found in `core/typesetter.lua`) is the logic that tries to handle material that was originally shaped for one frame context but didn't end up fitting and gets pushed into the start of the next frame. The trouble is it has to _unshape_ the contents, drop some things that are relative to the frame (glues that might be margins, etc.) then hope it all gets shaped right in the next frame context. It mostly works, but is notorious for having edge case bugs. We've rewritten it several times and it still isn't very robust.

**Comment by OlivierNicole** [comment]
I see.

**Comment by PapistPenguin** [comment]
Has there been any progress on this issue? How should I fix the last line stretching issue in the meantime?

**Comment by OlivierNicole** [comment]
@PapistPenguin One simply needs to remove [the temporary setting of `parfillskip` to a zero-width glue](https://github.com/sile-typesetter/sile/blob/193fded67edb7d33f65e3ebeb7b571285da5a8cd/packages/pullquote.lua#L39), which is the cause for that stretched line and is unnecessary given the way `pullquote` works.

I'll file in a merge request presently.

**Comment by alerque** [comment]
@OlivierNicole Do you have a working example (stripped down to as small an example as possible) that shows the second paragraph not indenting?

**Comment by OlivierNicole** [comment]
@alerque Sure.
```latex
\begin[class=plain]{document}
\script[src=packages/pullquote]

\begin{pullquote}
You wonder that there are so few followers of the Pythagorean opinion [that the
earth moves] while I am astonished that there have been any up to this day who
have embraced and followed it.

Nor can I ever sufficiently admire the outstanding acumen of those who
have taken hold of this opinion and accepted it as true: they have,
through sheer force of intellect done such violence to their own senses as
to prefer what reason told them over that which sensible experience
plainly showed them to the contrary.

For the arguments against the
whirling of the earth we have already examined are very plausible, as we have
seen: and the fact that the Ptolemaics and the Aristotelians and all their
disciples took them to be conclusive is indeed a strong argument of their
effectiveness. But the experiences which overtly contradict the annual movement
are indeed so much greater in their apparent force that, I repeat, there is no
limit to my astonishment when I reflect that Aristarchus and Copernicus were
able to make reason so conquer sense that, in defiance of the latter, the
former became mistress of their belief.
\end{pullquote}

\end{document}
```

**Comment by alerque** [comment]
Thanks. That does reproduce for me. I'll have a look.

I suspect this is related to our drop-cap woes (which we have so many issues about I don't even know which one to link to). The paragraph merger definitely feels familiar.
