### ISSUE TITLE
Would merging `SILE.registerCommand()` and `\define[command]{}` make sense?

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#866]
Since it just came up [again](https://github.com/sile-typesetter/sile/pull/863#discussion_r420618389) I've been reminded that when I first started using SILE I was puzzled by the difference between `SILE.registerCommand()` and `\define[command=...]{}`. Obviously one is traditionally used from Lua and the other from markup, but the latter is actually accessible to Lua and basically just a wrapper over the former.

I'm wondering what if any rational there is for maintaining both rather than merging them into one implementation that works in all contexts.

**Comment by simoncozens** [comment]
`SILE.registerCommand` just puts a Lua function into the hash; `define` specifically declares a *macro* made up of SILE input tokens, with all the stack handling and `\process` stuff and what have you. In my mind they're very different, but if you can find a way of unifying them, why not?

**Comment by Omikhleia** [comment]
Rejected:
- As stated by Simon, `\define` has a specific role.
- Inactive issue for more than 3 years
