### ISSUE TITLE
Error passing named functions as content

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#892]
I ran into an issue in CaSILE where passing a function as a content argument wouldn't work, but an anonymous lambda function would. See https://github.com/sile-typesetter/casile/commit/4f3c1d9e962730883955d90a4fbf588b3af36167.

Since I worked around the issue there temporarily I'm opening an issue here to track resolving it for real.

> Hey @OlivierNicole might you have a look at this? My brain isn't firing on all cylinders. The story is that I updated SILE on a system that builds a whole bunch of book builds for a translation project and all the CI jobs started dying. I eventually tracked it down to what you see in 4f3c1d9, which is the difference between passing a function by reference vs. a lambda. Why the blazes should it care all of a sudden? I suspect this has to do with the changes in https://github.com/sile-typesetter/sile/pull/863 — can you put your finger on why? It's not a big deal this use case as it is a relatively minor 'fix', but I can't help but think we buggered something up and broke something that should be working.

**Comment by OlivierNicole** [comment]
Time is unfortunately rare for me these days, but I'll try to look into it within the fortnight. In the meantime, feel free to revert my changes if needed.

**Comment by alerque** [comment]
No pressure mate, I really just hoped you'd have a guess off the top of your head. I wasn't sure I completely understood the change, and am even more puzzled by the issue it created. I'll assign this to you so it doesn't get lost, but don't feel pressured to work on it either. I may have another look, and at least I'll try to get an MWE going.

**Comment by alerque** [comment]
In spite of the scope crossover it seems this is _not_ connected to #863. While working on an MWE I tried reverting the relevant commit (52b516f) and still got the same error. I still have no idea what's going on but thought I'd throw that tidbit in here.

**Comment by alerque** [comment]
So the difference between 'works' and 'dies' isn't actually about lambdas vs. passing function pointers (phew!). The difference is whether the passed function has any calls to `SILE.process()` in it.

**Comment by alerque** [comment]
This goes back to de03e6a047130ec586be0efaa61d5e27bcc5b161 that throws an error when running `SILE.process()` with no content. As far as I can see this shouldn't be an error condition at all. It would be an error if we only ever got called from TeX-Like SIL code where at a minimum the `\process` macro is called with an empty content table `{}`, but doesn't make sense at all in a mixed world where we pass stuff around in Lua including function references as content. I don't see any harm in allowing `nil` as a value.

**Comment by alerque** [comment]
This is not fully fixed. I tried to ditch my workaround in CaSILE and it crashed again. It turns out my MWE only covers some of the potential cases, it doesn't cover the case of commands defined from TeX-like macros.
