### ISSUE TITLE
rotate.sil example broken

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#912]
https://github.com/sile-typesetter/sile/blob/09a653a7768e5e8006614fc7d4703c82996d17b6/examples/packages/rotate.sil#L1

```
$ sile -t rotate.sil
This is SILE v0.10.5
<tet.tex>
[1] 
Error detected:
	/usr/share/sile/packages/rotate.lua:11: bad argument #5 to 'setmatrix' (number expected, got table)
stack traceback:
	[C]: in function 'setmatrix'
	/usr/share/sile/packages/rotate.lua:11: in function '?'
	/usr/share/sile/core/frame.lua:194: in function 'enter'
	/usr/share/sile/core/frame.lua:49: in function 'init'
	/usr/share/sile/core/typesetter.lua:112: in function 'initFrame'
	/usr/share/sile/core/typesetter.lua:97: in function 'init'
	/usr/share/sile/core/typesetter.lua:716: in function 'typesetNaturally'
	/usr/share/sile/packages/folio.lua:36: in function 'outputFolio'
	/usr/share/sile/classes/plain.lua:25: in function </usr/share/sile/classes/plain.lua:24>
	(...tail calls...)
	/usr/share/sile/core/baseclass.lua:269: in function 'finish'
	/usr/share/sile/classes/book.lua:56: in function 'finish'
	/usr/share/sile/core/inputs-texlike.lua:169: in function 'process'
	/usr/share/sile/core/sile.lua:237: in function 'readFile'
	/usr/bin/sile:62: in function </usr/bin/sile:62>
	[C]: in function 'xpcall'
	/usr/bin/sile:62: in main chunk
	[C]: in ?

```

**Comment by ctrlcctrlv** [comment]
For me, this fixes it.

Not yet familiar enough with `sile` to know the purpose of what I removed, but my PDF looks no different at a quick glance than the one on the SILE website.

```diff
diff --git a/usr/share/doc/sile/examples/packages/rotate.sil b/rotate.tex
index 72e99a7..aecb13c 100644
--- a/usr/share/doc/sile/examples/packages/rotate.sil
+++ b/tet.tex
@@ -1,6 +1,4 @@
 \begin[class=book,papersize=129mm x 198mm]{document}%
-\frame[id=folio,rotate=45]%
-\frame[id=content]%
 \script[src=packages/rotate]
 
 \bigskip
```

**Comment by alerque** [comment]
Thanks for reporting this, there does seem to be some breakage our test suite didn't catch.

The thing you patched out is just avoiding the issue. There are supposed to be _two_ things rotated on that page, the website only shows a screenshot clip on of of them. The other one is the page number frame itself. Your patch just doesn't rotate the folio at all.

I'll look into why the frame rotation failed.

**Comment by simoncozens** [comment]
All of the frame dimensions (`self:height()`, `self:left()`, `self:right()`) are coming out as lengths of `0pt`.

**Comment by alerque** [comment]
Yes somewhere we're passing a raw number for math when it's expecting a Length or Measurement.

**Comment by ctrlcctrlv** [comment]
Yeah I did notice that, see here https://twitter.com/HW_BEAT_THAT/status/1280735816969420801

**Comment by alerque** [comment]
So ... the test suite isn't able to check this right now because of #902.
