### ISSUE TITLE
`rotate` package: Doesn't work unless non-rotated text on page first

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#913]
```tex
\begin[class=book]{document}%
\script[src=packages/rotate]
\script[src=packages/font-fallback]
\font[family=Noto Serif CJK JP]

% anymore % Uncomment me to unbreak everything

\rotate[angle=90]{
よくある質問（英語：FAQ）
}

\rotate[angle=90]{derp}

\end{document}
```

```
This is SILE v0.10.5

Error detected:
	packages/rotate.lua:53: PDF object not initialized!
stack traceback:
	[C]: in function 'gsave'
	packages/rotate.lua:53: in function 'outputYourself'
	/usr/share/sile/core/nodefactory.lua:528: in function 'outputYourself'
	/usr/share/sile/core/typesetter.lua:558: in function 'outputLinesToPage'
	/usr/share/sile/core/typesetter.lua:404: in function 'buildPage'
	/usr/share/sile/core/baseclass.lua:263: in function 'finish'
	/usr/share/sile/classes/book.lua:56: in function 'finish'
	/usr/share/sile/core/inputs-texlike.lua:169: in function 'process'
	/usr/share/sile/core/sile.lua:237: in function 'readFile'
	/usr/bin/sile:62: in function </usr/bin/sile:62>
	[C]: in function 'xpcall'
	/usr/bin/sile:62: in main chunk
	[C]: in ?

shell returned 1
```

**Comment by alerque** [comment]
This does look like a bug, thanks for reporting it.

That being said in this particular case with Japanese input rotating the text might not be the best feature to accomplish what you have in mind. Rotated text is not meant to for use with orthographies that have different advance directions. I think maybe changing the frame's writing direction might be what you are looking for. If rotation is the effect you are looking for rotating the whole frame is generally more controllable that rotating a bit of text.

Also note there are Japanese specific classes with extra features handling some of the nuances. @simoncozens would be able to speak more specifically to that, although I believe they are mentioned in the manual.

Lastly it is also helpful to inform SILE about the content language so it can apply language specific features properly.

**Comment by ctrlcctrlv** [comment]
Yes, he told me on Twitter about japanese.sil. Thank you. Still, this is a bug. :-)

**Comment by simoncozens** [comment]
This will fix it, by analogy with other things in pdf.lua:

```diff
diff --git a/packages/rotate.lua b/packages/rotate.lua
index 3c430db7..f504ecb0 100644
--- a/packages/rotate.lua
+++ b/packages/rotate.lua
@@ -46,6 +46,7 @@ local outputRotatedHbox = function (self, typesetter, line)

   local horigin = (typesetter.frame.state.cursorX + origbox.width.length / 2):tonumber()
   local vorigin = -(typesetter.frame.state.cursorY + origbox.height / 2):tonumber()
+  SILE.outputters.libtexpdf._init()
   pdf:gsave()
   pdf.setmatrix(1, 0, 0, 1, horigin, vorigin)
   pdf.setmatrix(math.cos(x), math.sin(x), -math.sin(x), math.cos(x), 0, 0)
```

But calling private methods on the outputter is a bit of a bad smell. Serhaps a tidier fix would be to make packages/pdf.lua more of a wrapper around low-level libtexpdf functions, and move the gsave/grestore/setmatrix stuff into there.

**Comment by alerque** [comment]
I'm going to add that smelly hack for now because a proper fix is pretty involved.
