### ISSUE TITLE
variables not usable in []

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#921]
So, I'm doing a little hacking...

## get.lua
```lua
local firstContentFrame = function(_, _)
  return SILE.documentState.thisPageTemplate.firstContentFrame
end

SILE.registerCommand("first-content-frame", firstContentFrame)
```

## test.tex
(I call my files `.tex` as too lazy to fix vim, and it's almost true.)
```tex
\begin[class=book]{document}
\script[src=packages/frametricks]
\script[src=packages/rotate]
\script[src=packages/font-fallback]
\script[src=packages/tate]
\script[src=get]
\font:add-fallback[family=Noto Serif CJK JP]
\language[main=und] % workaround for #915 (besides, this won't be mainly in Japanese)
\begin[first-content-frame=\first-content-frame]{pagetemplate}
\tate-frame[id=tate1,next=content,height=1zw,width=width(content),left=left(runningHead),top=top(runningHead)]
\end{pagetemplate}
\typeset-into[frame=tate1]{よくある質問（英語：\latin-in-tate{FAQ}）}
\showframe[id=all]
\end{document}
```

## Crashing and burning :fire: 
```
! Couldn't find frame ID \first-content-frame at:
	tet.tex:9:1: in \pagetemplatetable: 0x5645cb0ed020 after 10:1: in \tate-frametable: 0x5645cb0ed2c0
```

**Comment by simoncozens** [comment]
Yeah, you can't do that, but I don't really regard that as a bug. Any clever things like this you should be doing in Lua, not on the markup side. Think of SILE documents as actual documents, not code...

**Comment by alerque** [comment]
> ! Couldn't find frame ID \first-content-frame

1. You shouldn't have a backlslash in a frame id! More than just your VIM is stuck in TeX. Vim you can [fix with this](https://github.com/sile-typesetter/vim-sile). Your head is just going to take practive to untrain it from TeX-ish habits.

1. You haven't defined any frame by that name in your page template. You probably mean something like this:

    ```tex
    \begin[first-content-frame=tate1]{pagetemplate}
    ```

**Comment by ctrlcctrlv** [comment]
Oh, @alerque, actually you just reminded me, this `first-content-frame`, how I'm using it, doesn't matter at all, since I always call a `\typeset-into`.

```
\frame[id=twilightzone] % It is a dimension as vast as space and as timeless as infinity. It is the middle ground between light and shadow, between science and superstition, and it lies between the pit of man's fears and the summit of his knowledge. This is the dimension of imagination. It is an area which we call the Twilight Zone.
\begin[first-content-frame=twilightzone]{pagetemplate}
```

I still need this for the argument to \tate-frame, but can indeed do that in Lua, I think through `SILE.process`.

Thanks for tip&numero;3 btw

Anyway, closed per @simoncozens. :+1:

**Comment by alerque** [comment]
Also you can put Lua inline in your documents:

```
\begin{script}
-- Lua code here
\end{script}
```

(And yes the vim-sile plugin highlights the embedded code as Lua.)

**Comment by ctrlcctrlv** [comment]
Nice. I'm making an `fbox.lua` which will be reusable though :-)

**Comment by ctrlcctrlv** [comment]
(Also, darn, I'm starting to like @alerque. It's going to be hard to keep up my face firmly in "pouting mode" at alerque/libertinus#329. :joy:)
