### ISSUE TITLE
ruby.lua should not set lang=ja

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#926]
It seems strange that ruby.lua does this:

https://github.com/sile-typesetter/sile/blob/e5ee4679d2d6830f806183e3c11c34f83fbd972c/packages/ruby.lua#L2

I can't think of a legitimate reason to. Even if we assume ruby is only used for <span title="furigana">振り仮名<sup>🐣</sup></span> (it isn't!), they already should be using a Japanese class, right?

But ruby is often also used for pinyin, bopomofo, etc:

![image](https://user-images.githubusercontent.com/838783/86961346-ee04fe00-c115-11ea-9b2c-4a022801e429.png)

**Comment by alerque** [comment]
Sounds reasonable to me, but out of my depth to confirm.

**Comment by simoncozens** [comment]
OK, I see why it calls that - the idea was to do `\language[main=ja]{}`, loading up Japanese language support to get access to the "zw" (全角 width) unit, but scoping the change of language to the empty block. (Similar to `\font[...]{foo}` versus `\font[..] foo`. But it doesn't quite work. I'll fix it.

**Comment by alerque** [comment]
If the `zw` unit is useful across more that just Japanese, perhaps it should be moved somewhere higher up than the language support code?

**Comment by simoncozens** [comment]
In theory, maybe? In practice, while there is an extremely useful [W3C specification](https://www.w3.org/TR/jlreq/) for handling Japanese text, there's not a similar one for handling Chinese text, so I'm not currently in a position to support Chinese typesetting in the same way. If we do have something to share, we'll share it, but not yet.
