### ISSUE TITLE
Is there something like \overset?

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#935]
To set one letter (or what have you) over another.

\stackrel is similar

**Comment by simoncozens** [comment]
Have a look at \rebox. Documentation in the new docs branch: https://github.com/sile-typesetter/sile/blob/new-documentation/packages/rebox.lua

**Comment by ctrlcctrlv** [comment]
Thanks for that @simoncozens .

I don't think you ever answered, but is there a way to make `tate` not so tightly kerned/tracked/spaced? Here's another example. It's just a little too close in my opinion.

![](https://user-images.githubusercontent.com/838783/87175141-36532600-c2a6-11ea-9edb-c2901c3dcb28.png)

(You _do not_ want to see the code for this. LOL)

**Comment by simoncozens** [comment]
That's looking awesome. I *do* want to see the code for that because you seem to have solved #911.

**Comment by simoncozens** [comment]
Are you saying that the letters are too close to each other vertically? That's a function of your font and the "solid setting" rules in [jlreq](https://www.w3.org/TR/jlreq/#spacing_between_characters). We don't currently support tracking in Japanese because it would break the hanmen. File another issue with what you think you should be able to do, and I'll think about it.

**Comment by ctrlcctrlv** [comment]
Yes, I do mean vertically.

To me this one looks OK, from W3C site

![image](https://user-images.githubusercontent.com/838783/87176559-4835c880-c2a8-11ea-9fba-db5d56afb04e.png)

But I think there's too little vertical space. If it's up to the font, maybe I should try one of Adobe's...

**Comment by ctrlcctrlv** [comment]
Actually, the spacing has grown on me. It's on the high end of "solid" for sure, but it's within the allowable range. (I looked at some professionally-produced Japanese books to verify.) So, self closing. Thanks all.
