### ISSUE TITLE
Could not resolve all dependencies: libtexpdf.so

### ISSUE THREAD

**Issue by PapistPenguin** [sile-typesetter/sile#938]
When I try to install sile-git via AUR, I run into the following error:

```
Building sile-git...
==> Making package: sile-git 0.10.4.r40.g6fb42db-1 (Sun 12 Jul 2020 05:27:29 PM EDT)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> libtexpdf.so
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
```

How do I get around this?

Manjaro 20.0.3 64-bit

**Comment by alerque** [comment]
Oops my bad. I had started to setup sile & libtexpdf a separate packages but introduced the dependency before that was finished. It worked as long as you had a previous compatible version of SILE installed, but that's a cart-before-the-hourse situation.

Try it now, it should be fixed.

**Comment by PapistPenguin** [comment]
That worked. Thank you!
