### ISSUE TITLE
Copy-edit all chapters of manual for grammar, style, etc.

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#941]
Migrated undone todo item from #616 and split into chapters...

- [x] Chapter 1
- [x] Chapter 2
- [x] Chapter 3
- [x] Chapter 4
- [x] Chapter 5
- [ ] Chapter 6
- [ ] Chapter 7
- [ ] Chapter 8
- [ ] Chapter 9
- [ ] Chapter 10
- [ ] Chapter 11
- [ ] Chapter 12

**Comment by alerque** [comment]
It seems like #948 might have checked off a few of these boxes?

**Comment by biggnome** [comment]
One grammatical error I spotted at the end of 6.2:

> ...if you’re creating any serious document format yourself [...] `you’re` should expect to write it in Lua

**Comment by alerque** [comment]
Thanks @biggnome, that will be fixed in the next release.

**Comment by Omikhleia** [comment]
A lot of fixes went into #1712 -- Thanks @jslabovitz and @alerque !

We can always open dedicated issues for unnoticed typos and unsatisfying documentation content. -- This very generic issue can be closed IMHO.
