### ISSUE TITLE
Rework developer-facing documentation

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#942]
Extracted from undone todo list item on #616.

**Comment by Omikhleia** [comment]
Not sure what remains to be addressed here.

**Comment by Omikhleia** [comment]
Closing this issue:
- Lots of things addressed in #616 
- Lots of things addressed in other issues as well.

Having better developer documentation would be good, but let's consider this has to be clarified with explicit aims rather than a very generic issue without description.

**Comment by alerque** [comment]
This is definitely not completed, but I'll call it a duplicate of discussions scattered over #493, #1337, and #1692.

Right our our overall user and package specific documentation is much-improved, but our the core Lua API end of things is almost completely undocumented. I intend for this to be resolved with proper inline documentation generating an API docs website, with possibly a version of that then converted and placed in the manual, but not directly typeset only by SILE.
