### ISSUE TITLE
SILE to PDF Stops Working

### ISSUE THREAD

**Issue by PapistPenguin** [sile-typesetter/sile#945]
While I have been typesetting a book, I ran into an issue. I ran the SILE command but got back (among other things):
```
This is SILE v0.10.5
<newDominus.sile>

! Underfull frame: 507.664pt stretchiness required to fill but only 0pt available at newDominus.sile: in \open-double-page near 13:1: in \chapter
[1] 
! Underfull frame: 567.864pt stretchiness required to fill but only 0pt available at newDominus.sile: in \open-double-page near 13:1: in \chapter after in \supereject
[2] 
! Underfull frame: 552.864pt stretchiness required to fill but only 0pt available at </usr/local/share/sile/classes/book.lua:122>:3:36: in \par
[3] 
! Font family 'Libertinus Serif' not available, falling back to 'Gentium Plus' at newDominus.sile: in \raisetable: 0x55a0a585f550 near 23:1: in \pullquote

Error detected:
	/usr/local/share/sile/core/length.lua:96: attempt to index a nil value (local 'self')
```
I have noticed this happens at a certain point, but I am not sure how to avoid it. Removing text has worked, but now I cannot compile my SILE document anymore in its entirety, and retracing my steps has not helped.

**Comment by alerque** [comment]
Sorry you're having trouble. This is pretty clearly a bug in SILE (or possibly some function you wrote). The thing to do is add a `-t` flag to your SILE command to get a full traceback for what code was running at the time it ran into a problem. We should be able to deduce from that exactly what line of code is tripping up your document. If you can post the stack trace we should be able to solve it from there.

**Comment by PapistPenguin** [comment]
Thank you for the help. Here is the output:
```
This is SILE v0.10.5
<newDominus.sile>

! Underfull frame: 507.664pt stretchiness required to fill but only 0pt available at:
	/usr/local/share/sile/classes/book.lua:133: in \open-double-page
	newDominus.sile:13:1: in \chapter
stack traceback:
	/usr/local/share/sile/core/typesetter.lua:426: in method 'setVerticalGlue'
	/usr/local/share/sile/core/typesetter.lua:403: in method 'buildPage'
	/usr/local/share/sile/core/typesetter.lua:574: in method 'leaveHmode'
	/usr/local/share/sile/packages/twoside.lua:30: in field '?'
	/usr/local/share/sile/core/sile.lua:284: in function 'core/sile.call'
	/usr/local/share/sile/classes/book.lua:133: in field '?'
	/usr/local/share/sile/core/sile.lua:284: in function 'core/sile.call'
	/usr/local/share/sile/core/inputs-common.lua:65: in function 'core/sile.process'
	/usr/local/share/sile/core/inputs-texlike.lua:164: in field 'process'
	/usr/local/share/sile/core/sile.lua:237: in function 'core/sile.readFile'
	/usr/local/bin/sile:62: in function </usr/local/bin/sile:62>
	[C]: in function 'xpcall'
	/usr/local/bin/sile:62: in main chunk
	[C]: in ?
[1] 
! Underfull frame: 567.864pt stretchiness required to fill but only 0pt available at:
	/usr/local/share/sile/classes/book.lua:133: in \open-double-page
	newDominus.sile:13:1: in \chapter
stack traceback:
	/usr/local/share/sile/core/typesetter.lua:426: in method 'setVerticalGlue'
	/usr/local/share/sile/core/typesetter.lua:403: in method 'buildPage'
	/usr/local/share/sile/core/typesetter.lua:574: in method 'leaveHmode'
	/usr/local/share/sile/packages/twoside.lua:33: in field '?'
	/usr/local/share/sile/core/sile.lua:284: in function 'core/sile.call'
	/usr/local/share/sile/classes/book.lua:133: in field '?'
	/usr/local/share/sile/core/sile.lua:284: in function 'core/sile.call'
	/usr/local/share/sile/core/inputs-common.lua:65: in function 'core/sile.process'
	/usr/local/share/sile/core/inputs-texlike.lua:164: in field 'process'
	/usr/local/share/sile/core/sile.lua:237: in function 'core/sile.readFile'
	/usr/local/bin/sile:62: in function </usr/local/bin/sile:62>
	[C]: in function 'xpcall'
	/usr/local/bin/sile:62: in main chunk
	[C]: in ?
[2] 
! Underfull frame: 552.864pt stretchiness required to fill but only 0pt available at:
	</usr/local/share/sile/classes/book.lua:122>:3:36: in \par
	/usr/local/share/sile/classes/book.lua:115: in \book:chapter:post
	newDominus.sile:13:1: in \book:sectioningtable: 0x55591de50640
	newDominus.sile: in \fonttable: 0x55591de4ffb0
	newDominus.sile: in \book:chapterfont
	newDominus.sile:13:1: in \chapter
stack traceback:
	/usr/local/share/sile/core/typesetter.lua:426: in method 'setVerticalGlue'
	/usr/local/share/sile/core/typesetter.lua:403: in method 'buildPage'
	/usr/local/share/sile/core/typesetter.lua:574: in method 'leaveHmode'
	/usr/local/share/sile/core/typesetter.lua:255: in method 'endline'
	/usr/local/share/sile/core/baseclass.lua:177: in field '?'
	/usr/local/share/sile/core/sile.lua:284: in function 'core/sile.call'
	/usr/local/share/sile/core/inputs-common.lua:65: in function 'core/sile.process'
	/usr/local/share/sile/core/baseclass.lua:80: in field '?'
	/usr/local/share/sile/core/sile.lua:284: in function 'core/sile.call'
	/usr/local/share/sile/classes/book.lua:115: in field '?'
	...
	/usr/local/share/sile/classes/book.lua:211: in field '?'
	/usr/local/share/sile/core/sile.lua:284: in function 'core/sile.call'
	/usr/local/share/sile/classes/book.lua:137: in field '?'
	/usr/local/share/sile/core/sile.lua:284: in function 'core/sile.call'
	/usr/local/share/sile/core/inputs-common.lua:65: in function 'core/sile.process'
	/usr/local/share/sile/core/inputs-texlike.lua:164: in field 'process'
	/usr/local/share/sile/core/sile.lua:237: in function 'core/sile.readFile'
	/usr/local/bin/sile:62: in function </usr/local/bin/sile:62>
	[C]: in function 'xpcall'
	/usr/local/bin/sile:62: in main chunk
	[C]: in ?
[3] 
! Font family 'Libertinus Serif' not available, falling back to 'Gentium Plus' at:
	newDominus.sile: in \raisetable: 0x5559284a2940 near 23:1: in \pullquote
	newDominus.sile:23:1: in \pullquote
stack traceback:
	/usr/local/share/sile/core/harfbuzz-shaper.lua:36: in method 'shapeToken'
	/usr/local/share/sile/core/base-shaper.lua:62: in method 'measureChar'
	/usr/local/share/sile/core/units.lua:180: in field 'converter'
	/usr/local/share/sile/core/measurement.lua:82: in function 'core/measurement.tonumber'
	(...tail calls...)
	[C]: in function 'lpeg.match'
	/usr/local/share/sile/core/frame.lua:260: in function 'core/sile.parseComplexFrameDimension'
	/usr/local/share/sile/packages/raiselower.lua:3: in field '?'
	/usr/local/share/sile/core/sile.lua:284: in function 'core/sile.call'
	/usr/local/share/sile/packages/pullquote.lua:21: in local 'func'
	/usr/local/share/sile/core/settings.lua:45: in field 'temporarily'
	/usr/local/share/sile/packages/pullquote.lua:17: in upvalue 'typesetMark'
	/usr/local/share/sile/packages/pullquote.lua:42: in local 'func'
	/usr/local/share/sile/core/settings.lua:45: in field 'temporarily'
	/usr/local/share/sile/packages/pullquote.lua:36: in field '?'
	/usr/local/share/sile/core/sile.lua:284: in function 'core/sile.call'
	/usr/local/share/sile/core/inputs-common.lua:65: in function 'core/sile.process'
	/usr/local/share/sile/core/inputs-texlike.lua:164: in field 'process'
	/usr/local/share/sile/core/sile.lua:237: in function 'core/sile.readFile'
	/usr/local/bin/sile:62: in function </usr/local/bin/sile:62>
	[C]: in function 'xpcall'
	/usr/local/bin/sile:62: in main chunk
	[C]: in ?

Error detected:
	/usr/local/share/sile/core/length.lua:96: attempt to index a nil value (local 'self')
stack traceback:
	/usr/local/share/sile/core/length.lua:96: in function 'core/length.__add'
	/usr/local/share/sile/packages/grid.lua:19: in method 'leadingFor'
	/usr/local/share/sile/core/typesetter.lua:339: in field 'boxUpNodes'
	/usr/local/share/sile/packages/bidi.lua:239: in method 'boxUpNodes'
	/usr/local/share/sile/core/typesetter.lua:566: in method 'leaveHmode'
	/usr/local/share/sile/classes/plain.lua:207: in local 'func'
	/usr/local/share/sile/core/settings.lua:45: in field 'temporarily'
	/usr/local/share/sile/classes/plain.lua:203: in field '?'
	/usr/local/share/sile/core/sile.lua:284: in function 'core/sile.call'
	/usr/local/share/sile/packages/footnotes.lua:45: in field '?'
	/usr/local/share/sile/core/sile.lua:284: in function 'core/sile.call'
	/usr/local/share/sile/core/inputs-common.lua:65: in function 'core/sile.process'
	/usr/local/share/sile/core/inputs-texlike.lua:164: in field 'process'
	/usr/local/share/sile/core/sile.lua:237: in function 'core/sile.readFile'
	/usr/local/bin/sile:62: in function </usr/local/bin/sile:62>
	[C]: in function 'xpcall'
	/usr/local/bin/sile:62: in main chunk
	[C]: in ?
```

**Comment by alerque** [comment]
Thanks. Unfortunately this wasn't as enlightening as I was hoping it would be (note only the last stack trace is relevant, the others are for the earlier warnings, we don't care about those, only the final error is in question here). Each individual part as far as I see is okay, but some combination of parts (grid typesetting, bidi, footnotes?) are inducing a case we haven't tested for and that has a bug in it.

I also messed around a little with combining a grid typeset layout that triggers some bidi usage plus footnotes, but couldn't get it to fail.

```sil
\begin[class=book,papersize=a6]{document}
\script[src=packages/grid]
\font[family=Amiri]
\grid[spacing=2em]
\grid:debug
This and stuff أَبْجَدِيّ after soft break.\footnote{frogs }

\hfill.أَلْأَبْجَدِيَّة ٱلْعَرَبِيَّة

Another paragraph.
\end{document}
```

![image](https://user-images.githubusercontent.com/173595/87426277-9c61e500-c5e7-11ea-97d0-a4cdbfc587d0.png)

I'm afraid we may need something of an MWE from you to replicate this. The smaller the better. Usually I do this starting with the whole setup, then ripping out chunks of content and testing one step at a time until you narrow it down to as little content as possible, then drop settings until it becomes clear what feature or combination of features is triggering this.

**Comment by PapistPenguin** [comment]
Sorry for the delay.
The following works:
```
\begin[papersize=letter, class=book]{document}
\define[command=headline]{%
\medskip%
\font[family=Spectral,style=Bold Condensed,weight=700,size=20pt]{\center{\process}}
\bigskip%
}
\font[size=12pt]
\script[src=packages/grid]
\script[src=packages/pullquote]
\script[src=packages/linespacing]
\grid[spacing=15pt]
\headline{Dominus Iesus}
\chapter{Introduction}
\noindent
1. The \em{Lord Jesus}, before ascending into heaven, commanded his disciples to proclaim the Gospel to the whole world and to baptize all nations: 
“\font[language=la]{Euntes in mundum universum praedicate evangelium omni creaturae. Qui crediderit et baptizatus fuerit, salvus erit; qui vero non crediderit, condemnabitur}” (\em{Mk} 16:15-16); 
“\font[language=la]{Data est mihi omnis potestas in caelo et in terra. Euntes ergo docete omnes gentes, baptizantes eos in nomine Patris et Filii et Spiritus Sancti, docentes eos servare omnia, quaecumque mandavi vobis. 
Et ecce ego vobiscum sum omnibus diebus usque ad consummationem saeculi}” (\em{Mt} 28:18-20; cf. \em{Lk} 24:46-48; \em{Jn} 17:18,20,21; \em{Acts} 1:8).

The Church's universal mission is born from the command of Jesus Christ and is fulfilled in the course of the centuries in the proclamation of the mystery of God, Father, Son, and Holy Spirit, 
and the mystery of the incarnation of the Son, as saving event for all humanity. The fundamental contents of the profession of the Christian faith are expressed thus: 

\pullquote{
\font[language=la]{\noindent Credo in unum Deum, Patrem omnipotentem, factorem caeli et terrae, omnium visibilium et invisibilium. 
Et in unum Dominum Iesum Christum, Filium Dei unigenitum, et ex Patre natum ante omnia saecula, Deum de Deo, lumen de lumine, Deum verum de Deo vero, genitum, non factum, consubstantialem Patri : 
per quem omnia facta sunt; qui propter nos homines et propter nostram salutem descendit de caelis et incarnatus est de Spiritu Sancto ex Maria virgine, et homo factus est, crucifixus etiam pro nobis sub Pontio Pilato, 
passus et sepultus est, et resurrexit tertia die secundum Scripturas, et ascendit in caelum, sedet ad dexteram Patris, et iterum venturus est cum gloria, iudicare vivos et mortuos : cuius regni non erit finis. 
Et in Spiritum Sanctum, Dominum et vivificantem, qui ex Patre procedit, qui cum Patre et Filio simul adoratur et conglorificatur, qui locutus est per prophetas. 
Et unam sanctam catholicam et apostolicam Ecclesiam. 
Confiteor unum baptisma in remissionem peccatorum. 
Et exspecto resurrectionem mortuorum, et vitam venturi saeculi.}\footnote{First Council of Constantinople, \font[language=la]{Symbolum Constantinopolitanum}: DS 150.}
}
\end{document}
```
However, if you add a line to it like
`

2. In the course of the centuries, the Church has proclaimed and witnessed with fidelity to the Gospel of Jesus. At the close of the second millennium, however, `
then it keeps counting up and never ends in the Terminal like so:
```
! Underfull frame: 567.864pt stretchiness required to fill but only 0pt available at testing.sile: in <file> (\) after in \supereject
[1353] 
! Underfull frame: 552.864pt stretchiness required to fill but only 0pt available at </usr/local/share/sile/classes/plain.lua:93>:19:29: in \vfill
[1354] 
! Underfull frame: 567.864pt stretchiness required to fill but only 0pt available at testing.sile: in <file> (\) after in \supereject

```
If you add even more, like:
```

this mission is still far from complete.\footnote{Cf. John Paul II, Encyclical Letter \em{Redemptoris missio}, 1: \em{AAS} 83 (1991), 249-340.} 
For that reason, Saint Paul's words are now more relevant than ever: 
\font[language=la]{“Nam si evangelizavero, non est mihi gloria; necessitas enim mihi incumbit. Vae enim mihi est, si non evangelizavero!”} (\em{1 Cor} 9:16). 
This explains the Magisterium's particular attention to giving reasons for and supporting the evangelizing mission of the Church, 
above all in connection with the religious traditions of the world.\footnote{Cf. Second Vatican Council, Decree \em{Ad gentes} and Declaration \em{Nostra aetate}; cf. also Paul VI Apostolic Exhortation \em{Evangelii nuntiandi}: \em{AAS} 68 (1976), 5-76; John Paul II, Encyclical Letter Redemptoris missio.}

```
then it gets the error:
```
Error detected:
	/usr/local/share/sile/core/length.lua:96: attempt to index a nil value (local 'self')

```
Sorry for the long MWE. I hope this helps.

**Comment by PapistPenguin** [comment]
So, the file seems to compile if \grid[spacing=15pt]  is removed. Though, the line spacing is more compact than it should be. Is there a way to keep the grid? Line matching is a huge benefit I've read about SILE.

**Comment by simoncozens** [comment]
It's the interaction between grid and the \vbox of pullquote; somehow `totals.gridCursor` is not being set up correctly.
If you add `if not totals.gridCursor then totals.gridCursor = SILE.measurement(0) end` to line 18 of grid.lua it compiles, but that is clearly not the right fix. I'll keep digging.

**Comment by simoncozens** [comment]
Sorry, the \vbox of *footnote*, not pullquote.

**Comment by simoncozens** [comment]
OK, I have *two* potential fixes, but I wonder which is the right one. Suppose I have the following text:

```
\grid[spacing=15pt]
\lorem \footnote{\lorem}
```

what leading would you expect to see in the footnote?

1. Grid spacing
2. Normal spacing

Right now we have a clash between a "grid" typesetter and a "non-grid" footnote frame. We could resolve it either way.

**Comment by PapistPenguin** [comment]
Personally, I would expect grid spacing unless declared otherwise, if I understand your question rightly. Also, after changing grid.lua, it produces:
```

Error detected:
	/usr/local/share/sile/core/measurement.lua:9: attempt to index a nil value (local 'b')

```

**Comment by alerque** [comment]
Oh spiffy, infinite loops _and_ hard crashes. Good morning to you too!

Thanks for the MWE, that helps a lot. I'll be looking into how to fix both problems. First two general comments:

1. I noticed you're ending all your lines with spaces. This is actually perfectly valid and you can keep doing it, I just thought it might be worth mentioning that you don't have to and indeed SILE will add spaces between any content lines it joins as part of the same paragraph. Not putting the spaces manually makes it slightly easier to move content around, split paragraphs differently, etc. without having to check whether you do or don't want the trailing space. Personally I find it easier to work with source control systems and make it though the editing process without them, your millage may vary.

2. About grid.

   > Line matching is a huge benefit I've read about SILE.

   While it's true that being able to typeset on a grid is an advantage SILE brings to the table over many other options, keep in mind that grid typesetting is not good in all situations. It mitigates *a specific problem* or perhaps a couple of problems, but it can also actively harm your output in some cases. In order for it to be useful in most print situations ⓐ you have to have very high page alignment accuracy (low tolerances for shifting between pages, known as 'registration'), something most print shops cannot provide and ⓑ you are printing on very thin or translucent paper than shows some bleed though.

   Without especially that first issue of accurate registration being in place, I've found grid typesetting can actively make book printing *worse*. Don't reach for grid printing just because it's better for some scenario, make sure it's right for your scenario. It might be the best choice for a high quality Bible print, it might be wrong for most other scenarios.

   In the case of your sample document, I suspect using a different line spacing method to set your leading will actually lead to better results overall. There are a variety of ways to calculate line spacing depending on how you want it to handle different size fonts and other considerations.

   Of course you can also prefer the visual effect and the way you can use different size text elements of a page and have it keep the vertical rhythm. There should be no technical barrier to using it, and we'll fix the bugs this has raised so that it can be used. I just wanted to throw out there that using a grid just to get bigger leading between elements is probably not the right tool.

**Comment by alerque** [comment]
> what leading would you expect to see in the footnote?

Personally I would have expected regular linespacing in the footnote frame — but then I actually have in my head the way SILE handles typesetters and frames and don't expect that property to carry over.

I think the best place to set this would be some analog to `\footnote:font` that configures the footnote frame's typesetter, or even a property on the frame itself (a callback to run when entering the frame?).

Having footnote frames default to grid typesetting just because the content frame is that way seems like a problematic can of worms to me, especially since we align grids to leading frame edges!

**Comment by PapistPenguin** [comment]
Thanks for the reply! Sorry for the delay. So, I actually have some Bible typesetting projects started in LaTeX that have been put on pause due to the limitations with LaTeX. I was very excited to hear about SILE! Right now, I'm trying to get a feel for it, use the same tools I would for any Bible or otherwise needy projects I would like to resume in SILE.
So, I find that many programs have a unique style for their footnotes which I usually modify. I don't know the technical side of it that much, but--in regards to the grid--I would want them aligned, for visibility, such as with thin Bible paper, just like the rest of the text. However, I don't know if that is common in Bible typesetting.

**Comment by alerque** [comment]
I've been playing around with this on v0.13.1 and am no longer able to get a failure off of the MWE's shown above. I don't know if we fixed it or if the target scenario that triggered the failure just moved. Anybody have input into this?

**Comment by alerque** [comment]
Nevermind, found it...
