### ISSUE TITLE
Multiple things can't be debugged

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#970]
```
:!sile -d texmode -d frames nondet.sil && firefox nondet.pdf
```

```
/usr/bin/lua: /opt/share/sile/lua_modules/share/lua/5.2/std/base.lua:397: bad argument #1 to 'find' (string expected, got table)
stack traceback:
	[C]: in function 'find'
	/opt/share/sile/lua_modules/share/lua/5.2/std/base.lua:397: in function 'split'
	/opt/share/sile/core/sile.lua:137: in function 'parseArguments'
	/opt/bin/sile:39: in main chunk
	[C]: in ?
```

**Comment by alerque** [comment]
Sure they can, just make the debug flags a comma separated list:

    sile -d texmode,frames nondet.sil

Also note enabling `-t` is pretty useful.

I'll keep this open because adding the flag multiple times like that is actually a syntax we *should* support.

**Comment by ctrlcctrlv** [comment]
Sorry I didn't think of that, seems undocumented, and other flags can be repeated :)

**Comment by alerque** [comment]
The previous syntax (comma separated) was document in the manual, §12.4. I've added the ability to use multiple flags as well because sometimes that's easier to script.
