### ISSUE TITLE
unichar package doesn't work with combining characters

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#979]
Compare output of
```
â
```
And

```tex
a\unichar{0x302}
```

**Comment by ctrlcctrlv** [comment]
Sorry @alerque 

Seems I made wrong assumption, when a specific combining char did not work, that all are broken

Here is a MWE

![image](https://user-images.githubusercontent.com/838783/88267474-e2c9da80-cc9e-11ea-98d6-4d158d916a24.png)
[MWE.zip](https://github.com/sile-typesetter/sile/files/4964756/MWE.zip)

**Comment by alerque** [comment]
Hmm, that's curious. Is there another font you can reproduce this with? I tried Noto with no luck:

```sile
\begin{document}
\script[src=packages/unichar]
â
a\unichar{0x302}

% \font[filename=./FRBTaiwaneseKana.otf]
\font[family=Noto Sans CJK TC]
セ𛌟
セ\unichar{0x1b31f}
\end{document}
```

![image](https://user-images.githubusercontent.com/173595/88268527-496ce980-ccdb-11ea-8f4b-9377edb25600.png)

**Comment by ctrlcctrlv** [comment]
Um, @alerque , all due respect, Noto wouldn't have 0x1B31F, since it's unencoded 😂 

So what you're seeing out of Noto there is the .notdef character, not a combining mark.

See also &sect; 1.1.3 of [[1]](https://drive.google.com/file/d/1H8SVHqdDu-V497XrL3uotfXsS7eoipx7/view?usp=sharing)

The way I implemented marks in my font really shouldn't break just because `\unichar` is used, right? If it works w/o `unichar`, it should work with?

I think maybe the reason a&#x302; is working and my example not is `ccmp` (GSUB) vs. `mark` (GPOS).

**Comment by alerque** [comment]
Of course I saw it was unencoded. I just didn't know what other font to turn to as a reasonable comparison test. Are there any other fonts that have tried to implement this yet? Or is that the only demonstration font to work with?

I'm actually more surprised that shaping works correctly with combining marks added via `\unichar` at all than that it failed for this case. In my head's model the tokenization vs. command processing order would have killed the shaper's ability to see the combination at all.

As for why `ccmp` vs `mark` would make a difference ... I'm getting out of my depth. @simoncozens is probably going to have to review this.

**Comment by alerque** [comment]
There might even be more than one bug here. Not that `â` and `a\unichar{0x302}` are not actually producing the same output either.

![image](https://user-images.githubusercontent.com/173595/88271269-93f06500-ccdf-11ea-86ba-df6b682b6a1f.png)

```sile
\begin{document}
\script[src=packages/unichar]
% \font[filename=./FRBTaiwaneseKana.otf]
% \font[family=Noto Serif CJK TC]
\font[family=Symbola]
\raggedright{
â\break
a\unichar{0x302}

セ𛌟\break
セ\unichar{0x1b31f}
}
\end{document}
```

**Comment by simoncozens** [comment]
I understand this problem: the characters are ending up in different nnodes, and so are passed to harfbuzz as separate runs. unichar should probably instead add text to the last unshaped node. Will work on it.

**Comment by alerque** [comment]
That was my first thought too but why does it seem to work for a+combining-circumflex also via `\unichar{}`?

**Comment by simoncozens** [comment]
It doesn't. The font is returning a non-spacing (zero-width) combining accent in that case.

I have a fix, just working on a test.

**Comment by alerque** [comment]
```console
$ make -j12 dist
Makefile:1456: *** missing separator.  Stop.
```

I've been trying to beat `make` into submission for ~~hours~~ days. Now I have random a-circumflex characters in my Makefile. No they don't help.

**Comment by simoncozens** [comment]
Actually the test is pretty simple, since the text mode tells us what ended up in what shaping run.
