### ISSUE TITLE
Unichar package should accept HTML entities

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#984]
Would you all accept a patch to allow...

```tex
\unichar{&uarr;}\unichar{&sect;}
```
instead of only

```tex
\unichar{0x2191}\unichar{0xA7}
````

?

Call me brainworm-infested, but hundreds of HTML entities are a permanent part of my long term memory...

**Comment by alerque** [comment]
My suggestion would be to nod overload the `\unichar` with anything other than Unicode code points. HTML entity names are a whole 'nother kettle of fish. How about an `\htmlentity` instead?

**Comment by ctrlcctrlv** [comment]
Thanks for your reply :-)

I'll think about how to make it work in `vim`...

**Comment by ctrlcctrlv** [comment]
<sup>btw @alerque check your Twitter DMs please 😄</sup>

**Comment by alerque** [comment]
For VIM:

```viml
abbreviate &sect; §
abbreviate &uarr; ↑
```

You probably want to hid that behind an autocommand for some file types but not others. Better yet there seem to be a number of related plugins.
