### ISSUE TITLE
tate and the immortal 章

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#990]
Importing `tate` creates a 章 that persists despite a call to `\language`, and despite the fact that `tate` allegedly no longer calls `\language` itself.

SILE v0.10.9.r36-gf16af44, Xubuntu 20.04

```tex
\begin[class=book]{document}
\script[src=packages/font-fallback]
\script[src=packages/tate]
\define[command=open-double-page]{\noindent\par}
\language[main=en] % I don't seem to matter :-(
\font:add-fallback[family=Noto Serif CJK JP]
\chapter{It's all good in the hood}
It is
\section{Wait, maybe it's not...}
Oh no
\language[main=ja]
\chapter{私たちの近所で、すべてはいつも大丈夫だぜ！}
うん、そう
\section{いつもいつも}
いつもだぜ
\end{document}
```
![image](https://user-images.githubusercontent.com/838783/88753069-59485b80-d129-11ea-879d-dc712e3ac9f8.png)

Workaround: 
```tex
\define[command=book:chapter:post]{\skip}
```

**Comment by simoncozens** [comment]
OK, I see why that's happening. Simpler example:

```
\begin[papersize=a5,class=book]{document}
\language[main=ja]
\language[main=en]
\chapter{Hello}

\end{document}
```

Fix coming soon.

**Comment by ctrlcctrlv** [comment]
Sorry @simoncozens ... @alerque also always shortens my MWE's ... I really do try to make them short, but seems brevity isn't my strong suit. Hope I'm not too annoying.

**Comment by alerque** [comment]
No worries on the MWE front @ctrlcctrlv, just make them as short as you can figure out with a reasonable amount of effort. It's sometimes easier to see how to shorten an MWE after we find the root problem, it's sometimes hard before that! Your last several have been quite useful to get us on the right track.
