### ISSUE TITLE
\add-font-feature; \remove-font-feature. Why not \font-feature?

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#992]
Seems strange. Am I missing something?

**Comment by simoncozens** [comment]
Hmm. Not sure now you mention it. Feel free to add and submit a PR. :-)

**Comment by ctrlcctrlv** [comment]
@simoncozens Would you accept me adding it to `\font`? So...

```
\font[family=EB Garamond, Letters=SmallCaps]
```

We can quite simply say that for the `\font` command going forward, all capitalized option names refer to features, and non-capitalized refer to font itself, so no new features will ever collide.

**Comment by simoncozens** [comment]
Not sure what I think about that. I don't really want this kind of higher-level handling (including all the option parsing) adding further complication to the already convoluted `core/font.lua`. If you can find a way to do it out of core - write a package which wraps the font command, perhaps - then fine.

**Comment by ctrlcctrlv** [comment]
@simoncozens I can have `features.lua` wrap `\font`. :-)

**Comment by alerque** [comment]
You know this already works from `\font` right? For example small caps would be `\font[features=+smcp]`. I don't think we want a whole series of meta labels for open type features, directly turning them on and off my name

**Comment by ctrlcctrlv** [comment]
@alerque I've already done a ton of work. I am aware of `\font[features=...]` yes. It's not what I want, I'm used to `fontspec`. We're already maintaining the "meta aliases", and I'm already using them in my docs, just want them better accessible.

```
 packages/features.lua   | 143 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------
 tests/font-features.sil |  11 ++++++++
 2 files changed, 129 insertions(+), 25 deletions(-)
```

Please don't reject before PR even opened...
